### ISSUE TITLE
NodeSchool chapter at Chennai,India

### ISSUE THREAD

**Issue by vikene** [nodeschool/organizers#103]
Hello,

 I would like to start a nodeschool chapter for Chennai, India. I am Vigneash Sundar (@vigneashsundar) on twitter. I am a grads student. I Have been using node.js in many of my projects for a while. I would like to help others to learn as well. 

Cheers :+1:

**Comment by finnp** [comment]
Great :+1:  I just added you to the organisation. Sorry that it took so long. You can now go ahead and follow these steps: https://github.com/nodeschool/organizers#1
