### ISSUE TITLE
Add as an Owner

### ISSUE THREAD

**Issue by nitins-optimus** [nodeschool/organizers#105]
Hie, Add me as an owner in this repo.

**Comment by finnp** [comment]
@nitins-optimus Hey! Where and why do you want to be added as an owner? Can you tell us more about you and what you are planning?

**Comment by LaughingSun** [comment]
HI, can you add me as owner (I am following the instructions from point 1 of the readme.md)

Hi, I would like to start a nodeschool chapter for Denpasar (in Bali, Indonesia). I am "Erich Horn"(https://www.facebook.com/erich.seac) on facebook and work at Laughing Sun (US company) remotely from my home in Denpasar. I will be co-organizing this chapter with Lia Horn and likely one ot 2 others (to be named as the chapter gains new members). I have been using Node.js one and off for 2 years (approx. 6 months total) and would like to help others learn as well.  I have extensive experience in programming, web and mobile application development for over 20 years.

I look forward to promoting and being a part of the larger global nodejs community.

**Comment by martinheidegger** [comment]
@nitins-optimus closing it for now, please re-open if needs be.
