### ISSUE TITLE
Nodeschool chapter for Stuttgart, Germany

### ISSUE THREAD

**Issue by kwakayama** [nodeschool/organizers#106]
Hi, I would like to start a nodeschool chapter for Stuttgart, Germany. I am @wakayamakentaro on twitter and work at [Brandwatch](http://www.brandwatch.com/). I have been co-organizing the [JS meetup in Stuttgart](http://www.meetup.com/stuttgartjs/) and want to create an event which focus on Node.js. I have been using Node.js for more than 4 years and would like to help others learn as well.

**Comment by finnp** [comment]
Awesome to have another chapter in Germany :+1:  I invited you to the org. You can now go ahed and [create a repo](https://github.com/nodeschool/organizers#1). Make sure to make a PR to the homepage to have the capter be featured there.
