### ISSUE TITLE
NodeSchool at Kirovohrad, Ukraine

### ISSUE THREAD

**Issue by ghaiklor** [nodeschool/organizers#107]
Hi, I would like to start a nodeschool chapter for Kirovohrad, Ukraine. I am @ghaiklor on twitter and work at [Onix-Systems](http://onix-systems.com). I will organize this chapter myself (Kirovohrad is small town). I have been using JavaScript more than 4 years and Node.js more than 1 year. I would like to help others learn as well.

**Comment by finnp** [comment]
Awesome :tada: I invited you to the organisation. Go ahead and follow these steps next: https://github.com/nodeschool/organizers#1
