### ISSUE TITLE
Add as Owner for nodeschool Denpasar, Bali

### ISSUE THREAD

**Issue by LaughingSun** [nodeschool/organizers#108]
HI, can you add me as owner (I am following the instructions from point 1 of the readme.md)

Hi, I would like to start a nodeschool chapter for Denpasar (in Bali, Indonesia). I am "Erich Horn"(https://www.facebook.com/erich.seac) on facebook and work at Laughing Sun (US company) remotely from my home in Denpasar. I will be co-organizing this chapter with Lia Horn and likely one ot 2 others (to be named as the chapter gains new members). I have been using Node.js one and off for 2 years (approx. 6 months total) and would like to help others learn as well. I have extensive experience in programming, web and mobile application development for over 20 years.

I look forward to promoting and being a part of the larger global nodejs community.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @LaughingSun Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
