### ISSUE TITLE
Nodeschool Gov/DC

### ISSUE THREAD

**Issue by ascott1** [nodeschool/organizers#109]
Hi, I would like to start a nodeschool chapter for US govies/DC. I am [@adamdscott](https://twitter.com/adamdscott) on twitter and work as a fellow for the [Consumer Financial Protection](http://cfpb.github.io/) Bureau. I will be co-organizing this chapter with [@contolini](https://twitter.com/contolini). I have been using Node.js for ~1 year and would like to help others learn as well.

A little more detail:

The CFPB has a design and development fellowship program with 30 remote team members. Though few of us are DC based, we'll all be in DC during the majority of January and would love to put together a nodeschool event on 1/28. We already have a [location](http://mybigchief.com/) who has also graciously agreed to supply pizza and beverages. 

I tried reaching out to @omidify who owns the DC chapter repo but haven't yet heard back. Since we're not actually DC based, this may be a one time event or potentially something that could happen quarterly when all of the CFPB fellows are in DC.

Thanks!

**Comment by jasonrhodes** [comment]
Hey @ascott1! Sounds like a great idea for an event! I'm interested in hearing what other organizers have to say about it, but it sounds to me that if it's going to possibly be a one-time or somewhat infrequent event, that's even more reason to try to sync up with NodeDC crew if possible. I would try connecting with @joshfinnie, @adunkman, @mcwhittemore, or @danmactough as they work with the NodeDC meetup group and have expressed interest in DC NodeSchool events.

I think that would be better than potentially having two different DC chapters, what do others think?

**Comment by ascott1** [comment]
That makes a lot of sense to me! I'll try reaching out them directly.

**Comment by adunkman** [comment]
@ascott1 heck yeah! NodeDC would be all about this — very exciting. Also, I’m not the best to help you out right now, as I’ll be out of town until around the 21st or so.

@joshfinnie/@ascott1 let me know if I can help in any way!

**Comment by ascott1** [comment]
This is excellent! Thanks for all of your help @joshfinnie and @adunkman! I'm going to close this issue and we can all talk directly.
