### ISSUE TITLE
NodeSchool International Exchange

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#110]
The NodeSchool is operating worldwide. I thought it would be nice if an Organisation (Kickstarter campaign) could sponsor the travel of various mentors from various countries to various countries?! To foster international exchange and a improvement & understanding of the progress (how nodeschool works) that sounds very awesome to me!

**Comment by prochafilho** [comment]
I am down. I volunteer to host mentors... how can we make this happen? This is a great idea!

**Comment by martinheidegger** [comment]
My first thoughts are that we should ask people that are willing to host/travel to X for NodeSchool events. Then we prioritise those persons (simple vote?) and define a fixed budget per person of, say, 1200 USD / person (should cover quite a bit of travel costs, considering places like south america or living costs in the US/UK). After prioritising we create a campaign, the more money we get the more people can be supported to travel.

**Comment by martinheidegger** [comment]
Closing the issue for now due to lack of interest. Please reopen freely.
