### ISSUE TITLE
Most common problem on windows: setup!

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#115]
Going through the issue list I feel like installing node on windows is uncomfortable at the least. It seems to me like those problems might be solve in the next version of node (or at least they can be addressed after the next release) but until then: Do you know a good resource on how to workaround node installation problems on windows? It would be awesome if an experience windows mentor could give a reliable document for common problem cases.

**Comment by sudodoki** [comment]
For windows there's rather good path of least resistence using [official installer](http://nodejs.org/download/). 
For most part my advice to those using node on windows was to use http://msysgit.github.io/ + follow advice from http://msysgit.github.io/. For me personally, the Microsoft Visual Studio Express did the trick (although .net should in theory provide same capabilities when it comes to building native dependencies on win). I would also give a tip on specifying its version, like `npm install %packagename% --msvs_version=2012`. 
To check setup, one should  run `npm i ws`.

**Comment by martinheidegger** [comment]
@sudodoki  Thank you for your suggestions! Very important tips hidden here that I had no idea about. I recently tried to use the official installer on a friends notebook but it didn't setup the `npm` and `node` commands correctly! I don't know how to properly debug that.

**Comment by jasonrhodes** [comment]
I *think* the main thing about the Windows installer is that it installs a
shell that you have to use. If you use that shell, everything seems to work
ok, in our experience at Baltimore nodeschool events and at Empire Node.

**Comment by martinheidegger** [comment]
I just figured out that the bash that comes with Git bash comes with the version "3.1.x" of bash ... not "4.x" . Good to know, hard to work with https://github.com/msysgit/git/issues/301 .

**Comment by martinheidegger** [comment]
![screenshot 2015-01-20 02 33 09](https://cloud.githubusercontent.com/assets/914122/5804828/bbf7c64e-a04c-11e4-8526-459b56db9c2a.png)

Another problem is that Node.js looks like this after the installation on Windows 7 (Only showing the Node REPL Button!!!). 

To get to the command prompt people need to access the subnavi:

![screenshot 2015-01-20 02 34 29](https://cloud.githubusercontent.com/assets/914122/5804848/f505cd3c-a04c-11e4-8680-025d46c45047.png)

Very un-user-friendly...

**Comment by martinheidegger** [comment]
Just a reminder (in case i forget to post in detail): It seems like installing anything `-g` can be irreversible on windows 7. In the classroom there was the case that someone installed `learnyounode-jp` and tried to update to `learnyounode` which resulted in a "ghost-file" (the learnyounode binary) that really didn't exist  therefore wasn't deletable. Only after a restart that file was really gone. While the file was not gone `npm remove` and `npm install` didn't work showing an `EPERM` error while trying to delete the binary.

**Comment by maxkorp** [comment]
You *can* set up git to work in the local terminal, but it can be funky. Best bet tbh for a more *nixy environment is cygwin, loathe as I am to suggest that. That said, I don't know that you really want to be forcing a *nixy environment on windows devs anyways. Sticking with the defaults is probably the best, if a bit kludgy. 

Regarding node, you don't have to use the node.js command prompt. In my experience, it does still add node to the path in the default command prompt. Getting people to find the windows command prompt is a whole different problem, but I'd recommend [CMDer](http://bliker.github.io/cmder/). PowerShell is also an option, but some native modules can play oddly with it the first time they compile, for some reason.

**Comment by a0viedo** [comment]
maybe @othiym23 can give us a hint here

**Comment by Sequoia** [comment]
what's *the one* simplest, *the one* most reliable way to get `workshopper` up and running on windows?  It is true that you can get it running from anywhere-- I did my first workshops in PowerShell, but for the purposes of nodeschool there should be a single recommendation that is easy & works for 90+% of people (i.e. don't bother with or even mention PS or cmd.exe if nodeshell works).

Does such a method exist? Let's identify it & anoint it. :droplet:

**Comment by vikene** [comment]
guess cmd.exe is fine. path variables are done by node :+1:  but , i had an issue on windows 8/8.1. like node missed out npm folder at %appdata%  :-1: so had to manually create a folder over there , then things went fine.

**Comment by martinheidegger** [comment]
Not all workshoppers work with the basic node installation. I think at least with some MS Visual Studio is necessary, right?

**Comment by a0viedo** [comment]
@martinheidegger not at least for the core ones: stream-adventure, git-it, javascripting and learnyounode.

I haven't tried with the rest of them.

**Comment by martinheidegger** [comment]
> Does such a method exist? Let's identify it & anoint it. :droplet:

The recommended way should contain the workflow for the extended workshoppers too.

**Comment by Sequoia** [comment]
@martinheidegger That sounds good, but for the users I'm most interested in supporting (and who *need the most support*) are those who are brand new & have never used node(and are doing `learnyounode`, `javascripting`, `stream-adventure`.  Having **one** clear windows install workflow for them would be very valuable --2 options is confusing ("which one do I use??")-- and it could hit the 80% of the users who are most in need.

Presumably users who want to learn more about GLSL shaders or experimental ES6 frameworks are more equipped to sort out issues.

I'd propose that in the FAQ or instructions the "windows install" has 1 main, basic approach, with "still not working? Here's some tips for more advanced workshoppers."

Where is this gonna go anyway? Not sure we have a spot for it quite yet :question:

**Comment by martinheidegger** [comment]
This issue is meant to produce a information sheet on how to install node the best way. I just came up with this: https://github.com/nodeschool/discussions/wiki/Installation-suggestions Perhaps we should improve upon it incrementally.

**Comment by othiym23** [comment]
For future reference, there is a [pretty OK troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting) that we've put together to help with supporting npm users, and it goes over a bunch of the things you touched on in this thread.

There are definitely usability problems getting new users up and running on Windows, especially because there are a variety of issues with the official .msi installers, and they're all slightly different on Windows 7, Windows 8, and Windows 8.1. @vikene, I haven't seen the %APPDATA% problem you describe with Windows 8.1. I'm pretty sure that's a Windows 7 or Windows 8 problem.

One thing that you might look at is getting people up and running with nodist and / or chocolatey. They're what I use to manage my OSS stuff on Windows, and it's _way_ easier than dealing with bare .msis.

Anyway. I'm available to help you all with npm stuff, although I don't have a lot of time. Just mention me when you need me!

**Comment by vikene** [comment]
@othiym23, cool :+1: . npm 1.4.28 on windows 8.1 does have %APPDATA% error. This is what i get with node 0.10.35
![0 10 35](https://cloud.githubusercontent.com/assets/7505422/5890478/b54f3572-a482-11e4-8edd-aac7e2a866b6.png) .
