### ISSUE TITLE
Nodeschool chapter for Cologne / Germany

### ISSUE THREAD

**Issue by peterhecker** [nodeschool/organizers#116]
Hi, I would like to start a nodeschool chapter for Cologne / Germany. I am phecker65 on twitter and work at/on GFU Cyrus AG. I will be co-organizing this chapter with Michael Reichart. I have been using Node.js for 6 months and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @peterhecker  
Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
