### ISSUE TITLE
Organizing a New Node School Chapter

### ISSUE THREAD

**Issue by azizali** [nodeschool/organizers#117]
Hi, I would like to start a nodeschool chapter for Chicago, IL. I am @heyaziz on twitter and work at https://iLoveCoding.org.

I will be co-organizing this chapter with people I am yet to confirm. I know a couple of friends, but the list is not confirmed.

I have been using Node.js for 10 months and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @azizali

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
