### ISSUE TITLE
New Nodeschool Chapter

### ISSUE THREAD

**Issue by tommymcdonald** [nodeschool/organizers#118]
Hello!, I would like to start a Nodeschool chapter for Athens, Georgia. On twitter, I am @tmacdotio and I currently work as a front-end developer at https://www.rentpost.com

I will be collaborating this endeavour with developers from Vitamin C (medical software) and Hackyard Athens, a local nonprofit geared toward teaching people to code.

I have been using Node to prototype apps for over a year, and am currently building out an enterprise level app in node / angularjs, and have been for the past 4 months.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @tommymcdonald 

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!

**Comment by jlord** [comment]
Shoutout to the great state of Georgia :peach: (I'm from Warner Robins, woo woo!)
