### ISSUE TITLE
NodeSchool Kochi, India

### ISSUE THREAD

**Issue by abyv** [nodeschool/organizers#119]
Hi, I would like to start a nodeschool chapter for Kochi. I am @AbyV on twitter and run IT services company Advanced Millennium Technologies. I also organised NodeSchool Bangalore and last week we completed the first evet in Bangalore. http://www.meetup.com/Bengaluru-Nodeschool-Event/. . We would like to conduct the NodeSchool program as a CSR activity of Advanced Millennium Technologies in Kochi(where we also have a branch office).

**Comment by martinheidegger** [comment]
@abyv since you are already in the organisers list: please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
