### ISSUE TITLE
YYJ

### ISSUE THREAD

**Issue by matchdav** [nodeschool/organizers#120]
Hey, I would like to start a nodeschool chapter.  I live in Victoria, BC, Canada. I don't have any co-hosts yet but am working on it. I have been using Node.js for 2 years, I run the Victoria Node Meetup, and would like to spread the good word.  Because TJ doesn't, like, talk, ever.

Either /victoria or /yyj would be an OK handle.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @matchdav 

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
