### ISSUE TITLE
Western Mass Chapter Application

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/organizers#121]
Hiyo,

I'm Sequoia, @_sequoia on twitter. I've been using node, mostly for fun, for a while now.  I *love* nodeschool/workshopper. After working thru several lessons I've tried to contribute thru lesson text & markdown cleanup and by giving [a](https://nerdsummit.org/nodeschool) [couple](https://nerdsummit.org/nerdsummit-2014/sessions/nodeschool) Nodeschool workshops out here in Western MA together with @a-pasquale & logistical support from @kellyalb.  We're currently planning to run a series of 3 workshops (probably in late Feb, March, April).  I would greatly appreciate input from people who have run workshops like this before.  (Where can I discuss my plan for this & solicit feedback?)

While I liked the quick & easy aspect of past workshops it looks like this new "chapters" setup has a lot of value, so I look forward to getting it up and running! Thanks nodeschool people & go team! :clap: :clap: :100:

**Comment by Sequoia** [comment]
Also: where buy stickers? Or get a high quality version of the logo (is there an official logo)? I'd love to use the old, green logo, though I'm sure it's currently "off-brand"... :wink:

**Comment by maxogden** [comment]
there are some templates here http://hexb.in/ and here https://github.com/finnp/nodeschool-stickerify

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @Sequoia 

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
