### ISSUE TITLE
New Chapter in Portland Maine

### ISSUE THREAD

**Issue by carlodicelico** [nodeschool/organizers#122]
Hi, I would like to start a nodeschool chapter for Portland, Maine. I am the technical cofounder of 
http://vonvo.com/about (built with Node, Mongo & Meteor) and work as a senior engineer at Cashstar (http://cashstar.com), where we use Node for our static asset build process - more at http://diceli.co. I will be co-organizing this chapter with a couple of coworkers - Shawn Campbell and Eric Loren. I have been using Node.js for about a year and a half and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @carlodicelico 

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
