### ISSUE TITLE
NodeSchool Mexico city

### ISSUE THREAD

**Issue by jeduan** [nodeschool/organizers#124]
Hi, I would like to start a nodeschool chapter for Mexico City. I am @jeduan on twitter and work at clevertech. I will be co-organizing this chapter with @rogr . I have been using Node.js for 3 years, organizing local meetups for 18 months and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @jeduan

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
