### ISSUE TITLE
Starting a chapter in Kuala Lumpur, Malaysia

### ISSUE THREAD

**Issue by soggie** [nodeschool/organizers#125]
Hi, I would like to start a nodeschool chapter for Malaysia. I am @roguejs on twitter and work at/on some minor contributions to koa, and am currently building my own simple webserver `naws`. I am also the founder of [Javascript Developers Malaysia](https://www.facebook.com/groups/javascript.my/) and the event [Nodehack](https://www.facebook.com/groups/nodehack), which are both related to javascript, while nodehack was an effort to evangelise node.js adoption in Malaysia. I have been using Node.js for 3 years (and many more for general javascript) and would like to help others learn as well.

I've been to JSDC Taiwan twice as a speaker, and the organisers have expressed some interest in bringing JSDC to Malaysia and Singapore as well. Right now I have quite a few contacts for venue, including one of the more active tech groups in Kuala Lumpur ([Webcamp](https://www.facebook.com/groups/webcamp/)), which our user group is affiliated to.

Hope you guys are cool with that, we want to use this as a platform to improve adoption of node in Malaysia, as well as reach out to under-privileged children to give them a valuable professional skill to uplift their lives.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @soggie
Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!

**Comment by soggie** [comment]
Thanks @martinheidegger. We'll be setting up the pages and everything else soon. :)

**Comment by martinheidegger** [comment]
@soggie btw.: did you know that this exists: https://gitter.im/nodeschool/organizers ?
