### ISSUE TITLE
Setup a NodeSchool Foundation

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#126]
As an excerpt from https://github.com/nodeschool/discussions/issues/402 I open here the issue that people would love to have an foundation that helps people develop the NodeSchool content and organize eventually full-time schools or bigger events.

**Comment by eafelix** [comment]
great idea!
what exactly you 've been thinking?

**Comment by martinheidegger** [comment]
@eafelix My understanding is that a Foundation would be a NPO with the aim to foster the NodeSchool (run events, improve the documents etc.). Since a foundation needs money it needs to be a construct in a country owned by a person. To start a foundation a few people would need to put together the funding. Those will be the main organisers of the foundation. From there on they try to get funding through various activities. The Foundation will be run like a company except that the none of the financial gains is returned to stockholders. But there would need to be yearly financial reports etc.

Before anyone starts this I think it would be best to hear from people if they would like to see a foundation popping up (no consent = problematic). Then those few poeple choose a country in which to start the foundation and then they search for contributors (money).

**Comment by mikeal** [comment]
I can take this up and lead it.

Because our mission is education related we can actually apply for a proper 501(c)3 license and collect tax deductible donations from the public.

There's a couple local foundations in Oakland that could help get this off the ground as well. Also my wife Anna knows a little something about non-profit accounting so she'll be a big help.

**Comment by martinheidegger** [comment]
@mikeal Awesome if you can take the lead on this. I would love to hear the voice from @rvagg @maxogden @sethvincent @timoxley and other "heavy commiters" on that matter.

**Comment by mikeal** [comment]
A few things we need to worry about:

* Formal structure *can* demotivate contributors if they feel out of touch with the institution.
* Money doesn't always fix problems, it can also cause problems.
  * If we start paying *some* people to do things that most people are currently doing for free it will de-motivate a lot of the people doing it for free because they love it.

We should have a clear list of things we *want* to do but are currently not able to do because of a lack of foundational support and financing. The one I'd personally like to focus on is getting NodeSchool in to some after school programs targeted at much younger kids. From there possibly even formalizing a curriculum people could teach in a classroom. Of course this would all remain free and be openly contributed to and maintained by the community.

What else?

**Comment by martinheidegger** [comment]
@mikeal I am sharing those "worries". My thinking is: I want the foundation to:

- Create a badge (certification) program
- Offer organisational support of the communities (i.e. talk to companies if necessary)
- Eventually pay people to review workshoppers for technical and linguistical correctness (not create them!)
- Organise international exchanges (or alike)
- Do reporting on things that the NodeSchool does that can be shown to companies

**Comment by eafelix** [comment]
we can get some advice from people at Mozilla, have a voice with experience to see these things. so we have no trouble managing things like money or administrative matters

**Comment by mikeal** [comment]
> Create a badge (certification) program

I'm -1 on this. One of the secrets to the success of this ecosystem so far has been that we've intentionally blurred the lines between organizer, mentor and student. I've seen students who *just* sat down and finished half a workshopper mentor work with other students and mentor them on the lessons they have just completed. Creating level of certified people and badges gives people the impression that "I'm a student, I don't mentor" and "I'm a mentor, I'm not an organizer" and I want to avoid that at all costs.

> Offer organisational support of the communities (i.e. talk to companies if necessary)

Yup, this is hard, and potentially a full time job.

> Eventually pay people to review workshoppers for technical and linguistical correctness (not create them!)

This should be a pure community effort, especially on the translation front. All the best translations I know of are community based and not paid for. Ubuntu and Mozilla are the biggest and most successful. Also, the io.js website team is spinning up translations right now so we should work with them and learn from each other.

> Organise international exchanges (or alike)

This is basically what @maxogden has been doing on his own dime and it has made a noticeable difference.

> Do reporting on things that the NodeSchool does that can be shown to companies

And schools. Companies and School want a PDF with charts and numbers. It is INSANELY BORING to create but we aren't benefiting from not having it :)

**Comment by mikeal** [comment]
@eafelix I used to be at Mozilla. They are a very unique and special organization, which ends up meaning that a lot of their approach and tactics don't port well. I'll sit down with Ace Monster Toys some time next month (a local oakland non-profit hacker space that runs many public workshops) and see what I can learn and one of the founders, Al Billings, also works at Mozilla :)

**Comment by blakmatrix** [comment]
:+1: On this discussion

I see a lot of talk about certification/badges (getting something longer lasting and physical out of attending nodeschool - I find this counterintuitive based on the real value being a part of the community and participating during the workshop events) 

The second thing I see a lot popping up in my e-mail are regarding the workshop themselves. I think this might be a great area for a foundation to vet... but then again to what @mikeal is saying is that this could detract from the community effort if an organization is in control and not the community.

I believe that a Foundation will be great if it's purpose is to serve the community and not take anything away, a support role of sorts, while the real champions are You, I, and the entire nodeschool community. The foundation should have little to no power to change anything about nodeschool.

**Comment by mikeal** [comment]
> RE: vetting workshops

IMO the more people running local events the better, and the more people writing workshops the better. So I'm -1 on adding vetting or other barriers to entry to the *creation* of either. 

But, we already have a long and confusing list of available workshops. If we organize them in to "curriculum" at some point in time there will obviously be a process around getting your workshop in a particular curriculum. Again though, that should be a community effort and not "enforced" or meddled with by the foundation.

Similarly, we have some "sustainability" issues that have come along with the proliferation of events. We can and should do more to help mentor organizers and help them *keep* their events goings. I'd love a group of people dedicated to following up with organizers 1month, 3months, 6months after they start to help them keep going. That can also be a pure community effort but that group may find that it helps to send someone in person, which requires money, which is something the foundation could do.

**Comment by mikeal** [comment]
> Seeing as my effort is based on meeting with @maxogden I am deeply grateful. However it is a constant effort/strain to keep communication going, a organisation should ease the way imho.

I brought up max as sort of a template for what is working and what we should continue but understanding that it isn't sustainable to rely on it indefinitely. The foundation could help pay more than one person to do this, and offer them the flexibility of time to follow through and communicate what they learn on those trips.

**Comment by martinheidegger** [comment]
How about lets close this discussion and open a "foundation" repo with issues on all the points?

**Comment by mikeal** [comment]
I'd like to see input from a few other key people before we do a repo.

**Comment by maxogden** [comment]
Sorry I've been busy lately, haven't found much time to participate in nodeschool discussions this month. 

I personally think these talks are kind of premature -- our number one priority should be increasing the number of active committers we have, in these areas (in order of importance:

- Workshop maintainers (individual workshop repositories)
- Common tools for organizers. E.g. better guides on our website, more written materials about how to run a nodeschool chapter. There is a lot of innovating left to be done in terms of what a nodeschool chapter is, we are still in the early stages here IMO
- Discussions issue-triagers

I have a short term plan to increase these numbers by convincing CTOs at a bunch of companies to budget 1 hour of developer time for someone on their node team a week to contribute to nodeschool, but there are a *lot* of things that need to be done to make this a success, most of them are standard open source contribution flow problems e.g. making it easy to find ways to contribute.

**Comment by jasonrhodes** [comment]
+1 @maxogden 

I was writing a response but this does nicely.

**Comment by martinheidegger** [comment]
@maxogden 
1. Workshop maintainers are a big issue, having a foundation could ease the load for them and thusly improve the incentive for working on things and doing it.
2. Yes, a chapter is loosely defined. Somehow I thought that was by design :) 
3. This issue was opened as part of my effort in `issue-triage`. I think we are well on the way to reduce the issues to a healthy amount by end of next week!

How I see it an organisation could help be at best supporting for the issues that you listed at worst not conflicting with them. Active members in the Organisation mean active members in the NodeSchool to me.

**Comment by olizilla** [comment]
I'm conflicted. I'm all like _"I'd love a job at nodeschool"_, but I fear that a nodeschool foundation would create a divide that doesn't currently exist and all the items raised in:
https://github.com/nodeschool/organizers/issues/126#issuecomment-71231968

I've seen first hand in the level of responsibility and elbow-grease available from volunteers plummets as soon as there is someone in a paid role in the org. Maybe I've jumped the gun here, but I'm assuming that a foundation would also entail some ongoing funding requirements and hiring people to do stuff.

**Comment by mikeal** [comment]
Quick reality check, just we're all on the same page:

* We can have a California Non-Profit setup in a less than a week. However, getting it approved as a 501(c)3 federally will as much as two years.
* If we want more contributors in a particular area, paying individuals to do it will likely *decrease* the number of community contributions. We've seen this time and time again, the intrinsic motivation begins to die once you start paying people for work the community used to do for free.

In a year or two I want to be in a place where we can start approaching schools. A non-profit doesn't help us get there, a bunch of other work by contributors does, but once we're there we'll *need* this already setup which is why I think it's good to talk about it now.

**Comment by maxogden** [comment]
I'm okay having you register a legal entity for the sole purpose of credibility, as long as any other purposes are thoroughly discussed w/ the organizers before any structure is put in place :)

**Comment by mikeal** [comment]
@maxogden if only it were so simple, we need to write a mission statement and charter and an initial board of directors and nothing *else* can be done without the board approving it anyway :) YA AMERICA!

**Comment by martinheidegger** [comment]
@maxogden @mikeal I think either way it might be better to create a "foundation" repo that deals with all the details (from a mission statement to charter to "if we do it at all"). Discussions in one long thread tend to stay unresolved.

**Comment by blakmatrix** [comment]
@martinheidegger this discussion thread is *only* 4 days old, and realitvely few organizers have responded. I feel that it's premature--it hasn't even been a full work week--to indicate the discussion is over on whether a nodeschool foundation should be created. 

As I just read @maxogden just indicated his opinion is that other than credibility any purpose for such a foundation should be thoroughly discussed with volunteer organizers of nodeschool while @mikeal just indicated, that while we might be able to create said foundation, once it's created nothing else could be done without the board approving it, so unless the board can be comprised of all current and future organizers, the same discussion as above will not occur unless the board moves on it... thus taking the entities purpose out of the hands of the very community that contributed to it.

**Comment by martinheidegger** [comment]
@blakmatrix I am not sure I am being clear: I am saying the opposite of "The discussion is over" I am saying it is going to take a lot longer (with several sub-threads). This discussion is already "TL;DR." to me :) I am thinking of a way how other people can contribute to this discussion in a structured way.

**Comment by blakmatrix** [comment]
I see, however, I still feel it's yet premature to move away from this discussion format without more representation, if this idea should be squashed it should be done here. I believe that closing this so soon and opening a "foundation" repo will create a self-fulfilling prophecy, one where NodeSchool might inadvertently start taking shape around this notion of a singular legal entity, rather than around the community that is still in the early stages of learning. 

If we **have to** move this so soon, I would ask that we take care to not send the wrong signals, to make it *clear* even in the repo name that it's discussion only.

**Comment by martinheidegger** [comment]
@blakmatrix Thank you for the input.

I opened the mission statement & charter statements in own issues. Once they are discussed I think it should be clear if we need one.

**Comment by martinheidegger** [comment]
Closing issue due to lack of interest / momentum.

**Comment by mikeal** [comment]
Pulling @kylemitchell in because he expressed interest in this :)

**Comment by iancrowther** [comment]
I would be interested @martinheidegger

**Comment by kemitchell** [comment]
I'm interested in contributing. If the right solution requires legal work---and I'm _not_ here to say that it is---I can probably help.

I will skim this issue for background, but see that it's both old and closed. If there's a better place or way for me to "plug in", please let me know.

**Comment by mikeal** [comment]
@kemitchell maybe just create a new issue :)
