### ISSUE TITLE
CLA definition

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#127]
We write a lot of content here and in the workshoppers. In other bigger open source projects they use Committer License Agreements's to make sure that the projects arn't stealing something etc. 
[This is Jquery's](http://contribute.jquery.org/CLA/).
The CLA process is quite comfortable if we use [CLAHUB](https://www.clahub.com) but a definition would be nice. In Apache & JQuery's case the CLA's reference a [Foundation](https://github.com/nodeschool/organizers/issues/126)... 

I would like to add this to workshoppers, etc. Do you know how to define a CLA?

**Comment by mikeal** [comment]
-1 on a CLA. You can accomplish all the important parts by just adding the DCO to the contributing file. This is what we're doing in `io.js` already.

**Comment by maxogden** [comment]
related: https://github.com/nodeschool/nodeschool.github.io/issues/219
