### ISSUE TITLE
Nablus

### ISSUE THREAD

**Issue by salahassi** [nodeschool/organizers#128]
Hi, I would like to start a nodeschool chapter for Nablus. I am @NablusTM on twitter.  I will be co-organizing this chapter with Nablus Technical Meetups. I have been using Node.js for years and would like to help others learn as well.

**Comment by finnp** [comment]
Hey @salahassi, I just invited you to the organisation :). You can now set up a `nablus` repository.

**Comment by martinheidegger** [comment]
Referencing #28

**Comment by salahassi** [comment]
Thanks :)
