### ISSUE TITLE
NodeSchool chapter for Islamabad 

### ISSUE THREAD

**Issue by itsnauman** [nodeschool/organizers#131]
Hi, I would like to start a nodeschool chapter for Islamabad, Pakistan. I am @itsnauman on twitter and am a student developer. I will be organizing this chapter myself for now. I have been using Node.js for 6 months and would like to help others learn as well.

**Comment by finnp** [comment]
Hey @itsnauman. That's great. I invited you to the organisation, so you can create the `islamabad` repo :).  You can follow the rest of the guide here: https://github.com/nodeschool/organizers#1

**Comment by itsnauman** [comment]
Thank you!
