### ISSUE TITLE
New Chapter in St. Louis, Missouri

### ISSUE THREAD

**Issue by brianalbrecht** [nodeschool/organizers#132]
Hi, I would like to start a nodeschool chapter for St. Louis, MO. I am @balbrecht on twitter am the Director of Architecture for CenturyLink's Managed Services Development Center. I will be co-organizing this chapter with a number of other CenturyLink Developers including Brian Felton, Steve Tarver, and Eric Manley. I have been using Node.js for a year and would like to help others learn as well.

**Comment by maxogden** [comment]
@brianalbrecht hey awesome!

I am getting CenturyLink Gigabit Fiber (FTTH) installed right now in Portland :) is node used widely there?

I invited you to the owners org, after you accept you can continue following the instructions from the organizers readme

**Comment by brianalbrecht** [comment]
It’s the most popular runtime on CenturyLink Appfog, which is still managed out of Portland.  I can’t speak to the quality of the local fiber, though.  ;)

Awesome!  Thanks, Max.  I’ll get  a good readme out there over the weekend.
