### ISSUE TITLE
Madrid Chapter

### ISSUE THREAD

**Issue by alexfernandez** [nodeschool/organizers#133]
Hi, I would like to start a nodeschool chapter for Madrid. I am @pinchito on twitter and work at MediaSmart Mobile. I will be co-organizing this chapter with @gootyfer. I have been using Node.js for 3 years now and would like to help others learn as well.

Thanks, and keep up the good work!

**Comment by finnp** [comment]
Go Europe! :es:  Awesome. I just invited you to the organisation.  You can now create the repository `madrid` and follow the rest of the guide here: https://github.com/nodeschool/organizers#1.

**Comment by alexfernandez** [comment]
Awesome, thanks!
