### ISSUE TITLE
Nodeschool Vegas Chapter

### ISSUE THREAD

**Issue by makenai** [nodeschool/organizers#134]
Hi, I would like to start a nodeschool chapter for Las Vegas. I am @makenai on twitter and work at Zappos.com. I have been using Node.js for ~2 years and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @makenai

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
