### ISSUE TITLE
Nodeschool Chapter Dublin

### ISSUE THREAD

**Issue by No9** [nodeschool/organizers#135]
Hi, I would like to start a nodeschool chapter for Dublin. I am @dhigit9 on twitter and work at/on secure-scuttlebutt and a bits of leveldb. I will be co-organizing this chapter with @jasonmarah @_johnbrett_ @akohli @davecocoa7 @lorcanmcdonald @gangleri_ (twitter handles). I have been using Node.js since 0.2 and would like to help others learn as well.

**Comment by davecocoa** [comment]
:wave: I am @davecocoa / @davecocoa7 on twitter. I like JS and helping people learn new things.

**Comment by gangleri** [comment]
GitHub: @gangleri Twitter @gangleri_

**Comment by gangleri** [comment]
Any idea of numbers? I have one potential venue in the cente that could handle 15 and will have WiFi

**Comment by No9** [comment]
@gangleri seems a little light but it is way better than nothing so big thanks. 
Are we ok for the Saturday May 23rd as mentioned here? 
https://github.com/nodeschool/international-day/issues/2

**Comment by No9** [comment]
I am thinking there could be 4 coming from my current place

**Comment by johnbrett** [comment]
Hey everyone, Github is @johnbrett, Twitter @_johnbrett_, been using Node here and there on personal projects over the few years, using it in work for the last 9 months or so. I've enjoyed working with it and would like to help others learn about it and JS in general too.

Saturday May 23rd works for me too!

**Comment by gangleri** [comment]
@No9 I haven't confirmed yet, wanted to check numbers first. If you want I could push forward and see if it can be confirmed for Sat 23rd May.

**Comment by No9** [comment]
@gangleri sure check it. 
Would be great to know when we have to confirm the commitment.

**Comment by gangleri** [comment]
@No9 I'll ask the questions and see if we can have something for Sat 23rd May :smile:

**Comment by gangleri** [comment]
@No9 Sat 23rd May is ok we can have the space, it's OpenJaw on capel st. so nice and central.

Numbers are probably around 15.

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @no9

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
