### ISSUE TITLE
Nodeschool Chapter Boston

### ISSUE THREAD

**Issue by jstreb** [nodeschool/organizers#136]
Hi, I would like to start a nodeschool chapter for Boston.  I am currently the co-organizer of the [node.js meetup in boston](http://www.meetup.com/Node-js-in-the-wild/).  We love what nodeschool is doing and want to start offering some workshops as part of our meetups.  (Great way to get the community more involved)

@foop37 on twitter.
@twalling is the co-organizer of the meetup.

**Comment by bahtou** [comment]
Let's get this going. This is be a great way to bring beginners and enthusiasts together to learn and work on projects. The meetup in Boston is great and having a Nodeschool chapter will definitely further solidify and expand the community. Plus, we want to contribute to Nodeschool electives :+1:

**Comment by martinheidegger** [comment]
Following #28 I invited you to the owners list @jstreb  

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
