### ISSUE TITLE
idea: use our /discussions dataset for interesting things

### ISSUE THREAD

**Issue by maxogden** [nodeschool/organizers#137]
we have about 900 discussions here: https://github.com/nodeschool/discussions/issues

I was thinking that it could be **really cool** to:

- extract all the data from the discussions, as JSON (maybe set up something that is easy to run to do this at regular intervals)
- use this data to build better tools, e.g. n00b friendly search pages or an Atom plugin that helps you when you are stuck when doing a nodeschool workshop

**Comment by jasonrhodes** [comment]
+1000 I love this idea. Would be easy enough to read data, thinking about how to store based on how we want to consume I suppose. 

Is anyone doing anything like this already?

**Comment by martinheidegger** [comment]
@jasonrhodes I doubt it. Would love to see it though, a lot of content should already be somehow well tagged.

**Comment by finnp** [comment]
I think it would be awesome to have a bot, that would look through a newly posted issue and look for similar issues and link them automatically.

**Comment by iancrowther** [comment]
I'd like to mine the data and give us a way to address the common issues.  A FAQ's that can indeed be utilised in an Atom plugin.  The key thing here for me though, is to resolve the issues that cover the highest % of users.  We cant win em all, but we can aim for good coverage

**Comment by finnp** [comment]
Okay I've set up a small service over here: http://162.243.127.144

You can use it to [get all the issues](http://162.243.127.144/issues) (updated every hour) from an ndjson stream  or [search for issues](http://162.243.127.144/search?q=learnyounode%206)

I am only downloading the issues right now, not the comments. Would be cool to maybe add a nice search interface as well. Code is over here: https://github.com/finnp/nodeschool-questions

**Comment by iancrowther** [comment]
Nice, I'm just kicking around the idea of finding the most common words and visualising via a 

o_O    

... "tag-cloud" 

or some means of quickly addressing the most frequently mentioned terms

**Comment by iancrowther** [comment]
@finnp I think the JSON has a formatting issue?

![screen shot 2016-01-22 at 14 07 13](https://cloud.githubusercontent.com/assets/76060/12512650/7a471790-c111-11e5-9b10-6ebc5298f3ce.png)

**Comment by finnp** [comment]
@iancrowther Yeah something like a tag cloud could be interesting as well. The API doesn't return JSON, but [ndjson](http://ndjson.org/)

**Comment by iancrowther** [comment]
Got it, ok cool

**Comment by fforres** [comment]
Kudos to @finnp :D
Will surely use this for our next session :)

**Comment by finnp** [comment]
I used it to create a search function for a `nodeschool` atom plugin: https://github.com/finnp/atom-nodeschool

**Comment by iancrowther** [comment]
much RT's - very cool

**Comment by martinheidegger** [comment]
Closing this issue here. I think knowing that it exists is very valuable. Future effort will need to go into visibility.
