### ISSUE TITLE
Nodeschool Chapter Auckland

### ISSUE THREAD

**Issue by jladuval** [nodeschool/organizers#138]
Hi, I would like to start a nodeschool chapter for Auckland, New Zealand. I am @JacobDuval on twitter and I'm a co-founder of Mish Guru. We run node across everything we can and we really want to get the nodeschool chapter started here. I will be co-organizing this chapter with Kevin Isom (@kev_nz). I have been using Node.js for 2 years and would like to help others learn as well.

There already exists a node chapter for Auckland (https://github.com/nodeschool/auckland) but the repo is dead and we can't get in touch with the guy. We already have 50 people coming to our next nodeschool event so it would be great if we could take that over somehow. Otherwise we're happy to make a new one.

**Comment by martinheidegger** [comment]
Hello @jladuval 

Probably @ram-manthry is busy at the moment. I added you as repo owner and to the owners of NodeSchool. I hope @ram-manthry and you can organise events together.
