### ISSUE TITLE
Request to be added as owner

### ISSUE THREAD

**Issue by xarus01** [nodeschool/organizers#139]
Hi, I would like to start a nodeschool chapter for Seoul. I am @xarus01 on twitter and work at/on iojs/iojs-kr. I will be co-organizing this chapter with our team. I have been using Node.js for a year and a half and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hi xarus01, wink from over here in Osaka!

Following #28 I invited you to the owners list

Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!
