### ISSUE TITLE
Opening a new chapter for Manizales, Colombia

### ISSUE THREAD

**Issue by gmauricio** [nodeschool/organizers#140]
Hi, I would like to start a nodeschool chapter for Manizales, Colombia. I am @mauriciomunoz. I have been using Node.js for more than a year, we're starting a local Javascript community, where one of our goals is to help others start learning about Javascript technologies.

**Comment by jeduan** [comment]
Go Manizales!

**Comment by finnp** [comment]
Awesome, I just invited you to the organisation :palm_tree:  You can now continue with these steps: https://github.com/nodeschool/organizers#1
