### ISSUE TITLE
Nodeschool Chapter Xi'an

### ISSUE THREAD

**Issue by howiehu** [nodeschool/organizers#143]
Hi, I would like to start a nodeschool chapter for Xi'an.

I am @howiehu on twitter/github and work at "ThoughtWorks Inc."

I am on a project named "ThoughtWorks Academy" for teaching students/beginners how to programming with javascript.

I will be co-organizing this chapter with @jtong on github.

I have been using and teaching Node.js for 7 months and would like to help others learn as well.

We want to take nodejs/io.js to all school/company technology communities.

**Comment by eafelix** [comment]
Great! Welcome!

**Comment by howiehu** [comment]
If we want to organizing nodeschool chapter in other city, could we use some other name like "Nodeschool ThoughtWorks Academy"?

**Comment by martinheidegger** [comment]
@howiehu Chapters are bound to physical locations so people can attend freely. Just open a new chapter for the other city you want to host!

**Comment by howiehu** [comment]
@martinheidegger Ok, thanks.

**Comment by martinheidegger** [comment]
Since you are an owner you should be able to open a chapter by following https://github.com/nodeschool/organizers/blob/master/README.md!
