### ISSUE TITLE
Salt Lake City, Utah, USA

### ISSUE THREAD

**Issue by majgis** [nodeschool/organizers#145]
Hello,

I would like to start a node school chapter for Salt Lake City, Utah, USA.  My name is Michael A. Jackson, aka. [majgis](http://majgis.com/).

I have been using Node.js since January 2013.  Mostly as a front-end build tool, but I'm steadily increasing my skills on the backend.

I am currently the organizer for [Utah Node Ninjas](https://github.com/Utah-Node-Ninjas), which is the Provo, Utah chapter.

My plan is to restructure a bit and organize Provo and Salt Lake City Node Schools under the UNN banner, so they can share resources.  My goal is to focus on encouraging attendants to finish all nodeschool lessons as well as hosting presentations.

Current co-organizers include [@joeycozza](https://twitter.com/joeycozza) and [@ryancswapp](https://twitter.com/ryancswapp)

Thank you.

**Comment by martinheidegger** [comment]
Hello @majgis 

Following nodeschool/organizers#28 I invited you to the owners list
Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!

Note: Your name is awesome! Michael ajax!

**Comment by majgis** [comment]
Funny, I never thought of Michael Ajax...

Thank you!
