### ISSUE TITLE
Kanpur, India

### ISSUE THREAD

**Issue by abdul** [nodeschool/organizers#146]
Hello,

I would like to start a node school chapter for Kanpur, India. My name is Abdul Qabiz (@abdulqabiz).

I have been using Node.js since 2012 in my hacks, projects and development and devops workflow.

I plan to organise workshops to share what I know, and also learn about Node.js (and ecosystem around it). I am also co-founder of a startup over here, hence venue/space/wifi is available; we love to host such events.

Thank you.

**Comment by martinheidegger** [comment]
Hello @abdul 

Following nodeschool/organizers#28 I invited you to the owners list
Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!

**Comment by abdul** [comment]
@martinheidegger thank you.
