### ISSUE TITLE
Nodeschool Chapter Wroclaw

### ISSUE THREAD

**Issue by grabbou** [nodeschool/organizers#148]
Hi guys,

Awesome idea, I am really impressed! :+1: 

I would like to start regular node school chapters in Wrocław, Poland on kind of monthly basis (probably impossible, but 'from time to time' is a good description). As open source contributing is not that popular in my country, I'd like to promote this way of spending our free time as a great way to learn, teach and discover new friends!

My twitter/github/gmail/everything nickname is @grabbou, feel free to contact me or follow (maybe this will give some extra motivation to keep my twitter account more up to date with my thoughts hah)

Currently I am working at Explosive Titles heading the R&D office from Poland. I started my journey with Node more or less a year ago. At ET we are doing some interesting things like cloud based platform aggregating social media data in real time from user provided hashtags with proxying stuff and lots of streams and that's one of the things I'd like to share with others. 

As other JS communities are quite huge here (meet.js, ng-conf and stuff) it's not a problem to organise a venue as those meetings usually happen in either casual pubs or co-working spaces where I am currently working. Couple of my JS friends are also interested in setting that up here although as I am the ops guy, wanted to set up the basics first.

Thanks again for considering my request and have a nice weekend! 

Mike

**Comment by martinheidegger** [comment]
Hello @grabbou

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
