### ISSUE TITLE
how can I avoid getting subscribed to everything?

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/organizers#149]
is there a way to not get subscribed to every new nodeschool chapter's repo?

**Comment by martinheidegger** [comment]
No, but you can unsubscribe them (just as  I do)

**Comment by maxogden** [comment]
@Sequoia you can adjust your settings here https://github.com/settings/notifications but that is for *all* repos

**Comment by Sequoia** [comment]
ty max & martin.
