### ISSUE TITLE
NodeSchool Chapters for Miami and Fort Lauderdale

### ISSUE THREAD

**Issue by khalifenizar** [nodeschool/organizers#151]
Hi everybody! My name is Nizar Khalife and I would like to start two NodeSchool chapters: one for Miami and the other for Fort Lauderdale. I am @khalifenizar on Twitter and all other things. I currently work for [Ironhack](http://ironhack.com/en), a coding bootcamp in Miami. Before that I worked for a marketing agency where I discovered Node.js and used it anytime I could. I've been on the Node.js plan for 2-3 years now.

Aside from my work, I help organize Node.js meetups in South Florida. In the past I have organized a couple of informal NodeSchool-style events. I helped out in the first NodeSchool event in Puerto Rico as well (I'm originally from San Juan). I've also been making small contributions to NodeSchool and workshopper, as time has allowed.

I will be co-organizing these chapters with @onel0p3z and @dambalah, who have collaborated with me in other Node.js community things in South Florida. I'd like to get to a point where we can just have NodeSchool events pretty much automatically every month or two without too much of a hassle. Creating chapters for these two cities will help get that plan started!

**Comment by martinheidegger** [comment]
Hello @khalifenizar 

Following nodeschool/organizers#28 I invited you to the owners list
Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!
