### ISSUE TITLE
Nodeschool Chapter Registration

### ISSUE THREAD

**Issue by AlabamaMike** [nodeschool/organizers#152]
Hi, I would like to start a nodeschool chapter for Southern New Hampshire, USA. I am @alabamamike on twitter and work at Cyrus Innovation . I will be co-organizing this chapter with others to be named later. I have been using Node.js on-and-off for a few years and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hello @AlabamaMike 

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
