### ISSUE TITLE
Postpone Event

### ISSUE THREAD

**Issue by salahassi** [nodeschool/organizers#153]
Hello, 

First of all, I'm sorry about the this, but we had to change the date of NablusTM Node.js event last week due to the bad weather we had. We are going to make it next Saturday Feb, 28th. So please change it on the map.

Thanks.

**Comment by martinheidegger** [comment]
Cc @maxogden

**Comment by jasonrhodes** [comment]
Aren't the nodeschool.io events pulled from the Google doc that anyone can edit? cc @jilord

**Comment by jlord** [comment]
@jasonrhodes It _used_ to be like that, but then we moved it to the form -> spreadsheet method because some people were entering spammy data or deleting data from the spreadsheet.

Now a few people have access to the spreadsheet but we can add people whenever—I'm totally happy to add people freely.

**Comment by jlord** [comment]
And whoever else has access should feel free to add people, I'll add you and I can make this change. Anyone else here want to be added?

**Comment by gangstead** [comment]
Speaking of the spreadsheet, @jlord the events page is showing an empty map.  Did something happen to the spreadsheet?

**Comment by jlord** [comment]
> events page is showing an empty map

Ahhhh! I'll try and figure out what happened.

**Comment by jlord** [comment]
Also, forgot that actually after you fill out the Google Form for your event, if you save your url at the end, you can go back and update your info that way! :rocket:
