### ISSUE TITLE
Meetup NodeSchool #Paris

### ISSUE THREAD

**Issue by Mysteris87** [nodeschool/organizers#154]
Bonjour, 

Ma démarche peut paraître osée mais je recrute un développeur node pour ma startup. Votre événement a-t-il un volet "jobs" ou il est possible aux startupers de venir pour recruter ?

Bien cordialement,
Mysteris87

**Comment by martinheidegger** [comment]
Cc @tdd

**Comment by tdd** [comment]
Thanks @martinheidegger for bringing this to my attention.

@Mysteris87 we should take this off-thread. I'm the lead for NodeSchool Paris, can you ping me at christophe -AT- delicious-insights -DOT- com, please? We'll see what can be done, and what other channels you may be interested in.
