### ISSUE TITLE
Nodeschool Chapter Registration

### ISSUE THREAD

**Issue by tianlitao** [nodeschool/organizers#155]
Hi, I would like to start a nodeschool chapter for ShiJiaZhuang, CHINA. I am @tianlitao on twitter and work at Jimi  Technology . I will be co-organizing this chapter with others to be named later. I have been using Node.js for one year and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hello @tianlitao

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
