### ISSUE TITLE
Nodeschool Seattle Co-Owner

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/organizers#156]
Hey Guys & @sethvincent ,

I am a coorganizer for Seattle NodeSchool.
We just had an Awesome turnout today! I'll be making a post about how it went soon. I was wanting to invite the attendees to be members of Seattle nodeschool, but it doesn't look like I have the appropriate permissions, could some one add me as Owner?

Thanks!

**Comment by sethvincent** [comment]
added you, so you should now be able to add people to the seattle team.
