### ISSUE TITLE
Anyone knows how to get in touch with @stevekane?!

### ISSUE THREAD

**Issue by tdd** [nodeschool/organizers#158]
Hey guys,

I'm a bit concerned about @stevekane apparently falling off the face of… GitHub (hopefully not the Earth). He owns promise-it-wont-hurt, but…

* He hasn't **done anything on the workshop since March 2014**: all PRs are pending, he's completely non-responsive, including direct e-mails;
* His website is non-responsive, either;
* I can't seem to find a Twitter handle I could try and ping;
* Glimmer of hope: his last public commits are from Jan 15, just 6-7 weeks ago.

So he might be on sabbatical, a world trip, or something, I dunno. It bothers me, obviously, because I'd like to get the FR L10n merged in and bumped on npm, and could even offer to take over the workshop, on which he's apparently lost all interest for over a year.

I was just wondering if anyone knows how to get in touch with Steve?  I hope he's okay, I'm at a loss here. @rvagg? @caolan? @maxogden? Someone else?

Cheers,

**Comment by maxogden** [comment]
while your concern is definitely appreciated, it also contains quite a bit
of wild speculation. in my experience most of the time in situations like
this people are simply busy.

my suggestion would be to fork the module and publish the fork to npm. in
the event that @stevekane responds in the future you can merge your work
into his version at that point. it's not ideal but we don't have many
options.

probably in the future we should suggest that maintainers do 'npm owners
add nodeschool' to their modules, and we can create a nodeschool npm
account that is shared with a few organizers

On Tuesday, March 3, 2015, Christophe Porteneuve <notifications@github.com>
wrote:

> Hey guys,
>
> I'm a bit concerned about @stevekane <https://github.com/stevekane>
> apparently falling off the face of… GitHub (hopefully not the Earth). He
> owns promise-it-wont-hurt, but…
>
>    - He hasn't *done anything on the workshop since March 2014*: all PRs
>    are pending, he's completely non-responsive, including direct e-mails;
>    - His website is non-responsive, either;
>    - I can't seem to find a Twitter handle I could try and ping;
>    - Glimmer of hope: his last public commits are from Jan 15, just 6-7
>    weeks ago.
>
> So he might be on sabbatical, a world trip, or something, I dunno. It
> bothers me, obviously, because I'd like to get the FR L10n merged in and
> bumped on npm, and could even offer to take over the workshop, on which
> he's apparently lost all interest for over a year.
>
> I was just wondering if anyone knows how to get in touch with Steve? I
> hope he's okay, I'm at a loss here. @rvagg <https://github.com/rvagg>?
> @caolan <https://github.com/caolan>? @maxogden
> <https://github.com/maxogden>? Someone else?
>
> Cheers,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/organizers/issues/158>.
>


-- 
Sent from my phone

**Comment by tdd** [comment]
Hey Max,

Le 03/03/2015 19:59, Max Ogden a écrit :
> while your concern is definitely appreciated, it also contains quite a bit
> of wild speculation. in my experience most of the time in situations like
> this people are simply busy.

Definitely.  I sure hope that's all it is.

> my suggestion would be to fork the module and publish the fork to npm. in
> the event that @stevekane responds in the future you can merge your work
> into his version at that point. it's not ideal but we don't have many
> options.

I'll def have to do that.  There's not been a single commit or PR merge 
on this module for a solid year by now, and 10+ PRs are pending.  I've 
done that for stream-adventure too, but just because bringing it up to 
g11n'ability requires a lot more work, which I'll discuss with substack 
once I get there, 7-8 weeks down the line.

> probably in the future we should suggest that maintainers do 'npm owners
> add nodeschool' to their modules, and we can create a nodeschool npm
> account that is shared with a few organizers

Good point!  I'll be sure to think of that when I get around to writing 
this complete guide to workshop authoring I've got scheduled 
post-translations in https://gist.github.com/tdd/d7b2b719485cdf87bd5f

Thanks for your reply!

-- 
Christophe Porteneuve
tdd@tddsworld.com
