### ISSUE TITLE
Nodeschool Charleston

### ISSUE THREAD

**Issue by niix** [nodeschool/organizers#159]
Hi, I would like to start a chapter for Charleston, SC.  I am @nickolus on twitter.  I currently work for Citrix but am in the process of transitioning to another company.  I've been using Node for about 2 years now, both professionally and outside of work.  Thanks!

**Comment by finnp** [comment]
Great, I invited you to the organisation.

**Comment by niix** [comment]
@finnp Thanks!

**Comment by martinheidegger** [comment]
memo]: #28
