### ISSUE TITLE
Nodeschool Ibague

### ISSUE THREAD

**Issue by Gioyik** [nodeschool/organizers#160]
Hi, I would like to start a nodeschool chapter for Ibague, Colombia. I am @Gioyik on twitter. I work at ZydiaLabs and with developer teams at Mozilla . I have been using Node.js for one and a half years on large production software and developing small tools.

**Comment by martinheidegger** [comment]
Hello @Gioyik, sorry for the late response.

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
