### ISSUE TITLE
NodeSchool Lodz

### ISSUE THREAD

**Issue by adamniedzielski** [nodeschool/organizers#161]
Hi, I would like to start a nodeschool chapter for Lodz (Poland). I am [@niedzielskiadam](https://twitter.com/niedzielskiadam) on twitter and work for [goodylabs](http://goodylabs.com/) . I will be co-organizing this chapter with @lipkap I have been using Node.js for over a year and would like to help others developers to learn it, too.

**Comment by grabbou** [comment]
Hello @adamniedzielski 

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
