### ISSUE TITLE
Date errors in events

### ISSUE THREAD

**Issue by Trott** [nodeschool/organizers#162]
I didn't create the Mombasa or Delhi entries, but the dates in the spreadsheet/site are incorrect. (The error stems from the fact that some parts of the world treat 3/2/2015 as March 2, 2015, but other parts of the world treat it as February 3, 2015.) The Delhi event is March 12, 2015, but is showing up on the NodeSchool website upcoming events as December 3, 2015. (Again, it's the ol' 3/12/2015 vs. 12/3/2015. Some places put the month first, others put the month second.) A similar thing is happening with the Mombasa entry.

It might be good to switch to a format like 02-Mar-2015 so there's no ambiguity.

**Comment by martinheidegger** [comment]
@maxogden Do you know how we can change the event excel file? (have never seen it..)

**Comment by jlord** [comment]
I looked at the settings and I don't think I can do much else to that part of the form. The form does say "mm/dd/yyyy" so hopefully most people will enter it as such.

I did edit the text that appears once the form has been submitted, however, to included "check back to make sure it is correct." Maybe that will help some. It now says:

> Thanks! You'll see your event listed on the site soon, check back and make sure it is correct. 

> ☞ Save the unique URL below ('Edit your response') in case you need to make an edit to your event's listing.

:balloon:

**Comment by martinheidegger** [comment]
I fixed the Delhi and mombasa dates.
