### ISSUE TITLE
Nodeschool Chapter for Khulna

### ISSUE THREAD

**Issue by masnun** [nodeschool/organizers#163]
Hi I would like to start a nodeschool chapter in Khulna. Khulna is a beautiful city in Bangladesh. I am <a href="https://twitter.com/masnun">@masnun</a> on Twitter and @masnun on Github. I work for Polar Design and co-manage Google Business Group Khulna. I would like to accept more organizers in the team once we start. I have been using Node.js for the last eight months or so. I would like this nodeschool chapter to be a Node.js learning platform for the local developers.

**Comment by finnp** [comment]
Wicked! I invited you to the organisation, you can now perceed with the steps here: https://github.com/nodeschool/organizers#1 :bee:

**Comment by masnun** [comment]
Thanks! :+1:
