### ISSUE TITLE
Remote video sessions during chapters

### ISSUE THREAD

**Issue by grabbou** [nodeschool/organizers#164]
Hey guys,

As NodeSchool chapters are often attended by people that either haven't contributed that much to the opensource before or are just taking their first steps in the js-everywhere world, I think it'd be quite cool to set up quick remote sessions / lectures / interviews with some of you just to give people tips, motivation and ability to meet core developers of many popular frameworks or even core node.js. In most cases, it's very unlikely we'll have an opportunity to meet each other in person, so I think this might be valuable experience for all of us!

We can also share some thoughts on how we are working in different countries, what processes are used during the development stage, how do we use Node.js or what's the most exciting moment in House of Cards we like.

What you think?

**Comment by maxogden** [comment]
I think this is a really cool idea! I think there is lots of potential for video content + nodeschool in general.

I went ahead a created a Youtube Channel for nodeschool: https://www.youtube.com/channel/UCzUA8Ch_NqTDzdgynhnLJFg

Anyone who wants to upload videos has to give me their Google email and I can add them as a manger.

I'll write up some instructions and add them to the readme in this repo soon

**Comment by grabbou** [comment]
I think there's been a talk about that in @nodeschool/international-day. Still my company, @explosivetitles is happy to do video editing of what we gonna do. Not sure where's the actual discussion about that happening, can somebody give me a link? #noob.

**Comment by iancrowther** [comment]
@grabbou can you define any user scripts? or bullet points?  this would help chapter orgs kick this off
