### ISSUE TITLE
Nodeschool Reno

### ISSUE THREAD

**Issue by colinloretz** [nodeschool/organizers#167]
Hi there, I would like to start a nodeschool chapter for Reno, Nevada. I am @colinloretz on twitter and work at @renocollective and a startup that uses Node.js. I will be co-organizing this chapter with Gabriel Hopper and CJ Avilla (@wizemanip). I have been using Node.js for 3 years and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hello @colinloretz

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
