### ISSUE TITLE
Chapter for Live online classes

### ISSUE THREAD

**Issue by nodejsguru** [nodeschool/organizers#169]
Hi, I want to start a new chapter in the name of nodeJSguru that would operate online only. I believe there are many out there who would not like to travel for the classes/events and prefer something that is online. I have been using node for an year but have more than 15 yrs experience in programming (most recently rails). I hope to add new materials to the ones already on NodeSchool.

**Comment by martinheidegger** [comment]
The term "chapter" refers to place where people can meet (online only is not really a place). So I think we should not call your awesome proposal a "chapter". Aside from that: You are proposing a regular online school class with attendance fees. Which is not a bad thing but somehow I think there are more than just this out in the world. If you would be presented as a place to learn node online I would like to see a bigger list of other organisations doing the same.

**Comment by nodejsguru** [comment]
>If you would be presented as a place to learn node online I would like to see a bigger list of other organisations doing the same.

Hi Martin, not sure if I understand this. Will you please clarify. Thanks.

**Comment by martinheidegger** [comment]
I am sure there is more than one place where you can learn node.js online. If there is, i would love to see it (and add your effort to it)

**Comment by nodejsguru** [comment]
Yes, there are places like codeschool that have online courses. However, it basically has recorded videos with exercises. What we are trying out here is a real classroom that is Live with students being able to interact with the instructor/mentor during the class.

So do you suggest we can't have a chapter? In that case how do we organize an event, because having a chapter is a prerequisite for that.

**Comment by martinheidegger** [comment]
In my understanding (there are surely other people with other opinions on this) a chapter has to have a location, so I don't think you should open a chapter repository here or call this a "chapter".

You can register an event even without creating a chapter (i am not sure its intended for that, but it surely works).

**Comment by nodejsguru** [comment]
Thanks Martin. I could create an event. I'm closing this issue now.
