### ISSUE TITLE
Owner request :D

### ISSUE THREAD

**Issue by davsket** [nodeschool/organizers#170]
Hi, I would like to start a nodeschool chapter for [BogotáJS](http://bogotajs.com) - Bogotá / Colombia. I am @davsket on twitter and work at [Monoku](http://monoku.com). I will be co-organizing this chapter with Giovanny Beltrán (@agar3s), David Roncancio (@kuryaki) and Jorge Zaccaro (@jorgezaccaro) . I have been using Node.js for more than 2 years and would like to help others learn as well.

**Comment by finnp** [comment]
Hey :)

That's awesome!

I just invited you to the NodeSchool organisation. You can now continue with these steps: https://github.com/nodeschool/organizers#1

Best,
Finn

**Comment by davsket** [comment]
Thank you!! :D
