### ISSUE TITLE
start a new NodeSchool chapter

### ISSUE THREAD

**Issue by pascalfares** [nodeschool/organizers#173]
Hi, I would like to start a nodeschool chapter for Beirut / Lebanon. I am @pascalfares on twitter and work at [Cnam Liban](http://depinfo.isae.edu.lb) a continuous training university associated to [Cnam Paris](http://www.cnam.fr) . I will organizing this chapter at first to our computer science students (~1000) then extend it to the [Opem Source Lebanese Movement](http://oslm.cofares.net). I am now preparing courses for beginners.

**Comment by martinheidegger** [comment]
Hello @pascalfares , sorry for the late response.

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
