### ISSUE TITLE
Spam entry submission

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/organizers#176]
Perhaps with the rise of spam entries we should build out a spam submission form that simply logs the submission some place useful for the admins of the list.

Alternatively, perhaps on submission we check an entry by auto verifying a file, like the code of conduct or something?

Anyone can host a nodeschool, but at minimum what must a nodeschool have and can we verify that and make spamming more difficult w/o sacrificing too much?

**Comment by martinheidegger** [comment]
Since the events are google spreadsheets I just added myself to get notifications. This way I will see easily if a new (spammy) entry is being made...

**Comment by blakmatrix** [comment]
I suppose that'll work; Definitely would be good to keep it in mind for when and if nodeschool blows up and automation of sorts is needed

**Comment by martinheidegger** [comment]
Closing this issue for now, checking the data should be enough.
