### ISSUE TITLE
Add as Owner - Gainesville, FL

### ISSUE THREAD

**Issue by aaronbdixon** [nodeschool/organizers#177]
I would like to start a nodeschool chapter for Gainesville, FL. I am @aaronbdixon and @gnvjs on twitter and work at 352 Inc. We use Node heavily for new projects. I will be co-organizing this chapter with Blake McLeod and Dennis Pelton. I have been using Node.js for about a year and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hello @aaronbdixon  , sorry for the late response.

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
