### ISSUE TITLE
Add as owner for Lagos, Nigeria

### ISSUE THREAD

**Issue by dipolediamond** [nodeschool/organizers#178]
Hi, I would like to start a nodeschool chapter for Lagos, Nigeria. I am @dipomajekodunmi on twitter and work at dipoleDIAMOND . I will be co-organizing this chapter with a friend Mayowa. I have been working with .NET technologies but recently discovered Nodejs and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hello @dipolediamond !

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
