### ISSUE TITLE
Add as an Owner - Helsinki, Finland

### ISSUE THREAD

**Issue by laurisvan** [nodeschool/organizers#179]
Hi, as one of the organisers of our HelNode community, I would like to start nodeschool chapter for Helsinki. Please find our meetup group at http://www.meetup.com/Helsinki-Node-js/ and @Helnode from Twitter. As to myself, I am @laurisvan on Twitter and work in SC5 Online (www.sc5.io).

I will be co-organising this chapter together with HelNode folks - our community has been running for some 9 months now and currently has almost 300 followers. Our community has both experienced Node.js hackers and newbies. Organising nodeschool has been in talks since founding, and it is about the time to do it now.

**Comment by martinheidegger** [comment]
Hello @laurisvan !

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
