### ISSUE TITLE
request to start a new NodeSchool chapter in isfahan

### ISSUE THREAD

**Issue by arianeai** [nodeschool/organizers#181]
Hi, I would like to start a nodeschool chapter for Isfahan/Iran. I am a graduate student in data commnunication networks at Isfahan University of Technology . I will be co-organizing this chapter with my classmates as IUTelecom Student group. I have been using Node.js for 8 months and would like to help others learn as well.
your sincerely,
Arian Sotoudeh Mehr
Isfahan University of Technology

**Comment by martinheidegger** [comment]
Hello @arianeai !

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I followed nodeschool/organizers#28
