### ISSUE TITLE
Sticker Exchange

### ISSUE THREAD

**Issue by gangstead** [nodeschool/organizers#182]
My fellow organizers of the Dallas chapter have some extra stickers and we'd like to do a swap with another chapter.  Anybody want to mail us some stickers and we'll mail you some back?  Here's our design:

![image](https://cloud.githubusercontent.com/assets/527760/6826438/7b2dbf82-d2cf-11e4-9187-7b9df877811b.png)

Action shot: https://twitter.com/qw3rtman/status/560622691623788545

**Comment by martinheidegger** [comment]
I am in. Address?

**Comment by gangstead** [comment]
Sent an email to the gmail address on your profile.

**Comment by martinheidegger** [comment]
:+1:

**Comment by gangstead** [comment]
Dallas and Osaka have completed a swap.  It's not too late to do some exchanging! ![img_20150414_095815](https://cloud.githubusercontent.com/assets/527760/7141463/68d28c32-e297-11e4-8968-25453a12eca1.jpg)

**Comment by finnp** [comment]
Awesome! We currently don't have enough stickers for Berlin. But with the next badge, I am going to post here again.

**Comment by gangstead** [comment]
There's no set amount you have to put up to swap. Dallas - Osaka only swapped a dozen.  At Dallas we only give out stickers after you complete a module which keeps them from running out too quickly.

**Comment by yosuke-furukawa** [comment]
If you would like to share your sticker, feel free to use [hexi.pics](https://hexi.pics/) !
We can ship your stickers internationally. 

NodeSchool Tokyo has their own sticker in hexi.pics. 

https://hexi.pics/items/6fd822b4b2500d5e833c24a01958a249

![image](https://hexi.pics/resize/w/462/h/462/0f48f67359995f579a3a03da77320fe5.png)

note: We have not translated all pages to English, but we have an English help page. https://hexi.pics/help_en

If you have some trouble, please create an issue here. https://github.com/paeria/Hexi-sayhello

**Comment by samiconductor** [comment]
The Osaka stickers were a great success at last night's nodeschool. Most folks opted for the limited edition Osaka stickers on completing expressworks. Thanks @martinheidegger!

**Comment by martinheidegger** [comment]
Collaboration ftw!

**Comment by grabbou** [comment]
We are going to have some NodeSchool Wrocław (Poland) stickers being ready next week. Anyone wants to exchange?

**Comment by martinheidegger** [comment]
How about sharing it on hexi.pics?

**Comment by grabbou** [comment]
Yeah, that can do. Will get back to you soon.

**Comment by samiconductor** [comment]
We updated our stickers!

Unfortunately, we won't be getting IRL versions until May 20th (just before international day). But if you want to exchange via snail mail anytime after that, let's swap addresses. We ordered 50 so we'll have some extra.

[dropbox link to svg](https://www.dropbox.com/s/wq87wbskxv3g5sa/nodeschool-dallas-skyline-v8.svg?dl=0)

![nodeschool-dallas-skyline](https://cloud.githubusercontent.com/assets/603812/7559071/be731416-f775-11e4-97fe-e9119a30cf5a.png)

**Comment by samiconductor** [comment]
Dallas stickers are in early. Might be able to swap in time for International Day. Send @gangstead or me your mailing address and we'll do an exchange.

![2015-05-15 11 35 20](https://cloud.githubusercontent.com/assets/603812/7657592/c524ff28-faf8-11e4-9cb7-7560dac6f74f.jpg)

![2015-05-15 11 43 02](https://cloud.githubusercontent.com/assets/603812/7657597/cec643ca-faf8-11e4-89fc-4e51b3d22b7c.jpg)

**Comment by martinheidegger** [comment]
Since there has been lack of interest recently I close this as a part of clutter. Please reopen a new issue if you are interesting in holding another sticker swap!
