### ISSUE TITLE
5/14/2015 Iran Node link has no information about event

### ISSUE THREAD

**Issue by Trott** [nodeschool/organizers#185]
They have a date, so presumably there could be some info, but it's just this: 

![screen shot 2015-03-30 at 10 02 43 pm](https://cloud.githubusercontent.com/assets/718899/6912601/878d7abc-d728-11e4-8fcf-8801fb7b3df6.png)

The link is http://nodeschool.io/iran/

**Comment by martinheidegger** [comment]
@hrayatnia Care to comment?

**Comment by hrayatnia** [comment]
![Uploading Screen Shot 2015-04-04 at 8.00.46 PM.png . . .]()

**Comment by hrayatnia** [comment]
![screen shot 2015-04-04 at 8 00 46 pm](https://cloud.githubusercontent.com/assets/5239218/6993309/7ba1ad0a-db05-11e4-84db-149c24db42d5.png)
![screen shot 2015-04-04 at 8 00 33 pm](https://cloud.githubusercontent.com/assets/5239218/6993311/87be84b4-db05-11e4-93ac-0d133178698f.png)

--------

@martinheidegger  @Trott sorry for my late response
check it!!!  http://nodeschool.io/iran/

**Comment by martinheidegger** [comment]
:+1:
