### ISSUE TITLE
Tessel 2 for NodeSchool

### ISSUE THREAD

**Issue by finnp** [nodeschool/organizers#187]
Hey everyone,

I noticed that you can order the new Tessel 2 right now, but only until April 4th. It's going to be shipped in August.

I think it's a cool device for teaching node and I got a someone to order 10 of them for NodeSchool Berlin and other user groups.

Maybe you can order some for your chapter as well and we can have a NodeBots summer! 

Best,
Finn

**Comment by maxogden** [comment]
good idea! I preordered 2. cant wait to hack on em. cc @Frijol

**Comment by martinheidegger** [comment]
Preordered one, thank you for the info.

**Comment by finnp** [comment]
It's still possible to pre-order tessels. :rocket:
