### ISSUE TITLE
New nodeschool chapter for Vienna, Austria

### ISSUE THREAD

**Issue by thomaspeklak** [nodeschool/organizers#188]
Hi, I would like to start a nodeschool chapter for Vienna, Austria. I am @thomaspeklak on twitter. I will be co-organizing this chapter with [Christoph Walcher](https://github.com/saintedlama) @saintedlama and [Michael Schärfer](https://github.com/shm) @notyce. We are the nodejs vienna meetup organizers and would like to organize a nodeschool event within the [Linuxwochen](http://linuxwochen.at/). I have been using Node.js for about four years and would like to help others learn as well.

**Comment by finnp** [comment]
This is awesome :) Cool to see NodeSchool come to Austria. You can now perceed, by following this steps: https://github.com/nodeschool/organizers#1

**Comment by alicetragedy** [comment]
:tada:

**Comment by simoneb** [comment]
@thomaspeklak I submitted a request for a Vienna chapter the day before you, I'd be glad to join you

**Comment by thomaspeklak** [comment]
@simoneb Interesting coincidence. When did you plan to make one?

If you want to join us, maybe we can meet in person at our next meetup and talk about details http://www.meetup.com/nodejs-vienna/events/219689039/

**Comment by simoneb** [comment]
It would be cool to have it on the international day: http://nodeschool.io/international-day/

I am not currently based in Vienna but I lived there for some time a few years ago and noticing there wasn't a local chapter I thought I would set one up. It's not going to be easy to meet in person as I'm not in Austria, but I'd love to attend to the first chapter meeting and glad to help out in organizing it from here. I also know some people in the area who might be willing to help out/attend.

**Comment by thomaspeklak** [comment]
As mentioned in my description we have the opportunity to hold it as part of the Linuxwochen which will probably be on May 8th. Doing it once again in such a short period does not make too much sense in my opinion. More tutors that will broaden our spectrum are very welcome.

**Comment by simoneb** [comment]
Totally agree, being in the area you are certainly more suitable to make
the call for a date, so I'm totally fine with whatever date you come up
with. I don't know if I can attend to this first meeting, the first step is
certainly to open an issue on the repo so to start discussing it. Can you
add me to the repo perhaps?
