### ISSUE TITLE
Ownership for node school/San Jose

### ISSUE THREAD

**Issue by spivotron** [nodeschool/organizers#189]
Hello,
My names Henry Spivey and I am a student at San Jose State University studying computer science.   I have been learning  JavaScript and angular JS for the past few months now. Fellow computer science  students here would greatly benefit from a nodeschool chapter right here on campus.  Please see my github at github.com/spivotron.

Thanks!

Henry Spivey

**Comment by martinheidegger** [comment]
I added you to the owners list a while back but I completely forgot to answer this thread, sorry for that!

please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!

PS.: I followed nodeschool/organizers#28
