### ISSUE TITLE
VM for Windows users?

### ISSUE THREAD

**Issue by gangstead** [nodeschool/organizers#191]
At our events the biggest source of problems are running node in Windows environments.  Sometimes it's quirks with Node / NPM itself.  Sometimes it's problems with the modules (we've had to fix spaces in paths handling for Windows users on multiple modules).  It's tough for us organizers since we only have Linux/Macs.

We're floating the idea of making a Linux VM with Node preinstalled to hand out to all Windows users.  Has anyone done this or come up with a better solution to supporting Windows users?

**Comment by martinheidegger** [comment]
@gangstead Aside from the fact that there are several ways to launch workshoppers in virtual, remote machines: I don't think its a good idea to ignore the windows problems. Of course they are horribly annoying but unfortunately that is the reality right now when working with node.js on windows. Telling windows "learners" that "using windows is a bad idea" is not a good reputation stamp for node.js in my opinion. It would be better if we were to fix the existing problems and work on better [installation instructions](https://github.com/nodeschool/discussions/wiki/Installation-suggestions). With a good FAQ about windows. Community process for the win?

**Comment by gangstead** [comment]
I agree, but Node not working is also a poor beginners' experience and a botched Windows Node install is very hard to troubleshoot.  We're looking for the fastest time to writing code.

What virtual/remote Nodeschool options are there?  My google-fu has failed me and I can't find anything.

**Comment by julianduque** [comment]
@gangstead we use Codio (http://codio.com) an online IDE with Node support for people using Windows or new to programming (due to lack of dev environment), results are great, no need to deal with virtual machines or anything.

**Comment by kwandrews7** [comment]
https://c9.io/ looks to be another option for virtual node dev. I was able to load and run the expressworks node module.

**Comment by edsadr** [comment]
Hello ... we got some problems with C9 ... console stops working some times and when used from the same location some weird VM memory warnings ... so far Codio is doing fine

**Comment by gangstead** [comment]
Thanks @julianduque, codio looks promising.  I was working on a module in about a minute.  We're going to try this at our next meetup.

**Comment by martinheidegger** [comment]
Did you know that in combination with Windows Azure its possible to launch a Visual studio online editor that does work "just like that". Aside from a slight bug (the menu doesn't work) it is possible to complete learnyounode.
