### ISSUE TITLE
New nodeschool chapter for Thessaloniki, Greece

### ISSUE THREAD

**Issue by kmargaritis** [nodeschool/organizers#193]
Hi, I would like to start a nodeschool chapter for Thessaloniki, Greece. I am [_margaritis](https://twitter.com/_margaritis) on Twitter and i am Software Engineer at [Goodvidio](http://goodvid.io). I will be co-organizing this chapter with my fellow organizers from Thessaloníkis' Node.js Meetup and my co-workers, Thanasis Polychronakis (@thanpolas), Konstantinos Bariotis (@kbariotis) and Adonis Kakoulidis (@varemenos). 

We have been running [Thessaloníki's Node.js Meetup](http://www.meetup.com/Thessaloniki-Node-js-Meetup/) for almost a year now and our community is growing at a steady pace. Our community consists of both newbies and some crazy geeky hackers :stuck_out_tongue: 

I have been using Node.js for about 2,5 years and would like to help other fellow Noders as well.

**Comment by finnp** [comment]
Awesome! I just invited you. You can now perceed with the steps over here: https://github.com/nodeschool/organizers#1. Also you can invite you co-workers in the organisation. :green_apple:

**Comment by kmargaritis** [comment]
Thanks @finnp! :+1:
