### ISSUE TITLE
CLI for helping people at nodeschool/discussions

### ISSUE THREAD

**Issue by finnp** [nodeschool/organizers#194]
Hey,

I created a small CLI for helping out people on nodeschoo/discussions more easily: https://github.com/finnp/help-out

Basically you type in `help-out` in your terminal and it tells you what to do. It is inspired by the workflow @martinheidegger set up for the repo, where we tag issues in a useful manner.

It's just a first version, this could be a lot cooler. But I think it's helpful for people who want to help out, but don't know where to start.

Best,
Finn

**Comment by martinheidegger** [comment]
Nice!

**Comment by martinheidegger** [comment]
Hello @finnp I just thought we could use a little more features here than just discussions. I think right now no. 1 reason why chapter owners are not participating in the nodeschool is the repo issue: Every new chapter gets a repo and ever owner is automatically added to them. Which leads to owners being unable to filter through the vast amount of notifications. (I am having a hard time doing it and I am trying hard to stay up-to-date). It would be good if a `nodeschool` command line tool and/or a nodeschool server could be used to automatically deregister from new chapters but stay registered on important issues.

**Comment by finnp** [comment]
@martinheidegger Sounds great. Maybe let's start with name-grabbing and creating a http://github.comnodeschool/cli repo?

**Comment by martinheidegger** [comment]
@finnp I am busy with international-day right now (50 peeps in osaka wew) but can help out later.

**Comment by finnp** [comment]
@martinheidegger Done. I also don't have more time for it right now though. https://github.com/nodeschool/cli

**Comment by martinheidegger** [comment]
We have a cli repo so I close this issue :+1:
