### ISSUE TITLE
Add as Owner - Hanoi, Vietnam

### ISSUE THREAD

**Issue by hainh** [nodeschool/organizers#195]
Hi, I would like to start a nodeschool chapter for Hanoi, Vietnam. I am [nghonghai](https://twitter.com/nghonghai) on twitter and work at home. I will be co-organizing this chapter with @dominhhai and some promising mentors from our Hanoi Javascript Application [meetup](http://www.meetup.com/Ha-Noi-JavaScript-Application-Meetup/). I have been using Node.js for 1 month and would like to help others learn as well.

**Comment by finnp** [comment]
Hey @hainh , I just invited you to the organisation. You can now perceed with the steps over here: https://github.com/nodeschool/organizers#1

Best,
Finn :v:

**Comment by hainh** [comment]
Thank you @finnp :+1:
