### ISSUE TITLE
Chapter in Santiago/Chile:)

### ISSUE THREAD

**Issue by forres** [nodeschool/organizers#196]
Hey guys! 
I'd love to start a NodeSchool chapter in Santiago Chile, 
In twitter I'm @ffores, but we are currently hosting courses and workshops through www.Noders.cl (@noderscl on twitter), NodeJS and JS learning community in Santiago. 
We are currently running 2 courses (for free btw) 
Introduction to NodeJS, and Backend a APIs with Looback (31 and 16 people enrolled on course)

And as no man can do it alone through life, the are people other than me working on this proyect:
@maetschl 
@josev55
Gustavo hidalgo (sorry, no twitter account)

I'm working on noisegrasp.com a NodeJS based startup that does marketing analisis, and been i love with nodeJS and JS for a couple of years now.
And we are planning on keep ok teaching and creating courses to strengthen the NodeJS and JS community in Santiago Chile.

**Comment by finnp** [comment]
Awesome, I invited you as an organizer. Please follow these steps next: https://github.com/nodeschool/organizers#1
