### ISSUE TITLE
Query to initiate a nodeschool chapter [ Casablanca / Morocco ]

### ISSUE THREAD

**Issue by altreze** [nodeschool/organizers#197]
Hi, I would like to start a nodeschool chapter for [Casablanca / Morocco]. I am Mouad on [ freelance at mohandis dot ma] and work at Altreze as software engineer. I will be co-organizing this chapter with Altreze. I have been using Node.js for 2 years and would like to help others learn as well.

Catch up soon.

:-)

**Comment by martinheidegger** [comment]
Hello @altreze  !

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: I just followed nodeschool/organizers#28 ; you can do that too!
