### ISSUE TITLE
NPM NodeSchool user - I did something on a whimp

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#198]
NPM supports user namespaces since recently so I went ahead and created a [npm user](https://www.npmjs.com/~nodeschool) This way someone can use this user to publish something. Now I still have to figure out how many people can use the same user ... have you got an idea?

**Comment by martinheidegger** [comment]
It looks like groups are something that will be coming in future npm releases. Will drop the user then if it blocks any community effort.

**Comment by bcomnes** [comment]
Your doing good work @martinheidegger!
