### ISSUE TITLE
Change date of Chiang Mai event

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/organizers#199]
Currently, it is set as May 2nd. It should be May 1st, from 3-6pm at Punspace (Tha Phae Gate). Not sure how to change it myself.

**Comment by dominhhai** [comment]
When you submitted the event to nodeschoo.io, you got a edit link.
By using it to edit your event and resubmit again, your event will be updated.
Do you remember it?

**Comment by RichardLitt** [comment]
Hmm. I don't! Was that link saved anywhere?

**Comment by dominhhai** [comment]
It's really hard to remember it because of the long key generated by google form. So, it's good to save this link in browser or other places as github's issues comment. :+1: 
I think the first event is OK, your student can see the schedule on event-meetup.

**Comment by RichardLitt** [comment]
Hmm. I guess I don't remember that process. Sorry about this. 

The event does need to be edited, though - the date is wrong.

**Comment by martinheidegger** [comment]
Should be fixed!

**Comment by RichardLitt** [comment]
Thanks!
