### ISSUE TITLE
New Chapter in Poznań / Poland

### ISSUE THREAD

**Issue by born4code** [nodeschool/organizers#200]
Hi, I would like to start a nodeschool in Poznań / Poland. I am CEO&CO-Founder at Born4Code. I will be co-organizing this chapter with whole our company. We have been using Node.js for 3 months and would like to help others learn as well. I think we are able to make something awesome to make node.js stronger! My e-mail: wojtek@born4code.pl

**Comment by martinheidegger** [comment]
Hello @born4code!

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: All I did was following: nodeschool/organizers#28 Now you can do that too!

**Comment by born4code** [comment]
Thanks :)
