### ISSUE TITLE
NodeSchool chapter for Washington, DC

### ISSUE THREAD

**Issue by owmf** [nodeschool/organizers#201]
Hi, I would like to start a nodeschool chapter for Washington, DC. I am @matthew_fincher on twitter and work at OpenWhere as a principal cloud architect. I will be co-organizing this chapter with Andy Heifetz. I have been using Node.js for 18 months and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hello @owmf!

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: All I did was following: nodeschool/organizers#28 Now you can do that too!
