### ISSUE TITLE
Node school for Caracas Venezuela

### ISSUE THREAD

**Issue by danielrvt** [nodeschool/organizers#202]
Hi guys,

I would like to start a nodeschool chapter for Caracas Venezuela. I am @danielrvt on twitter and I'm also CEO at Soluciones Drag & Drop. I will be co-organizing this chapter with my partner Daniela Velasquez. I have been using Node.js for over a year now and would like to help others and build a community around this technology in my country.

**Comment by martinheidegger** [comment]
Hello @danielrvt!

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: All I did was following: nodeschool/organizers#28 Now you can do that too!
