### ISSUE TITLE
Nodeschool chapter for Cochabamba Bolivia

### ISSUE THREAD

**Issue by chitopolo** [nodeschool/organizers#203]
Hi, I would like to start a nodeschool chapter for Cochabamba. I am @chitopolo on github and twitter and I work as the CTO of UCATEC University. I have been teaching Javascript and Node.js on my city. I have been programming in node for already 8 months and I would like to help others learn even better by using this amazing curriculum.  

Thank you very much. Rene Polo.

**Comment by martinheidegger** [comment]
Hello @chitopolo!

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: All I did was following: nodeschool/organizers#28 Now you can do that too!

**Comment by eafelix** [comment]
great news!
