### ISSUE TITLE
Nodeschool in Seville

### ISSUE THREAD

**Issue by beltran-rubo** [nodeschool/organizers#204]
Hi,

I'm Beltran and I am a software developer. I would like to start a NodeSchool chapter for Seville (Spain). I am @beltranrubo on twitter and work at Bitnami https://bitnami.com . I will be organizing this chapter with other Node.js and Javascript users in the city and other team mates. 

I usually participate in other meetups in Seville (MongoDB, OpenStack, WordPress, Joomla!) and we already hosted around 5 events in our office this year. I also have been participate in other events as speaker like WordCamp or DrupalCamp in the past.  I have been using Node.js for 4 months and it hsa been great to learn with NodeSchool tutorials. I would like to help others learn as well.

These are some pictures of our space for events. Thanks!

![img_4959 1](https://cloud.githubusercontent.com/assets/3718440/7374486/f465ef14-edd2-11e4-9137-3a4c744fd33d.JPG)
![img_4894 1](https://cloud.githubusercontent.com/assets/3718440/7374496/f8718258-edd2-11e4-8bdf-5cccfd651878.JPG)

**Comment by martinheidegger** [comment]
Hello @beltran-rubo!

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

Also I saw that you created an event on the nodeschool page that sends people to this issue, did you keep the link to change the url to some event-registration site?

PS.: All I did was following: nodeschool/organizers#28 Now you can do that too!

**Comment by beltran-rubo** [comment]
Thanks! I will create the chapter for Seville with more details and I will register the event to point that page, sorry for the confusion.
