### ISSUE TITLE
NodeSchool Chapter for Raleigh/Durham, NC

### ISSUE THREAD

**Issue by brianpmarks** [nodeschool/organizers#205]
Hi, I would like to start a nodeschool chapter for the Raleigh/Durham, NC area (also known as RDU and the Triangle). I am @brianpmarks on twitter and co-founder/CTO of trinket.io. I am also the organizer of the Triangle Node.js meetup group. I've been using Node.js for over 2 years now.

I will be co-organizing this chapter with Jean-Marcel Belmont, a Front-End JavaScript Engineer working at a Startup in the Cary, NC area. He is also a Node.js enthusiast as well as a Functional Programming Enthusiast.

**Comment by finnp** [comment]
Hey I just added  you to the team. Go ahead and follow these steps next: https://github.com/nodeschool/organizers/
