### ISSUE TITLE
NodeSchool in Fresno, CA

### ISSUE THREAD

**Issue by stonemirror** [nodeschool/organizers#206]
Hi, I'm the executive director of Liberating Software, a software literacy nonprofit in Fresno, CA, and I'd like to offer NodeSchool events. I've been playing around with NodeJS for six or eight months on and off, on Linux, OS X, and most recently on Raspberry Pi's. Our web site is at http://lliberating-software.org.

**Comment by finnp** [comment]
Great, just added you to the team. Go ahead and follow the steps here: https://github.com/nodeschool/organizers :)
