### ISSUE TITLE
Nodeschool in Monterrey, México.

### ISSUE THREAD

**Issue by diegowifi** [nodeschool/organizers#207]
Hi, I would like to start a nodeschool chapter for Monterrey, México. I am @Diego_WiFi on twitter and work at Jumpstart MTY, a tech community. I will be co-organizing this chapter with Alejandro Cavazos and others. I have been using Node.js for about 2 months and would like to help others learn as well.

**Comment by finnp** [comment]
Awesome, I just added you to the team. Make sure to follow the steps mentioned here: https://github.com/nodeschool/organizers
