### ISSUE TITLE
nodeschool chapter for Belgrade, Serbia

### ISSUE THREAD

**Issue by stojanovic** [nodeschool/organizers#208]
Hi, I would like to start a nodeschool chapter for Belgrade, Serbia.
I am [@slobodan_](https://twitter.com/slobodan_) on twitter and work as CTO at [Cloud Horizon](http://cloudhorizon.com/). I will be co-organizing this chapter with [JS Belgrade](https://twitter.com/jsbelgrade) co-organizers ([Bogdan Gavrilović](https://twitter.com/ispijac_kafe), [Aleksandar Simović](https://twitter.com/simalexan) and others).
I have been using Node.js for a few years and would like to help others learn as well.

**Comment by finnp** [comment]
Cool, I just added you to the organisation, follow these steps next: https://github.com/nodeschool/organizers#1

**Comment by stojanovic** [comment]
Thanks
