### ISSUE TITLE
Structuring Post-school Write Ups

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/organizers#209]
I've just organized two NodeSchools - one with @LaughingSun in [Bali](http://nodeschool.io/bali/) and one in [Chiang Mai](http://nodeschool.io/chiang-mai/). Both times, I have felt a bit confused about what I should do afterwards. I want to write about the process of organizing NodeSchools in places you're just passing through, but I don't know where to do this best.

I could write a write up on my own blog; I could write a write up in the GitHub issues, particular in https://github.com/nodeschool/discussions/issues/93. However, I feel like https://github.com/nodeschool/discussions/issues/93 is bloated and is more about giving advice to future organizers than to help bootstrap and energize the community by talking about how the nodeschool went. I think there should be a definitive place to write up events, or there should be a more definitive structure around how to write them up wherever, and how to link to those write ups after the event on nodeschool.io or in the local chapter repositories. 

I propose that we add in either:
 * a blog functionality - maybe with a markdown file that can be rendered on nodeschool.io - or,
 * a way of linking, after the event, to a writeup in an issue in the GitHub repository for that chapter, or
 * a way of linking to an external blog, and example blogs encouraging organizers to write similar ones.

As a side note: Luckily, both chapters are now going ahead with plans (independently of me) to host another session soon. This is great; it means that the local community has a bit of steam left to run on, and will probably grow and continue. Hopefully, we can get Balinese and Thai translations, too.

**Comment by mikeal** [comment]
Maybe we should do a new repo for writeups?

**Comment by RichardLitt** [comment]
That might work. Each write up could be an open issue, and those could be linked from the readme's from each respective chapter repository.

**Comment by maxogden** [comment]
+1 to that idea. Also I did a buncha work today with @trosetty on the Organizers repo Wiki in case there needs to be a place to put 'best practice' kind of info into one place: https://github.com/nodeschool/organizers/wiki

**Comment by RichardLitt** [comment]
Alright. Created https://github.com/nodeschool/write-ups. There's a few things we should do now: 
 * Figure out best syntax for the name of the issues.
 * Figure out if we want to do issues or have people PR a Markdown file. I'm for Issues, because it enables discussions and allows multiple people to add their writeups for each event. 
 * Make an example // first write up.
 * Link this page on nodeschool.io, in the organizers wiki, and wherever else it should be.
 * Move past writeups into this repository. 

Sound good? Shall I open these as issues in the write-ups repository?

**Comment by maxogden** [comment]
I linked to it from here:
https://github.com/nodeschool/organizers/wiki/Event-Success-Stories

I think we should use it as a discussions repo rather than as a repo of
markdown files

On Sun, May 17, 2015 at 10:52 PM, Richard Littauer <notifications@github.com

**Comment by RichardLitt** [comment]
Alright, cool. I'll write up two examples from my experiences as issues, then.

**Comment by martinheidegger** [comment]
This issue seems to be done. Closing it.
