### ISSUE TITLE
Chapter creation for Pereira, Colombia

### ISSUE THREAD

**Issue by cronopio** [nodeschool/organizers#210]
Hi, 

Around one year ago, @pin3da, @jhonber and me started http://pereirajs.org the local community for our city. Now is time to get into the NodeSchool workshops and we are ready to join to you in the international day.
Pereira is a small city in colombia know as the center of the triangle of the "Eje Cafetero" (coffee production area).

I'm [@cronopio2](https://twitter.com/cronopio2) on twitter and recently started to work with NodeSource. I been using Node.js since `v0.2.2` and I worked previously for Nodejitsu.

We have confirmed venue and have several sponsors for our events (on our webpage are listed), we hope we can get ownership soon and create the repo and all the pages to launch the event to our local audience.

Thanks for make NodeSchool International Day a reality

**Comment by SomeoneWeird** [comment]
Added you as an owner.

**Comment by martinheidegger** [comment]
Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: All @SomeoneWeird  did was following: nodeschool/organizers#28 Now you can do that too!

**Comment by cronopio** [comment]
@martinheidegger @SomeoneWeird Awesome!! Thank you so much guys!
