### ISSUE TITLE
I want to add a chapter, can I be added as an Owner?

### ISSUE THREAD

**Issue by fritzvd** [nodeschool/organizers#211]
Hi Nodeschool,

I'm Fritz (@fritzvd on most networks e.g. [twitter](https://twitter.com/fritzvd), and I work at [Nelen & Schuurmans](https://nelen-schuurmans.nl) (hydrology consulting with flooding simulation and lots of Geo stuff). I started and co-host and co-organize the [Utrecht JS meetup](http://www.meetup.com/Utrecht-JavaScript-Meetup/). For the city I work in Utrecht, I'd love to start a chapter and get going with an OaklandJS style open setup. For this I already have a hosting location with a proper internet connection and seating for about 10 people. I'm thinking of asking people to co-organize this with, like the one who's organizing the meetups with me (@thabemmz)

Looking forward,

Fritz

**Comment by jasonrhodes** [comment]
@fritzvd hey hey! I added you as an owner. You can follow the directions in the README here to get the chapter set up. Let me know if you have questions! Welcome! :)

**Comment by jasonrhodes** [comment]
PS you can add co-organizers as owners as you see fit.

**Comment by fritzvd** [comment]
Thanks dude. (fancy meeting you here :+1:)
