### ISSUE TITLE
Permissions to add a edmonton repo/chapter

### ISSUE THREAD

**Issue by ryanramage** [nodeschool/organizers#212]
Hi, I would like to start a nodeschool chapter for Edmonton, Alberta. I am @ryan_ramage_ on twitter and work on node stuff all day long. I will be co-organizing this chapter with some others that are pending me telling others. I have been using Node.js for 4 years and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hello @ryanramage!

I invited you to the owners list, please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapters!

PS.: All I did was following: nodeschool/organizers#28 Now you can do that too!
