### ISSUE TITLE
Hello all, new chapter setup request

### ISSUE THREAD

**Issue by razvansky** [nodeschool/organizers#213]
Hello all,

I would like to start a nodeschool chapter for [Bucharest, Romania]. I am @razvansky on twitter and since September, 2014 I work as a consultant/freelancer. I have been working in finance technology for 15 years and turned freelancer last year. I moved from Frankfurt to Bucharest were I started a small software company and I am preparing some coding curriculums for students.
I have attended a Node School event in Hamburg in February 2015. I have been evaluating Node.js for 12 months and also did a couple of pilot projects based on [MeteorJS](https://github.com/meteor/meteor) (which uses node.js as a backend) and I am also participating to [TelescopeJS](https://github.com/TelescopeJS/Telescope) (an open source social community software based on Meteor.JS) would like to help others learn as well.

I have currently and assignement in Munich until 18 Mai, after that I will start with the Romanian translation.

Best regards,

Raz

**Comment by martinheidegger** [comment]
Hello @razvansky!

@iamcamps was searching for people trying to do this with him in https://github.com/nodeschool/discussions/issues/611
Well: I added you to the owners list (like described in #28) and you should now be following https://github.com/nodeschool/organizers/blob/master/README.md to setup the romanian chapter!

cheers
Martin.

**Comment by razvansky** [comment]
Hi Marti,

thank you and thanks for pointing me to #611. You are well informed. :-) I'm a team player, give me some time to accommodate and I will het in touch.

I participated at the last BucharestJS meetup in February, I hope I'll be back in Bucharest by the time the BucharestJS meetup take place end of Mai and will try to assemble a team!

Have a great day!
