### ISSUE TITLE
New Chapter - San Luis Obispo, Ca USA

### ISSUE THREAD

**Issue by ecwyne** [nodeschool/organizers#214]
Hi, I would like to start a nodeschool chapter for [San Luis Obispo, California](http://en.wikipedia.org/wiki/San_Luis_Obispo,_California) (halfway between Los Angeles and San Francisco). I don't have a twitter, but I work for a smallish company called Grade Potential in town. I work primarily alone to build custom solutions for business processes using Node and [Meteor](https://github.com/meteor/meteor). I'm in a [college town](http://en.wikipedia.org/wiki/California_Polytechnic_State_University) with a [growing tech community](http://www.keyt.com/news/san-luis-obispo-among-nations-best-in-tech-job-growth/26735896) that's currently lacking a community to learn and share about programming in node, I wanted to provide a space for students to come learn how to use Node/Meteor as well as a place for developers to gather and grow as we mentor together. I am self-taught and have been working in node as my primary framework for 3+ years

**Comment by martinheidegger** [comment]
?

**Comment by ecwyne** [comment]
I've already created the repo [here](https://github.com/nodeschool/san-luis-obispo) and updated the nodeschool.io site (https://github.com/nodeschool/nodeschool.github.io/commit/d15537dea39f91b78d4f45b3b43c1ae3d560b6a9) so I didn't think I still needed this issues to be open. Let me know if you have any other thoughts @martinheidegger

**Comment by martinheidegger** [comment]
Oh! No problem, just wondered what was going on ;)
