### ISSUE TITLE
Request for permission to start a chapter Melbourne, Australia

### ISSUE THREAD

**Issue by mirazmamun** [nodeschool/organizers#215]
Hi, I am Miraz Al-Mamun. I would like to start a nodeschool chapter for Melbourne. I am @mirazalmamun on twitter and work at Bruel & Kjaer EMS, based in Melbourne, we develop web apps based on GIS. At this moment I would be the fist person to start this initiative. I have been with nodejs for more that a year. I am pretty keen to get involved in building and collaborating with the community. Cheers

**Comment by martinheidegger** [comment]
@mirazmamun There is already a nodeschool in melbourne! How about engaging as a mentor there? If you write a message to: https://github.com/nodeschool/Melbourne/issues I am sure that they look forward to meet you! Also: Did you know of: http://v.campjs.com/

**Comment by martinheidegger** [comment]
I assume you know of it, closing this issue.
