### ISSUE TITLE
Belfast, UK chapter

### ISSUE THREAD

**Issue by d3z** [nodeschool/organizers#216]
Hi, I would like to start a nodeschool chapter for Belfast, UK. I am@d3z on twitter and github. I will be co-organizing this chapter with others whose names I can supply later ... when they volunteer !!

I really have been using Node.js for 6 months and I'm hoping that I can pull in some more experienced users to help mentor. It's all for myself really ;)

We already have a vibrant javascript meetup in the city, but we think that a group focused more on directed learning would be really useful.

**Comment by martinheidegger** [comment]
Hello @d3z !

Thank you for your interest. I added you to the owners list (like described in #28) and you can now follow the https://github.com/nodeschool/organizers/blob/master/README.md to setup the belfast chapter and help out with many other things :wink: - cheers!
