### ISSUE TITLE
New Chapter in Hong Kong

### ISSUE THREAD

**Issue by neilnand** [nodeschool/organizers#218]
Hi there

I would like to start a chapter for my Meetup Group - HKWD (www.meetup.com/HK-Web-Developers/). I am @neilnand on Twitter and used to be based in Hong Kong, however currently living in Helsinki. I will be organising the Chapter with my co-organisers (Rowland Watkins, Bart Verkoeijen, Marc Linder, Rhys Turner and Chris Hitchcott). I have used NodeJS for a variety of commercial projects for Lincoln Motors, Swire and a few other clients.

Cheers, Neil

**Comment by martinheidegger** [comment]
Hello @neilnand !

Sounds awesome. HK sure is a vibrant place. I added you to the owners list (like described in #28) and you can follow https://github.com/nodeschool/organizers/blob/master/README.md now to setup the hong kong chapter! Please make sure that the chapter is attended by someone in your absence :wink: 

_Note: now that you are added as owner to the NodeSchool which makes it possible that you can help out everywhere, including approving new chapter requests!_
