### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by finnp** [nodeschool/organizers#219]
Hey @trosetty,

I saw that you created some info in the [organizers github wiki](https://github.com/nodeschool/organizers/wiki/Setting-up-your-chapter). Nice effort, the infos there are actually pretty great.

However: I prefer having the infos checked in as files in the repos.  For example there is already a guide on how to set up a new chapter in this readme.md file: https://github.com/nodeschool/organizers/blob/master/README.md#how-to-start-a-new-nodeschool-chapter The process there is a bit different to what you describe.

I especially like your installation instructions, maybe you could create a `installation.md` in  https://github.com/nodeschool/discussions with those infos?

Best,
Finn

**Comment by maxogden** [comment]
@finnp YO! I'm helping @trosetty at a documentation hackathon in Portland today. It's a work in progress but we are kickstarting use of the organizers wiki to encourage organizers to share best practices (which doesn't happen as much as it should at the moment -- its mostly me you and @martinheidegger updating the docs in the organizers repo at the moment).

The big goal is to reduce the number of places where guides exist. I wanna give the wiki a shot and see if we can make it sustainable for this use case (organizer info).

**Comment by finnp** [comment]
Ah, okay, sounds cool!  :bee:  Was a bit confused by the sudden wiki activity :)
