### ISSUE TITLE
Concerns about a lack of incrementalism in workshops and the workbook approach.

### ISSUE THREAD

**Issue by mikeal** [nodeschool/organizers#22]
> These are some thoughts I've had after the Berlin Node School during JSFest Berlin which, to my knowledge, was the first to use the workbook approach. These thoughts solified much more as I started working on `learnjs`, a workshop for learning JavaScript and programming in general.

To date, Node School events have worked best when the comfort level of the people attending is already high in Programming, JavaScript, command line, and Node. Even before Berlin, I noticed that our workshops and approach works best when the assumptions authors make about the audience's existing knowledge holds true (and most of them make a lot of assumptions). In Berlin, everyone was doing learnyounode, and many of them did not know JavaScript or had ever used Node. In fact, I'm pretty sure we installed Node on at least half of the attendees machines.

The "workbook" requires that you already sort of understand GitHub. You can have them just download the zip flie, but then it makes no sense because they just get a bunch of empty files and are sort of confused, and at the end they are like "what do you mean push my work to GitHub?"

In addition, all existing programs which assume the user doesn't already know workshopper will ask the use to create a file name "program.js" and use it for the workshop. This discrepancy is very confusing for new people who just downloaded a bunch of empty files with identical names to the workshop lessons.

The Windows experience is painful, even more than the regular Windows experience. Do you know a simple way to dump users in to the command line in whatever place they just put all those files, which is actually a few directories deep even from the zip they extract? I didn't, and I still don't. Imagine how someone who has never used the command line feels, they don't even known tab completion is a thing and they are typing these long `cd` commands.

Not to pick on it too much, but `learnyounode` is a very difficult way to teach people Progamming/JavaScript. There is a pretty deep assumption in learnyounode that you already know JavaScript and how to write code somewhat effectively. Even then, there's a huge number of assumptions made and in many lessons, you actually have to get your head around more than one concept at once with the other concepts essentially being implied. My solution to this for `learnjs` has been to take an incredibly incremental approach, where each concept is introduced lightly and ends up being only small edits to the existing file from the prior lesson. The problem here is that this doesn't work that well with the workbook approach because you're told to start each lesson in a new file.

In fact, I'm starting to think that the best way to structure **all** workshoppers is to modify an existing file and change/add to it with every lesson and if a workshopper doesn't follow this linear incremental approach it probably isn't suited for new users at all. There's a confidence that you can build in people by improving and editing their program. Every time that person is faced with a new empty file it sets their confidence level back to zero.

Lastly, and this is a problem across every workshop, we are too facinated with *proving* people's work. It's actually fine to tell people *exactly* how to do something, without trying to trick them or obfuscate the answer. In fact, I'd love to see an `answer` command added to workshopper/adventure so that people can skip to the answer and pull from it when they are stuck. Seeing the answer is a great way to learn, you can work backwards from that in order to understand what is going on.

I'm going to follow up with another post about the process and issues with installing node that is related to all this but isn't specific to the issues I've raised here.

**Comment by martinheidegger** [comment]
@jasonrhodes Yes: the should be resources like that in the org: I have opened #378 that focusses on this issue from a slightly different perspective.
