### ISSUE TITLE
Chapter for Bratislava, Slovakia

### ISSUE THREAD

**Issue by yangwao** [nodeschool/organizers#220]
Hello, I'd like to start a nodeschool chapter for https://github.com/nodeba/nodeba, located in my town  Bratislava, Slovakia. I've done previously little meetup here http://www.meetup.com/nodeba/events/194718812/ and meeting folks randomly. So I now decided to make up nodeschool chapter. You can find me on twitter like @yangwao and I'm working on CRM Aktiv.io and password manager SaferPass.net right now. 
I'll be organizing this chapter for now myself, but I asked at local nodejs facebook group for help to find out some sponsors and mentors to achieve ratio 1:5 :smile: 
I've been using node.js since 0.1.98, hope that's enough :smiley: 
Also proud member of #polyhack community as well

**Comment by SomeoneWeird** [comment]
Sent you an invite :)

**Comment by martinheidegger** [comment]
@yangwao @SomeoneWeird  added you to the owners list (like described in #28) and you can do that to (please close issues after the deed was done ;) )
