### ISSUE TITLE
Chapter for Zagreb, Croatia

### ISSUE THREAD

**Issue by shime** [nodeschool/organizers#221]
Hi, I would like to start a nodeschool chapter for Zagreb, Croatia. I am [@shimetweets](https://twitter.com/shimetweets) on twitter and I will be co-organizing this chapter with [@dinodsaurus](https://twitter.com/dinodsaurus). We have been using Node.js for some time and would like to help others learn as well and to support the recent growth of our local developer communities here in Croatia.

We will host another international node school day event tomorrow here in Varaždin, Croatia.

**Comment by martinheidegger** [comment]
@shime you should register the International day event on the international-day repo!

I have added you as owner (following https://github.com/nodeschool/organizers/issues/28) Please setup the zegrab chapter as described in https://github.com/nodeschool/organizers/blob/master/README.md

**Comment by martinheidegger** [comment]
Also side-note: we need all hands on deck ;)

**Comment by shime** [comment]
thank you for the prompt response, @martinheidegger!

**Comment by iancrowther** [comment]
are their any photos/videos/logos from this event?
