### ISSUE TITLE
Make "Solutions" repo

### ISSUE THREAD

**Issue by marinintim** [nodeschool/organizers#224]
I wrote about it in Gitter, but thought that putting it here would make more sense.

I suggest creating `solutions` repo, where students' solutions would be hosted.

We could create branch per student and inside would lie solutions grouped by workshop.

```
branch marinintim
  - learnyounode
    - 1.js
    - 2.js
    - 3.js
  - kick-off-koa
    - 1.js
    - 2.js
    - 3.js
```

Student would make a fork, switch to his branch, commit and send pull request back.

Pros:
* We could do code review. Useful when student continues working at workshop at home.
* We could do some CI on this and give student some achievements for that. Like, `you've completed 100 challenges, good work!`
* Branches guaranteed to be unique due to uniqueness of github usernames.

Contras:
* It would be a heavy repo (many branches), so slow
* It would create more hassle to start. (install git, fork repo, checkout repo, create branch, commit, push, create pull request...), but could be solved if it would be optional.
* It would be too easy to look at another students' solutions, but I don't think that it's even a Contras point.

We plan to try this scheme at next event, but general repo would be great.

So, what do you think?
*

**Comment by martinheidegger** [comment]
There is already a repo for this. Some improvements would be nice. https://github.com/nodeschool/workbook
