### ISSUE TITLE
New chapter for Tacoma, WA

### ISSUE THREAD

**Issue by NorthDecoder** [nodeschool/organizers#225]
Hi Theophilus,

I would like to start a node school chapter for Tacoma, WA. I am Joe Devlin at [LinkedIn](https://www.linkedin.com/pub/joe-devlin/a3/413/808/) and work at [Vivid Ventures LLC](http://vividventures.biz/) . I will be co-organizing this chapter with the Tacoma Javascript meetup [TacomaJS](http://www.meetup.com/Tacoma-JS/). There are currently around 100 members of TacomaJS and several members have already made node presentations [1](http://www.slideshare.net/JoeDevlin2/meetup-js-032815) [2](http://www.meetup.com/Tacoma-JS/messages/boards/thread/48545559).  There is a strong interest about node.js from the membership.

We follow a guideline of present, code, discuss in a short time frame.  Maybe ten minutes of presenting and twenty minutes of coding, discussion to fix everyone's code problems then we move on to the next part of the presentation. Usually we meet from 0830 - 1200 around the last Saturday of the month depending on room availability.  Recently I have experimented with a midweek mid-afternoon meeting and had good attendance with that too.

I would like to promote our meetings to interested people in the vicinity via a node school chapter.  We hope you agree :smile:

**Comment by bcomnes** [comment]
lgtm :+1:

**Comment by martinheidegger** [comment]
Hello @NorthDecoder  !

Sounds awesome. Have yet to set foot on american soil but it sounds great! I added you to the owners list (like described in #28) and you can follow https://github.com/nodeschool/organizers/blob/master/README.md now to setup the chapter!

Note: now that you are added as owner to the NodeSchool which makes it possible that you can help out everywhere, including approving new chapter requests!

**Comment by NorthDecoder** [comment]
Thanks Martin,

Every time I return home to the Pacific Northwest from
a great vacation I think this is the best, and I get
to live here!

I will work on getting our site set up.
Thanks for the review.

Joe Devlin

->-----Original Message-----
->From: Martin Heidegger [mailto:notifications@github.com]
->Sent: Friday, June 05, 2015 8:09 PM
->To: nodeschool/organizers
->Cc: Joe Devlin
->Subject: Re: [organizers] New chapter for Tacoma, WA (#225)
->
->Hello @NorthDecoder <https://github.com/NorthDecoder>  !
->
->Sounds awesome. Have yet to set foot on american soil but it sounds great! I added you to the
->owners list (like described in #28 <https://github.com/nodeschool/organizers/issues/28> ) and
->you can follow https://github.com/nodeschool/organizers/blob/master/README.md now to setup the
->chapter!
->
->Note: now that you are added as owner to the NodeSchool which makes it possible that you can
->help out everywhere, including approving new chapter requests!
->
->—
->Reply to this email directly or view it on GitHub
-><https://github.com/nodeschool/organizers/issues/225#issuecomment-109512905> .
-><https://github.com/notifications/beacon/AJJ0OLM_3TyS-
->t0KGRHGFNBlgVI3NodZks5oQlvIgaJpZM4E6CLv.gif>
