### ISSUE TITLE
New Chapter in Ho Chi Minh city (Saigon)

### ISSUE THREAD

**Issue by okaiji** [nodeschool/organizers#227]
Hey, I would like to start a nodeschool chapter based in Ho Chi Minh city (HCMC, Saigon) of Vietnam (In the south) [View city link] (https://nodeschool-hcmc-saigon.doorkeeper.jp). I am [@nkaijie] (https://twitter.com/nkaijie) on twitter, work at [@InnovQ] (https://twitter.com/InnovQ) on [BallPark.SG] (http://ballpark.sg) . I will be co-hosting this chapter with @fw1065, @balasivagnanam. We have been using, writing Meteor/Node.js (framework) for 2-3 month and currently based in HCMC, therefore love to contribute back to our community, on learning about Git and hosting coding workshops in hcmc.

Have successfully curated the following events with my co-hosts, early this year: 
[#ideaflowtalk] (https://nvite.com/IdeaFlowTalk/cbfb) and [#dribbblemeetup] (https://nvite.com/dribbblemeetup/c508) in the first quarter for SG also.

**Comment by dominhhai** [comment]
Hey, I'm an orig-er of Hanoi [NodeSchool](https://github.com/nodeschool/hanoi). Really awesome!

**Comment by martinheidegger** [comment]
@dominhhai Since you are close, do you want to invite them like written in #28?

**Comment by dominhhai** [comment]
Thx @martinheidegger  @okaiji !

I added you - @okaiji to the owners list (as described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the HCM chapter! 

I intend to group the Vietnam-based chapters on the same [chat place on Gitter](https://gitter.im/nodeschool/vietnam-chapter). There are some nice HCM's guys joining this group who want to join as mentor also. So, it's nice if we can cooperate in the same place.
