### ISSUE TITLE
New Chapter - Anchorage, Alaska

### ISSUE THREAD

**Issue by thejones** [nodeschool/organizers#229]
Hi, I would like to start a nodeschool chapter for Anchorage, Alaska. I am [@bearsdoingyoga](https://twitter.com/bearsdoingyoga) on twitter. I will be co-organizing this chapter with [Mike Humphrey](https://github.com/mikehumphrey). I have been using Node.js for 1 year and would like to help others learn as well.

**Comment by dominhhai** [comment]
Hey @thejones  !

I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the Anchorage chapter!
