### ISSUE TITLE
Failure is harsh.

### ISSUE THREAD

**Issue by mikeal** [nodeschool/organizers#23]
One thing I've noticed running through workshops is that the failure case is pretty harsh, especially for people brand new to programming that are actually worried they might break their computer at any moment.

In all the tools it's like "YOU FAILED!" and it's red across the terminal. How about we use orange, and throw in random sentences of encouragement. The process of programming is basically failing and observing that failure, we can teach them this as they learn through NodeSchool workshops by using the failure text as a place to instruct them.

**Comment by Sequoia** [comment]
@samjewell :+1: this idea, I was thinking the same thing the other day.
```
└── problem               
    ├── solution       
    │   └── ...
    ├── exercise.js
    ├── problem.md
    └── hints.md       # run `learnyounode hint` to get this
```
There are currently hints in the exercises typically, but this would be for more explicit, point-you-directly-towards-the-answer hints.

Will consider trying to write & adding PR for workshopper, but don't wait up for me if you've got a notion to do it yourself :smile_cat:

**Comment by martinheidegger** [comment]
Assuming this issue is not relevant anymore, closing it. If you need to reopen it: I think this is not the right repo.
