### ISSUE TITLE
Augusta Chapter

### ISSUE THREAD

**Issue by kpeeples** [nodeschool/organizers#230]
Hi, I would like to start a nodeschool chapter for Augusta, GA, USA. I am @ossmentor on twitter and work at Red Hat . I will be co-organizing this chapter with Eric Parker. I have been using Node.js for approximately 3-6 months and would like to help others learn as well.    I would like to start the repo, https://github.com/nodeschool/augusta

**Comment by dominhhai** [comment]
Hey @kpeeples !

I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the Augusta chapter!

**Comment by dominhhai** [comment]
Hey @kpeeples !

I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the Augusta chapter!

**Comment by kpeeples** [comment]
thank you!  I will be setting up the Augusta Chapter now.  I had a big conference for Red Hat to prepare/attend this past week.  So now onto creating the Augusta Node School Chapter.

**Comment by dominhhai** [comment]
:100:
