### ISSUE TITLE
Heidelberg Chapter

### ISSUE THREAD

**Issue by martensms** [nodeschool/organizers#231]
Hey guys,

please add me as an owner to the nodeschool organization. We plan to organize a nodeschool around here in Heidelberg, Germany.

As the HeidelbergJS was a huge success, we now try to move the node-battlefront a bit more to the real world :)

**Comment by dominhhai** [comment]
Hey @martensms !

I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the Heidelberg chapter!

**Comment by martensms** [comment]
Thank you very much!

**Comment by dominhhai** [comment]
:+1: let make a strong community :100:
