### ISSUE TITLE
nodeschool ankara / turkey

### ISSUE THREAD

**Issue by trkozd** [nodeschool/organizers#232]
Hi, I would like to start a nodeschool chapter for Ankara / Turkey . I am Türker Özdamar working at Sebit Eğitim ve Bilgi Teknolojileri A.Ş as Team Leader, Software Development. I will be co-organizing this chapter with Sertaç Aydın studying at METU | Middle East Technical University. We have been using Node.js for 1 month and would like to help others learn as well.

**Comment by dominhhai** [comment]
Hey @trkozd !

I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the Ankara chapter!
