### ISSUE TITLE
Cincinnati Chapter

### ISSUE THREAD

**Issue by fiveisprime** [nodeschool/organizers#234]
Hi,

I would like to start a nodeschool chapter for Cincinnati, OH. I am
@fiveisprime on twitter and work at Modulus. I will be co-organizing this
chapter with @jackboberg and @Tzmanics. I have been using Node.js for 3 years
and would like to help others learn as well.

I am interested in removing the barriers that I see most often in my area to
bring new members into what I feel is the best community of developers around.

Thanks!

**Comment by dominhhai** [comment]
Hey @fiveisprime  !

Thank you for registering :+1:  I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the Cincinnati chapter!

**Comment by gyaresu** [comment]
Good luck! @fiveisprime :+1:
