### ISSUE TITLE
New chapter in São Paulo, Brazil

### ISSUE THREAD

**Issue by thebergamo** [nodeschool/organizers#236]
Hi, I would like to start a nodeschool chapter for São Paulo, Brazil. I am @thebergamo on twitter and work at Pagar.me. I have been using Node.js for 2 years and would like to help others learn as well.

Thanks =D

**Comment by dominhhai** [comment]
Do you org with others?

**Comment by thebergamo** [comment]
Yes, initial @alanhoff

**Comment by alanhoff** [comment]
Confirmed.

**Comment by dominhhai** [comment]
:+1:  awesome!
I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the Cincinnati chapter!

**Comment by thebergamo** [comment]
Perfect!

I'll do this ASAP =D
