### ISSUE TITLE
New Chapter for Strasbourg (France)

### ISSUE THREAD

**Issue by jsebfranck** [nodeschool/organizers#237]
Hi, I would like to start a nodeschool chapter for Strasbourg (France). I am jsebfranck on twitter and work at Sfeir. I will be co-organizing this chapter with Sven SAULEAU and Edgar HIPP (@edgarhipp on twitter). I have been using Node.js for two years and would like to help others learn as well.

**Comment by jsebfranck** [comment]
Hi, what is the next step to organize my first nodeschool session?

**Comment by jsebfranck** [comment]
I did my chapter request two months ago. In the meantime others chapter requests have been approved. I would love to organize a first session in september. Should I forget this idea? Maybe Strasbourg city is not big enough to catch your attention? :(

**Comment by marocchino** [comment]
Hello, @jsebfranck. I'm sorry for late. I just invite you.

This [guide](https://github.com/nodeschool/organizers/blob/master/README.md#how-to-start-a-new-nodeschool-chapter) can help you. Good luck!

**Comment by jsebfranck** [comment]
Thanks ! :)
