### ISSUE TITLE
New Chapter for Lowell, MA

### ISSUE THREAD

**Issue by GaryChamberlain** [nodeschool/organizers#238]
Hi, I would like to start a nodeschool chapter for Lowell, MA. I work at [Pro Graphics, Inc.](https://pro.graphics/) I will be organizing this chapter myself and seeking co-organizers. I have been using Node.js for 6 months and would like to help others learn as well.

http://www.meetup.com/Modern-Javascript/

**Comment by dominhhai** [comment]
Hey @GaryChamberlain 
I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the Lowell, MA chapter! 

:100:

**Comment by martinheidegger** [comment]
Closing this issue, please let me know if I did so prematurely.
