### ISSUE TITLE
Terminal color issues

### ISSUE THREAD

**Issue by mikeal** [nodeschool/organizers#24]
I have no idea how to fix this, but I noticed at the NodeSchool in Berlin one woman could not figure out what the hell she was doing wrong because the example text used a terminal color that was light grey and she had a dark terminal background with transparency on so the quote was almost invisible.

**Comment by archieopteryx** [comment]
In windows you can change the colours using the color command

>color *nn*

where *nn* is a two digit hexadecimal number. The first digit is the background and the second the text colour. For example

>color E2

will give you an eye watering yellow and green!

Downside is that you lose any colour highlighting, and every time you go to a new section it'll be reset. But at least it's quick to change and you can read everything.

**Comment by Pharylon** [comment]
I know there hasn't been any talk about this in a while, but seriously, it's super annoying. LearnYouNode is barely usable on Windows.

**Comment by maxogden** [comment]
@Pharylon if you install https://git-scm.com/download/win and use the Git Bash it installs as your shell it looks good

**Comment by Pharylon** [comment]
I already had git bash installed since it came with git, but it gives this error when I try to launch learnyounode: "Please start this in a tty-compatible terminal program."

**Comment by martinheidegger** [comment]
The terminal colors should have become arguably better on most platforms a while ago. closing this issue. Please reopen in [msee](github.com/firede/msee) if it occurs again.
