### ISSUE TITLE
Nodeschool in Guatemala City

### ISSUE THREAD

**Issue by edwinallenz** [nodeschool/organizers#240]
As I mentioned at nodeconf, I'm starting to create a nodeschool chapter in Guatemala City, the first one I want to build is inside a public university [USAC](http://www.usac.edu.gt) which is the most important in Guatemala City. You can reachme at @fredjourney

**Comment by dominhhai** [comment]
Who are your co-organizers?

**Comment by edwinallenz** [comment]
@bladimir47 and @ottogiron

**Comment by dominhhai** [comment]
Thank you  :+1: 
I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the your chapter!

**Comment by edwinallenz** [comment]
Thanks

On Sat, Jul 11, 2015 at 7:34 AM, Do Minh Hai <notifications@github.com>
wrote:

> Thank you [image: :+1:]
> I added you to the owners list (like described in #28
> <https://github.com/nodeschool/organizers/issues/28>).
> Now, you can follow
> https://github.com/nodeschool/organizers/blob/master/README.md to setup
> the your chapter!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/organizers/issues/240#issuecomment-120578215>
> .
>



-- 
www.edwinallenz.com

Aprendiendo a crear, a innovar, a construir, a emprender.
eAz.

**Comment by dominhhai** [comment]
:100:
