### ISSUE TITLE
Denton Texas nodeSchool

### ISSUE THREAD

**Issue by MichaelJCole** [nodeschool/organizers#242]
Hi, I would like to start a nodeschool chapter for Denton TX. 

I am a freelance MEAN fullstack developer. 

I will be co-organizing this chapter with some people from the Techmill co-working space I just met.  We're still organizing. 

I have been using Node.js for ~1 year and would like to help others learn as well.

**Comment by dominhhai** [comment]
Hey @MichaelJCole 
I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the your chapter! 

:100:
