### ISSUE TITLE
New chapter in Mauritius

### ISSUE THREAD

**Issue by daviddiasfront** [nodeschool/organizers#243]
Hi, I would like to start a nodeschool chapter for Mauritius Island (Indian Ocean). I am @daviddiasfront on twitter and work on Proximity BBDO (marketing / digital agency). I will be co-organizing this chapter with @_kyushiro. I have been using Node.js for 2 years and would like to help others learn as well. I participated to a NodeSchool Paris (France) meetup, and I thought to create the same in Mauritius.

**Comment by dominhhai** [comment]
Hey @daviddiasfront  
I added you to the owners list (like described in #28).
Now, you can follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the your chapter! 

:100:

**Comment by daviddiasfront** [comment]
Thank you a lot @dominhhai, you'll see soon our first meeting happening !
