### ISSUE TITLE
Question for upcoming SF event

### ISSUE THREAD

**Issue by RoseTHERESA** [nodeschool/organizers#245]
Hi,
Is it okay to show up a bit late on 7/25? I should be there by 1:30.

Thanks in advance,
Rose

**Comment by jedireza** [comment]
Hi @RoseTHERESA :smile:

> Is it okay to show up a bit late on 7/25? I should be there by 1:30.

That's fine. Whatever you miss we can catch you up on.

Also feel free to create issues in our chapter's repo https://github.com/nodeschool/sanfrancisco/ since not everyone in SF monitors this `organizers` repo.
