### ISSUE TITLE
Chapter request for Reykjavík, Iceland.

### ISSUE THREAD

**Issue by koddsson** [nodeschool/organizers#249]
Hi, I would like to start a nodeschool chapter for Reykjavík, Iceland. I am @koddsson on twitter and work at [Bókun](http://bokun.io/). Me and some other people have been running javascript meetups for sometime now in Iceland and I will be co-organizing this chapter with other people from the [javascript iceland user group](https://github.com/jsis).

**Comment by finnp** [comment]
@nodeschoolbot create-repo reykjavik

**Comment by finnp** [comment]
Hey. This sounds really great. I just invited you to the organizers team and created a repository for Reykjavík: https://github.com/nodeschool/reykjavik. It's great to see another European country joining NodeSchool :sparkles: :snowflake:

Make sure to follow the steps here: https://github.com/nodeschool/organizers#1
