### ISSUE TITLE
How to install Node.js docs for mentors

### ISSUE THREAD

**Issue by mikeal** [nodeschool/organizers#25]
We need to create a comprehensive guide to installing node along with all the crazy things you'll have to fix across different operating systems and install methods.

In Berlin, ever person on Mac and Linux had to get a permission fix in order to npm install anything.

Also, and I'm going to loop in @othiym23 and @zeke on this one, when NPM gets that dreadful "EACCESS" error it should come with some text about how to clean up the permissions in order to fix it :)

It might also be good to let the nodeforward/welcome people know about this as they'll probably want to link to it.

**Comment by iancrowther** [comment]
I always recommend Node installer for beginners and nvm for advanced.

**Comment by greelgorke** [comment]
in Hamburg we made good experience with cloud9 ide for beginners

**Comment by riyadhalnur** [comment]
I would recommend using `nvm` on OSX and Linux. Easiest way to maintain multiple versions of Node and easy to get started with.

**Comment by martinheidegger** [comment]
Plenty of docs in https://github.com/nodeschool/discussions by now, closing this issue.
