### ISSUE TITLE
Should we bring back chapter teams (GitHub Org question)?

### ISSUE THREAD

**Issue by maxogden** [nodeschool/organizers#250]
## The old way

We used to have a team-per-chapter, so the repo `nodeschool/berlin` also had a corresponding team called `berlin`. This was nice because we had the chapter organizer be both a member of `berlin` and `Owners`, giving them the ability to do team management (invite people to teams, create repos).

The chapter repo was owned by the chapter team, so anyone added to `berlin` could push to their repo. This meant only the small number of organizers in `Owners` had the superuser privileges that let them delete the entire org (which eventually happened the other night).

## The new way?

GitHub is currently working on improving org permissions: https://github.com/orgs/improved-permissions. We can't have them yet, but they will ship eventually and should solve a lot of the issues we've had, because according to the checklist on their site it says members will be able to create teams and create repositories. The only lacking thing I can see is that it still requires an Owner to invite new members, but we now have @nodeschoolbot for that.

The other thing we used chapter teams for was for chapter membership. Some chapters had all of their attendees invited to their chapter team, so that when they wanted to do meetups they could use their repo issue tracker as a message board to plan + announce meetups. This would be awesome to bring back.

## What do you think?

So that's the situation. I would love some thoughtful feedback on what you think we should do given what features are coming soon (hopefully) to GitHub and what we have now. For a refresher on our current 'new chapter' workflow check out the organizers readme, which I updated to reflect the new `chapter-organizers` team: https://github.com/nodeschool/organizers/#how-to-start-a-new-nodeschool-chapter

**Comment by finnp** [comment]
I think we should add "Create team" and "Add people to team" functionality to the nodeschool bot as long as there are no improved permissions.

The bot would allow chapter organizers and maybe team members to add new people to a team.

To make sure team members can get push access to the chapter repos, it should be possible to link them. Maybe "Create team berlin" would automatically look for a repo /berlin and give people from this team access rights to that repo.

For convenience there could also be a "create chapter <xyz>" command which creates a team and a repo for `<xyz>`

**Comment by iancrowther** [comment]
is a good way to ping your regular mentors etc so +1 from me

**Comment by dylants** [comment]
For our (Austin) NodeSchool chapter, the only team we need at this time would be one for those who want to help mentor others in the group.  We want to give these mentors write access to our chapter repo.  Given that we already have the `chapter-organizers` team, I'm not sure how the permissions would differ for our proposed  `mentors` group.  With this in mind, maybe we shouldn't add any more teams unless there really is a need to split permissions further, and just add the mentors to the `chapter-organizers` team?

What do you think?

**Comment by ahdinosaur** [comment]
for our Wellington chapter, i was adding everyone who came to our weekly meetup a few times to the chapter team so that we could use our repo issues for group discussions and announcements. i'd appreciate if our team could be restored (or at least get a list of handles so i can re-create the team, i'm afraid i may have forgotten the handles of some people); the details of team permissions don't matter much to me.

**Comment by SomeoneWeird** [comment]
Yeah, I think we should re-create the teams, it makes management easier and allows you to ping an entire time @nodeschool/team etc.

**Comment by ionescu77** [comment]
I agree I miss not having tested this feature!

**Comment by iancrowther** [comment]
based on the new bot we can create our own teams.  this would save "team recovery" some work.  

if we are happy to put our chapter teams back together ourselves we can close this issue?

**Comment by iancrowther** [comment]
@ahdinosaur do attendees reg a tkt to your event? if so can you check your own records?

**Comment by dylants** [comment]
@iancrowther Do you mean the `nodeschoolbot`?  The help output from the other issue post didn't mention the ability to create teams: https://github.com/nodeschool/organizers/issues/248#issuecomment-126023805?  If it can create a team, I'm not sure how we would do that.  Would we just create an issue, and within it, request that the bot create a team?

Thanks for the help!

**Comment by SomeoneWeird** [comment]
If @maxogden doesn't have any objections - I'll open another issue and start creating chapter teams if people want?

**Comment by ahdinosaur** [comment]
@iancrowther some attendees RSVP to our Meetup events, but then i'll need to manually go through every week's event to get the attendee's Meetup name and search for them on GitHub, which is how i arrived at the team members pre-delete and was ideally hoping to not start over. if it's not possible it's all good, just sharing where i'm at.

**Comment by SomeoneWeird** [comment]
@ahdinosaur I don't think we have a list of previous members per-team, unfortunately.

**Comment by ahdinosaur** [comment]
@SomeoneWeird ah right, no worries. :smile_cat:

**Comment by dylants** [comment]
@SomeoneWeird Creating the chapter teams sounds great to me!

**Comment by SomeoneWeird** [comment]
#258
