### ISSUE TITLE
Do you mind making me owner?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#257]
My account is not allowed to publish the nodeschool website :( thus the homepage script can not be updated. Would it be possible to add me as read/write to the homepage repo or add me as owner?

**Comment by SomeoneWeird** [comment]
Added the other team to the nodeschool website, so you should be able to publish.

re: owner, I have no problems with that because you're a great help (and you were in the owners team before) but I'd like to get one more +1 :smiley:  @nodeschool/owners

**Comment by iancrowther** [comment]
+1 for me.. @martinheidegger is a rock

**Comment by martinheidegger** [comment]
Thx guys. I have been sick for a while (nothing dramatic) and that pushed all my deadlines - now I am in a frenzy to catch up thus I am not the rock i used to be ... but thanks for the support!

**Comment by maxogden** [comment]
@martinheidegger no worries! glad to hear you're OK. @watson has been doin some great work on the website the last few days, maybe sync up with him before doing anything major

**Comment by iancrowther** [comment]
Too modist 😀

**Comment by martinheidegger** [comment]
Thx!
