### ISSUE TITLE
Nodeschool [Munich, DE]

### ISSUE THREAD

**Issue by meaku** [nodeschool/organizers#260]
We @peerigon would like to teach Node.js / JavaScript in Munich. We are already teaching a full course – not based on nodeschool – at the university in Augsburg. Nodeschool would be a great addition and nodeschools in southern Germany are still missing. 

We would also like to organize a nodeschool in Augsburg. 

First event would be after Oktoberfest in October. :beers:

**Comment by meaku** [comment]
We is @jhnns, @topa, @matthaias, @sbat, @flootr 
And we've been using Node since 0.4.

**Comment by SomeoneWeird** [comment]
Awesome! I'll create a repository and team for munich :)

@nodeschoolbot add-user meaku

**Comment by SomeoneWeird** [comment]
Done :tada: keep following the getting started guide :+1:

**Comment by meaku** [comment]
Thanks! Nodeschool is an awesome idea :+1:

**Comment by sbat** [comment]
:+1:

**Comment by meaku** [comment]
@SomeoneWeird can you give me write access for https://github.com/nodeschool/munich?

**Comment by SomeoneWeird** [comment]
@meaku Sorry! Forgot to change permissions for the munich team. You should be good now.

**Comment by meaku** [comment]
No worries! Thanks!
