### ISSUE TITLE
New NodeSchool chapter in Cordoba Argentina

### ISSUE THREAD

**Issue by avilaton** [nodeschool/organizers#261]
Hola,
I would like to set up a nodeschool chapter for Cordoba, Argentina. I am @AvilaGas on twitter and work as a freelance contractor for various open-data projects. 

I will be organizing the chapter with Alejandro Cragnolini @alejandrocragnolini-santex.

I have been using Node.js for 2 years. There is a lot of demand for a friendly meeting to get started, so we decided we would go the nodeschool way.

Thanks in advance
PS: `cordoba` would be a good name for the chapter.

**Comment by SomeoneWeird** [comment]
Done. Please follow the rest of the getting start guide :tada:

**Comment by a0viedo** [comment]
Hola @avilaton!

It's great that you guys are promoting NodeSchool in Argentina :) Let me know if I can help you with anything, or if you just want to talk about how it has been in Buenos Aires.

**Comment by iancrowther** [comment]
+1

**Comment by avilaton** [comment]
@a0viedo, @eafelix  You have been FORKED! Thanks guys, we will surely need your help getting started. We will try out a first in-house event and then try organizing a public one.
