### ISSUE TITLE
Core members

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/organizers#262]
I think @martinheidegger and @iancrowther should be part of the core team, they have been dedicating a lot of time contributing and in particular for Nodeschool International Day.

**Comment by marocchino** [comment]
:+1: :tada:

**Comment by SomeoneWeird** [comment]
I have no problem with that, I'd also recommend both you and @marocchino get added too.

**Comment by SomeoneWeird** [comment]
Also: the Core team can be removed, because of how github has changed how organisation permissions work. People just need to be listed as owners now.

**Comment by iancrowther** [comment]
Thanks guys, lovely to have your support.

**Comment by a0viedo** [comment]
Welp, better luck next time.

**Comment by iancrowther** [comment]
Can I get permissions to add teams?

**Comment by a0viedo** [comment]
ping @nodeschool/core

**Comment by SomeoneWeird** [comment]
There's a PR open over [here](https://github.com/mafintosh/nodeschoolbot/pull/1) to add the ability to create teams.

**Comment by SomeoneWeird** [comment]
@a0viedo @iancrowther @martinheidegger I've made you all owners.
