### ISSUE TITLE
Nodeschool [Augsburg, DE]

### ISSUE THREAD

**Issue by meaku** [nodeschool/organizers#263]
As an addition to Munich, we would like to teach Node.js / JavaScript in Augsburg. The university sponsors the location and nodeschool would be a perfect addition to the Node.js course at the university open to everyone.

Mentors are the same as in munich: @jhnns, @topa, @matthaias, @sbat, @flootr

**Comment by iancrowther** [comment]
Node.js course, thats cool.  Have you got a link so I can check it out

**Comment by topa** [comment]
They are all on GitHub, so the students can practice in a real word scenario :)

- [JavaScript - Winter Semester 2014/2015](https://github.com/hsa-js-ws1415/vorlesung)
- [node.js - Winter Semester 2013/2014](https://github.com/orgs/hsa-nodejs-workshop/dashboard)
- node.js for Winter Semester 2015/2015 is still wip
- and finally the description of the course on the university web-site (only in German): [Web-Entwicklung mit Node.js](https://www.hs-augsburg.de/fakultaet/informatik/studium/wahlpflichtveranstaltung/web_entwicklung_node_js/index.html)

**Comment by iancrowther** [comment]
Wow, That's amazing. I've not heard of a uni teaching node before.. Do any other institutes offer these kind of courses

**Comment by iancrowther** [comment]
Thanks for the links btw

**Comment by alexlawrence** [comment]
@topa @meaku FYI: I will be teaching JavaScript (+ browser and its APIs) again this year for the third semester of Interactive Media at the University of Augsburg (http://glossar.hs-augsburg.de/Lehrveranstaltung:IAM_2006:Multimedia-Anwendungen/Programmierung)

I guess it makes sense to read through your material and eventually update mine so the different materials about JavaScript at the same university won´t actually differ too much. :-)

Maybe I will also make my script public on Github (if allowed). However it will only be in german.

**Comment by meaku** [comment]
@SomeoneWeird can you create the repo for us please?

@alexlawrence would be great to merge some stuff if possible. We should try to push the University of Applied Sciences in Augsburg to focus on web development! Way better than SAP or other crap! Maybe we can talk about it at the next Web&Wine?

**Comment by SomeoneWeird** [comment]
done.

**Comment by meaku** [comment]
Thanks!
