### ISSUE TITLE
Install / Setup instructions

### ISSUE THREAD

**Issue by kmckee** [nodeschool/organizers#266]
Hi,

We're hosting our first NodeSchool on Monday.  I'm trying to get my hands on a nice installation / setup guide to help people install git / node / npm.  

Is there an official NodeSchool thing that I could use for this?  Any recommendations?

Thanks for your help.

**Comment by jedireza** [comment]
> We're hosting our first NodeSchool on Monday.

Congrats. That's always great to hear.

> I'm trying to get my hands on a nice installation / setup guide to help people install git / node / npm. 

If you haven't seen the mentor best practices wiki, I highly recommend it. There is a section on setup and installing node.

 - https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices

Be sure to comment and ask for more if it's not what you're looking for.

**Comment by kmckee** [comment]
Thanks for the quick response!

I recently taught at a RailsBridge event and they had some really good documentation to help walk students through getting everything installed and set up here.  I was hoping we might have something similar to this:  http://installfest.railsbridge.org/installfest/installfest  

The mentor best practices is definitely helpful, though not exactly what I had in mind.

Kyle

**Comment by jedireza** [comment]
The installer from nodejs.org should handle most cases for a fresh install. Beyond that it will depend on special cases. For instance, if someone wants to use different versions of node at the same time, I would recommend [nvm](https://github.com/creationix/nvm), which has it's own installation instructions.

You could use `brew` to install node, but at the moment it looks like they latest version there is `v0.12.7`.

I've also see tutorials using `apt-get` on Ubuntu.

In general node is really easy to install. I don't remember there being more than one or two people at a workshop that need 1-on-1 help installing node.

**Comment by iancrowther** [comment]
I cant advise you go with brew.  You'll run into permissions issues and it does not install 4 yet.

The download for the main site works well, as does nvm.  I have played with nave a lot but nvm is easier to get started with

**Comment by kmckee** [comment]
We weren't really sure what to expect since this is our first meetup and we got a pretty huge turnout for it (30 people).  I think based on your comments we will point people to nvm or just nodejs.org and help 1:1 where it's need.

Thanks for your help!
