### ISSUE TITLE
Chapter organizer Switzerland 

### ISSUE THREAD

**Issue by pungggi** [nodeschool/organizers#267]
Hello seems like in Switzerland none yet started a chapter. So Id like to try.
Im devolping since June, or better, i started my learning path, in nodejs. I would like to see more nodejs developers here in switzerland.

Chapter Name>  Nodeschool Switzerland Basel

**Comment by maxogden** [comment]
@pungggi hi, do you have any other co-organizers? we ask that new chapters have 3 organizers

**Comment by martinheidegger** [comment]
ping @pungggi !

**Comment by martinheidegger** [comment]
Closing the issue as @pungggi sadly seems to have lost interest.

**Comment by RichardLitt** [comment]
:(

**Comment by pungggi** [comment]
I simply do not have others organizers, if someone living in Switzerland would like to organize i am here.

**Comment by phipix01** [comment]
I would be very interested but basel is a bit far. If someone is interested in organizing a Nodeschool Zürich text me :)
