### ISSUE TITLE
New chapter in Chernivtsi, Ukraine

### ISSUE THREAD

**Issue by denysdovhan** [nodeschool/organizers#269]
![Theatre's Squere](https://upload.wikimedia.org/wikipedia/uk/e/e5/%D0%90%D1%80%D1%85%D1%96%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BD%D0%B8%D0%B9_%D0%B0%D0%BD%D1%81%D0%B0%D0%BC%D0%B1%D0%BB%D1%8C_%D0%A2%D0%B5%D0%B0%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%97_%D0%BF%D0%BB%D0%BE%D1%89%D1%96.Jpg)

Hi there!
I'd like to start a new nodeschool chapter for **[Chernivtsi, Ukraine](https://en.wikipedia.org/wiki/Chernivtsi)** also known as «Little Vienna». My twitter account: @denysdovhan. I'm working at Codeguida. I'm going to co-organizing this chapter with support from Chernivtsi National University. I have been using Node.js for 3 years and would like to tell students about this perfect thing.

**Comment by martinheidegger** [comment]
@nodeschoolbot add-user denysdovhan

**Comment by SomeoneWeird** [comment]
@nodeschoolbot add-user denysdovhan

**Comment by SomeoneWeird** [comment]
Must be down.

**Comment by denysdovhan** [comment]
So, what should I do?

**Comment by SomeoneWeird** [comment]
manually done. open another issue if you run into any problems :)

**Comment by denysdovhan** [comment]
Yep, I've got invite. Thnx.

P.S. I think #270 must be open, untill somebody fix @nodeschoolbot.
