### ISSUE TITLE
@nodeschoolbot is down

### ISSUE THREAD

**Issue by denysdovhan** [nodeschool/organizers#270]
I've created this issues bcoz @SomeoneWeird can't add me to the `chapter-organizers` team. As I understood @nodeschoolbot is down.

Can anyone help me with establishing my chapter (#269) in Chernivtsi?

**Comment by SomeoneWeird** [comment]
@denysdovhan Sorry you misunderstood, I manually invited and set everything up. :+1: :tada:

**Comment by denysdovhan** [comment]
oh, sorry. Nice :+1:

**Comment by maxogden** [comment]
should be all fixed now
