### ISSUE TITLE
Philadelphia Chapter

### ISSUE THREAD

**Issue by adobley** [nodeschool/organizers#271]
I'm looking to start up a nodeschool chapter in Philadelphia. I'm on twitter @adobley, am working on Yadaguru with some people from Code for Philly, and I'm developing software for the District Attorney's Office. I've been using Node.js for a while and I've found that nodeschool is a great way to introduce people to programming and node. I have a few people interested so I'm looking to get setup so we can start organizing.

Thanks.

**Comment by jsumnersmith** [comment]
+1 Count me in.

**Comment by LabLayers** [comment]
👍 I would also be interested, I highly reccomend coordinating with the Philly Node meetup to start this :)

**Comment by adobley** [comment]
Awesome! I'll reach out to them. I know that LibertyJS has done this before so I plan to see what worked/didn't work when they did it.

**Comment by Mikerob215** [comment]
I'm newish to node, so very interested.

**Comment by adobley** [comment]
@SomeoneWeird I'm sorry to bother you, but could you take a look at this when you have a moment? 

I'm unsure if I should have posted in #258 instead. I understand that team creation has changed a bit, but the readme indicated to create a new issue. I'd love to get started inviting people and organizing.

Thanks!

**Comment by SomeoneWeird** [comment]
@adobley I created a repo + team and invited you. Let me know who else you want in the team as the top is currently not working.

**Comment by adobley** [comment]
Thanks! I'm working on getting a list together while I setup the gh-pages and repo.
