### ISSUE TITLE
Instructions for how to add a new chapter

### ISSUE THREAD

**Issue by maxogden** [nodeschool/organizers#28]
@nodeschool/owners <-- anyone in this team can take care of adding new chapters when they request to be added

Here are examples of open chapter requests at the moment:

- ~~https://github.com/nodeschool/organizers/issues/26~~
- ~~https://github.com/nodeschool/organizers/issues/21~~
- ~~https://github.com/nodeschool/organizers/issues/18~~
- ~~https://github.com/nodeschool/organizers/issues/17~~ 

How to close one of these:

- go to https://github.com/orgs/nodeschool/teams/owners
- add the person who requested to start the chapter to the owners team
- tell them they are an owner and can continue following the instructions here https://github.com/nodeschool/organizers/blob/master/README.md

That's it! The goal of this issue is to give others on the owners team a chance to close requests so that the small few doing it now aren't the only ones doing it

**Comment by martinheidegger** [comment]
This system has changed. And the instructions should be rewritten to reflect it. Would love if someone could open a new one!
