### ISSUE TITLE
Lessons Menu gets stuck...

### ISSUE THREAD

**Issue by tomarone** [nodeschool/organizers#285]
I updated to node 5.0.0 I am running a windows laptop, (it's 8.1)
The first time the menu is OK. (for lessons such as 'learnyounode' etc.)
After a code test and run, the menu gets stuck, the keys up/down do not work
Is there another way to Up/Down the menu? (other than keys ↑↓)
(this is the lesson selection menu white over blue) what module needs to be fixed here?

**Comment by iancrowther** [comment]
I know this is not very helpful, but this is prob the wrong place to post this issuse

check out https://github.com/nodeschool/discussions for support

**Comment by tomarone** [comment]
thanks!
