### ISSUE TITLE
nodeschool bot down?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#296]
@nodeschoolbot help

**Comment by ismnoiet** [comment]
I think something is going wrong i can't add members to  a given chapter
even though i'm the maintainer of that chapter !

**Comment by SomeoneWeird** [comment]
ping @mafintosh

**Comment by iancrowther** [comment]
:-( 

here are some error's

https://github.com/nodeschool/organizers/issues/301#issuecomment-167761768

**Comment by SomeoneWeird** [comment]
dammit. that's annoying. ping @mafintosh :)
