### ISSUE TITLE
call to discuss international day 2016

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/organizers#300]
we have a lot to do for the 2016 international day. it would be great to get a few people together to discuss some of the points on our checklist.

example: define organiser reposonsibilities.

We have this from last year, but were aiming to improve wiht feddback and input.

We also would like to widen the net of organiser engagement, many hands n'all

Any suggestions?

**Comment by PatrickHeneise** [comment]
is there an update on this matter @iancrowther ?

**Comment by iancrowther** [comment]
how about this Monday 21st March at 19:00GMT?

**Comment by martinheidegger** [comment]
NodeSchool International Day was successful, right? @iancrowther can we close this issue?
