### ISSUE TITLE
Correct URL for Belfast #1 event

### ISSUE THREAD

**Issue by gangleri** [nodeschool/organizers#302]
On the events page the URL for the Belfast event is http://nodeschoo.io/belfast it needs to be http://nodeschool.io/belfast

**Comment by iancrowther** [comment]
@SomeoneWeird @maxogden i dont have access to the form to correct this :-(

**Comment by iancrowther** [comment]
@jlord thanks for the access.

@gangleri I have fixed the url for you

**Comment by gangleri** [comment]
@iancrowther Thanks
