### ISSUE TITLE
New chapter for Turin, Italy - looking for other organizers

### ISSUE THREAD

**Issue by edoardo849** [nodeschool/organizers#303]
Hi, I would like to start a nodeschool chapter for Turin, Italy. I am @edoardo849 on twitter and work at DaviomData and Daviom (a finTech company) as a fullStack dev / devOps. I have been using Node.js for 5 months and would like to help others learn as well. Plus, Turin has a very active tech startup community and I think that we could all benefit from a chapter here.

**I am looking for a couple of other organizers in or around the Turin area** interested in the project. As a general idea we could host an event / meeting in a startup incubator (like i3P) or a co-working space (like ToolBox).

**Comment by RichardLitt** [comment]
@edoardo849 I would check out Talent Garden. They might be able to help. I should be there at some point this year or next, too, if you'll still be looking then for help.

**Comment by iancrowther** [comment]
check out https://gitter.im/nodeschool/italy

this moves from city to city in Italy.  It might be a great accelerator

**Comment by jpwesselink** [comment]
Hey @edoardo849, any luck on finding people who want to help you?

**Comment by jpwesselink** [comment]
Heya @edoardo849, how is it going?

**Comment by martinheidegger** [comment]
Since there is no response I am assuming this didn't work out. Closing this issue. If that was prematurely please reopen.
