### ISSUE TITLE
Form of signup to meetup?

### ISSUE THREAD

**Issue by yangwao** [nodeschool/organizers#304]
I'm little bit struggling about this, 
* should I use ti.to or typeform? something else?

* What kind of questions should I ask attendees? 
  I was asking them about 
    * name 
    * food they like to eat
    * coffe preference 
    * knowledge levels
    * define their knowledge by short words
    * where they are comming from
    * operating system of their notebook
    * how did known about meetup 
    * last question if they having some suggestions,

well, any more ?

**Comment by iancrowther** [comment]
you can use whatever suits you and your chapter best.

London uses ti.to

**Comment by iancrowther** [comment]
we just ask for attendees github, twitter and food alergies

**Comment by SomeoneWeird** [comment]
Yeah this is probably entirely up to the chapter organiser, food allergies is probably important if you're serving food. Asking for the OS is another good one, and allows you to prepare a bunch of help if windows users turn up (etc)

**Comment by yangwao** [comment]
food allergies is good, however I lead them to pick food on their own :)

**Comment by iancrowther** [comment]
can this get fed back into the wiki?

https://github.com/nodeschool/organizers/wiki/Checklist-For-Events

**Comment by Jovena** [comment]
On the NY JavaScript meetup page, we ask:
- What is your full name (for security)?
- Which lesson plan will you work on? (This allows our mentors to prepare.)

We also encourage preparation:
_"Install Node.js before arriving. We'll certainly be available to help get Node.js installed if you're having issues, but coming prepared will mean more time for coding!"_

**Comment by iancrowther** [comment]
@yangwao - did we answer your question?

**Comment by yangwao** [comment]
@iancrowther yes, I just wanted know your opinions, thanks for responses, Ill try simplify steps for attendes
