### ISSUE TITLE
Restructuring NodeSchool with NodeSchool Admin

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#309]
# Hello everyone!

This is sort-of a **big deal**. It would be absolutely helpful to my efforts at NodeSchool if you could spare a few minutes and read this Issue and leave a comment.

Alright: Up until now a chapter at nodeschool consisted of a `<chapter-name>.json` in the [nodeschool's website repository](https://github.com/nodeschool/nodeschool.github.io/tree/source/chapters) and events stored in google docs. While this method does/did serve the purpose for displaying the chapters and events on the homepage it poses a few **structural issues** that hinder our progress. Those I am trying to solve.

## Issues
1. **Duplicate data**: A lot of data (like the name) was duplicate.
2. **Unclear ownership**: Since the chapters are hosted in the "global" repo nodeschool.github.io. Usually a second person was required to add/change a chapter (See the [many PR's](https://github.com/nodeschool/nodeschool.github.io/pulls?q=is%3Apr+is%3Aclosed)). This means that the chapter owner didn't had a clear authority over his chapter.
3. **Out-of-Sync**: The organisers array does not often match the repo's team. Note: This is _also_ due to the double effort it takes to maintain both lists.
4. **Missing useful data**: The `<chapter-name>.json` does not contain a lat/lng location to easily point out where it to find it on a map. 
5. **Wrong relationship**: The region is stored with the chapter, however: This adds choice _(and a source of error)_ for whoever creates the chapter and can not be decided apart from the chapters involvement (An owner would need to touch the chapter.json of the chapter to assign it to a different area).
6. **Google Docs pains**: I don't know how often I lost the link to the google docs document to publish events is the only place to maintain. Also, no event is linked to a chapter and the I personally have to look up the lat/long all the time.
7. **Events without timezone**: The events are entered without timezone which means the dates are all wrong. This is a particular issue when trying to organize something like international-day.

## Proposal
My idea is to **change** the way how chapters **sign up** and are **continuosly management** using `conventions` and `tools`:

1. Allowing to simply put a [`chapter.json`](https://github.com/nodeschool/admin/blob/master/lib/util/schema/chapter.js) into the gh-pages branch of a chapter-repo to designate it as a chapter (and list on the homepage) and every change triggers a http://nodeschool.io build with the chapter information. The json file doesn't contain duplicate data.
2. Use the organiser-data directly from a github team with the same name as the chapter instead of the organisers Array to give the chapter owner power & responsibility over the chapter setup. _(This has a few other, nice, side-effects: i.e. we can address the chapter-owners through their github-team)_
3. Like the `chapter.json` have a `events.json` file that contains the [events](https://github.com/nodeschool/admin/blob/master/lib/util/schema/event.js). Additional fields of an event help to place it and to contact the organizer _(keyword: code of conduct)_
4. Move the area-data out of the timezone into a [centralised area lookup](https://github.com/nodeschool/admin/blob/master/country_designations.js) 
5. Creating a lint- and scaffold tool called [nodeschool-admin](https://github.com/nodeschool/admin) that allows to setup the chapter.json easier and automates a few things.

_Note: With this plan, signing up for international-day would be as difficult as just creating a new event that overlaps with the general international-day._

## NodeSchool Admin
If you read this far you already know that [nodeschool-admin](https://github.com/nodeschool/admin) exists. I have written with a few goals in mind:

1. Automate as much as possible
2. Be as verbose as possible (`--loglevel silly` support)
3. Make it a pleasure to work with

And I hope we will be able to continuously improve on those three.

# Next Steps
If you choose to support this issue `+1`'s will do but helping out implementing this would be a lot better! Here is what I imagine the TODO list to be like from now on. _(Since I have some other work on my list regarding the `workshopper` help would be mighty appreciated)_:

 - [ ] Review and finalize the [nodeschool-admin](https://github.com/nodeschool/admin); Particularily [the validation logic](https://github.com/nodeschool/admin/blob/master/lib/util/validate.js)
 - [ ] Create and merge a PR to [nodeschool.github.io](https://github.com/nodeschool/nodeschool.github.io) that adds `require('nodeschool-admin').mode.standard.list()` as a source for chapters.
 - [ ] Add a trigger to [nodeschool-bot](https://github.com/mafintosh/nodeschoolbot) that runs the codeship build of the nodeschool.github.io on every `push webhook`. (_Note: The person hosting nodeschool bot will need my private codeship key_).
 - [ ] Update the documentation on the [wiki](https://github.com/nodeschool/organizers/wiki/New-Chapter-Setup) and the [homepage](http://nodeschool.io/host.html) to include information on the new tool.
 - [ ] Add a tool to nodeschool-admin and/or write a batch script to invite people to teams for their chapters. (hint: nodeschool-bot contains that logic atm.)
 - [ ] Migrate the current chapter.json's to the new format.
 - [ ] Migrate former chapter events to the new format
 - [ ] Extend `nodeschool-admin` for new & awesome features.

What do you think? Is this a reasonable plan? Is it worth working on it? Could you spare some time to support this? Hints on how to implement this better?

Please let me know!
_(If you are generally fine with this plan but have issues with the implementation of nodeschool-admin it should be talked about in a [new issue](https://github.com/nodeschool/admin/issues/new) on nodeschool-admin)_

**Comment by fforres** [comment]
:+1: I like the idea :D
And i think this type of platform would be a nice addition, count me in :+1:

**Comment by tzmanics** [comment]
:+1: Excited about the event changes & would like to help out if this moves forward

**Comment by PatrickHeneise** [comment]
:+1:

**Comment by danywalls** [comment]
great!

**Comment by iancrowther** [comment]
+1 +1 +1

Especially for international day

**Comment by ismnoiet** [comment]
Agreed 1000%.

**Comment by SomeoneWeird** [comment]
Mostly +1 on this

**Comment by maxogden** [comment]
Sounds great. I even think we should think about generalization it beyond `nodeschool-bot` and `nodeschool-admin` and calling them e.g. `openorg-bot` and `openorg-admin`, and brand them under the http://openopensource.org/ project

**Comment by martinheidegger** [comment]
@maxogden Great minds think alike but I would like to have it first tested "in production"

**Comment by lvivier** [comment]
:+1: I dig it!

**Comment by lisposter** [comment]
:+1:

**Comment by dominhhai** [comment]
:+1

**Comment by bnb** [comment]
+infinity. I really want to help out with this. @martinheidegger is there a faster/better way to talk about it all? Gitter, Slack, Twitter?

**Comment by fforres** [comment]
@bnb 
I think using the repo issues it's the primary communication channel.
But... We also have a brand new [gitter channel](https://gitter.im/nodeschool/admin)

**Comment by martinheidegger** [comment]
Update: @fforres and @dinodsaurus are co-maintainers of `nodeschool-admin` now and we are working as transparent as possible using github issues & PR's. I also joined the gitter channel - so I guess its "official" :smile:

**Comment by gaboesquivel** [comment]
:+1:

**Comment by marinintim** [comment]
:+1:

Is there any particular issue to work on?

**Comment by martinheidegger** [comment]
@marinintim Sure, lotsa issues. gitter?

**Comment by marinintim** [comment]
@martinheidegger nodeschool/organizers gitter or nodeschool/admin one? anyway, I'll return after few hours and would check both (if I have access to).

**Comment by riyadhalnur** [comment]
I'm good with the plan

**Comment by martinheidegger** [comment]
Closing this issue do to lack of resources.

**Comment by dinodsaurus** [comment]
I think I can take over the completion of `nodeschool-admin`over the next month or two. What are your thoughts on that @martinheidegger

**Comment by martinheidegger** [comment]
@dinodsaurus I think i nevers stopped you from doing it :) Initiative welcome.
