### ISSUE TITLE
What about creating a specific rule for creating social media groups and accounts ?

### ISSUE THREAD

**Issue by ismnoiet** [nodeschool/organizers#316]
Before starting, Hi, hope you are doing good.

Any way what do you think(organizers and chapter maintainers ) about respecting a specific format when creating chapters accounts for Twitter, Facebook and the rest of the other platforms.
A format that we discuss  and respect to solve this issue. 
Here are 4 propositions  :
 
- [x] nodeschool_chapterName, for example ``nodeschool_london``
- [ ] nodeschoolchapterName, for example ``nodeschoollondon``
- [x] nodeschool_chapterName(some characters), for example ``nodeschool_lnd``
- [ ] nodeschoolchapterName(some characters), for example ``nodeschoollnd``

And any other format that you can come up with and you find it consistent and easy to remember.
Because the existing twitter accounts for example i found that for **london chapter** they are using 
the format [@nodeschool_ldn](https://twitter.com/nodeschool_ldn) Whereas for **berlin chapter** they are using [@nodeschoolbln](https://twitter.com/nodeschoolbln)  which is **GOOD** but not **UNIFORM** and may be there are other formats used by the other chapters. this is something that disturbs us as human being , because we generally and most of the time tend to remember and learn things that respect a certain logic so we can automate it in our minds .

I'm waiting for any suggestion or improvements and Thank you for you time.

**Comment by iancrowther** [comment]
I'll be honest, I'm not understanding the issue?

Chapters are unique entities with their own character, style and tone. I dont really see the value on trying to enforce a rule here?

If you can really explain the value, you may get some real engagement, but even then, only a % coverage

Also, without a governing body, who would enforce it? What would be the consequence??

**Comment by ismnoiet** [comment]
Yes @iancrowther  without a governing body no one can enforce it and even if there is a governing body it is hard to respect and enforce it.
The consequence of not using such a rule is that we end up with tones of chapter names and abbreviations in the long run, which is kind of a confusing especially if they are not in the same flow(for example starts with the prefix nodeschool or ns instead).
Again it is hard to respect such a thing as you've said before,But we can at least **suggest to new chapters organizers to follow  a specific format** in the wiki page :).

**Comment by iancrowther** [comment]
i think a suggested pattern is fair enough, nothing more than that should be attempted.  there are better way to spend your energy.
