### ISSUE TITLE
DNS entry for github teams.

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#318]
To fix https://github.com/nodeschool/admin/issues/18 I wrote a [small server](https://github.com/martinheidegger/open-github-teams) that publicly shows the github teams. It is now running on my server with the IP 81.95.5.101. It would be nice if whoever-has-access-to-the-dns (note: there should be a github team for those people) could add it as an A entry. 

CC: @maxogden @rvagg

**Comment by SomeoneWeird** [comment]
Pretty sure domain is managed by @brianloveswords 

Also, SSL isn't working on latest chrome, unsupported ciphers probably?

**Comment by martinheidegger** [comment]
@SomeoneWeird I can setup the ssl only after the A entry is added :-)

**Comment by SomeoneWeird** [comment]
Should probably disable SSL redirect then, so we can actually see what it looks like :P

**Comment by martinheidegger** [comment]
Would love to, unfortunately i ran in a hard bug of `auto-sni` will fix the server :sweat: but it would help if @brianloveswords could setup the DNS.

**Comment by brianloveswords** [comment]
Ah, I will look into this tonight!

**Comment by brianloveswords** [comment]
@martinheidegger what do you want the A record to be? `team.nodeschool.io` ?

**Comment by martinheidegger** [comment]
Teams.nodeschool.io

**Comment by martinheidegger** [comment]
@brianloveswords Oh! I saw that team.nodeschool.io already works! Thanks!

**Comment by brianloveswords** [comment]
I can switch it to `teams.nodeschool.io` no problem, or have both, let me know what your preference is

**Comment by martinheidegger** [comment]
No need: I am all good! :smile:
