### ISSUE TITLE
Foundation Hiring: Education Community Manager

### ISSUE THREAD

**Issue by feross** [nodeschool/organizers#319]
*Cross-posting from https://github.com/nodejs/TSC/issues/46.*

The Node.js Foundation is looking to hire an Education Community Manager. If you are interested in the position please email mikeal.rogers@linuxfoundation.org with your resume ASAP :)

The role is a contract position.

### Requirements
- Available for part time contract employment (1099)
- Familiarity with existing Node.js education communities.

### Responsibilities

- Subject matter expert on Node.js development with familiarity w/ existing Node.js education.
  - Is the point of contact for the Node.js Foundation's e-learning, training and certification teams.
  - This means approving Marketing materials regarding our education efforts.
  - This means be a point of contact for questions and signoff for Public Relations related to education.
  - This means being present at certain events as the foundation’s education representative.
- Collecting and exposing community resources.
- Participates in the NodeSchool community.
- Participates in the Documentation WGs.
- Coordinating with for-profit Node.js education providers.
- Leading a University Committee.

**Comment by feross** [comment]
Would be great to have folks who are already heavily involved in Node School to apply for the position!

**Comment by iancrowther** [comment]
@feross what is the closing date?

**Comment by feross** [comment]
@iancrowther There's no set closing date. But the Board wants to fill the position ASAP so those who are interested should apply soon!

**Comment by mikeal** [comment]
if you don't send me your resume this week you're unlikely to make it in :)

**Comment by simonv3** [comment]
US based? I was thinking of sending this to some people I know in Europe who'd likely be interested.

**Comment by mikeal** [comment]
There are no location requirements, everyone is remote.

**Comment by simonv3** [comment]
@mikeal cool! will pass it along :)

**Comment by SomeoneWeird** [comment]
This is fantastic, if I wasn't already so busy working I'd totally apply. :tada:

**Comment by fforres** [comment]
Looks awesome! :+1:  :tada:

**Comment by iancrowther** [comment]
will be announcing this at LNUG this wednesday

**Comment by martinheidegger** [comment]
As far as I know the community manager was hired. Closing this issue

**Comment by SomeoneWeird** [comment]
Is it public knowledge who it is yet?

**Comment by martinheidegger** [comment]
I don't, but I do hope that she/he will make herself/himself known.

**Comment by mikeal** [comment]
Press release will go out soon ;)
