### ISSUE TITLE
Node.js in Amsterdam?

### ISSUE THREAD

**Issue by Lisastamm** [nodeschool/organizers#323]
Hi guys! I am situated in Amsterdam and was wondering if there is anyone interested in Node.js in the Netherlands.. I am working on organizing an evening with Node.js and would be cool to do a collaboration of some sort :)

**Comment by SomeoneWeird** [comment]
@nodeschool/amsterdam

**Comment by Lisastamm** [comment]
Thanks! Unfortunately I get a 404. But found something on meetup that might do the trick :) Nonetheless, would be cool to actually connect with someone. Let me know if someone would be interested!

**Comment by SomeoneWeird** [comment]
Ah, yeah, it's a github team, you won't be able to see it because you're not part of the organisation. Hopefully one of those folk can chime in :)

**Comment by yoshuawuyts** [comment]
@Lisastamm could you perhaps share some more details? e.g. 
- What topics / format do you have in mind?
- Who's your intended audience?
- What has been arranged so far / what do you need help with?

By sharing this information I reckon there's a bigger chance that people lurking the thread will step forward - Cheers!

**Comment by Lisastamm** [comment]
Hi Yoshua! Yes of course :)

The idea is some sort of happy hour sprinkled with code, if you wil. I found a bar who wants to host this for free in Amsterdam (called Noorderlicht cafe). I want to do a beer and do 4 challenges with Node.js. These challenges all take appx. 20 minutes each. Of course the event is not about being the best, or being super professional. The objective is to connect the Node.js-ers we have in the Netherlands and bring them together, while having a beer. Share knowledge. Maybe find someone who's done a project with Node.js and wants to share his/her project during the event.

I am looking for someone who wants to co-host this with me. The format is discussable. I mean, I have an idea of it now, but this of course can change :) Would be cool to do it together, I am just alone in Amsterdam haha

Let me know if anyone is interested either to co-host or join the evening. Would be cool to connect!

**Comment by rickheere** [comment]
Hi @Lisastamm, that sounds like a lot of fun. I'm one of the organizers of NodeSchool Haarlem (Haarlem is a couple of minutes from Amsterdam by train). In Haarlem we have a meeting every 2 weeks, see: http://www.meetup.com/Nodeschool-Haarlem/. 

It happens to be that we are looking into "expanding" to Amsterdam as well. It sounds like we can help each other out :)

Would you like to come over the one of our meetings? The next one is coming Thursday.

**Comment by Lisastamm** [comment]
Awesome! I RVSP-ed and will send you a private message in Meetup :)

**Comment by rickheere** [comment]
Great. Looking forward to meeting you.
