### ISSUE TITLE
Add chapter & hexagon of Bratislava

### ISSUE THREAD

**Issue by yangwao** [nodeschool/organizers#330]
I would like 
- [x] add chapter http://nodeschool.io/bratislava/ to http://nodeschool.io/chapters.html 
- [x] add hexagon from https://github.com/nodeschool/bratislava/tree/master/assets/logo to http://nodeschool.io/hexdex.html

I could'nt find some guidelines, is it manual?

**Comment by yangwao** [comment]
oh, I will do PR

**Comment by yangwao** [comment]
PR https://github.com/nodeschool/nodeschool.github.io/pull/483

**Comment by martinheidegger** [comment]
Done :+1:
