### ISSUE TITLE
Knock knock nodeschool/core 🐷

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/organizers#331]
May I join you? My qualifications are as follows:
* running multiple nodeschool events
* submitting patches to lessons
* triaging & closing a zillion "I'm stuck" issues
* nodeschool international day + sweet shirts
* evangelizing nodeschool at events (people at fluentconf kept assuming I worked for some company called "nodeschool" because of my shirt :stuck_out_tongue:)

lmk :dizzy:

**Comment by martinheidegger** [comment]
Your contributions are awesome! I see no issue with adding you as a @nodeschool/core member so I added you!

**Comment by Sequoia** [comment]
:raised_hands:

**Comment by a0viedo** [comment]
about time! sorry for not bringing this up until now :tada: :tada:
