### ISSUE TITLE
New Chapter for Hermosillo, México

### ISSUE THREAD

**Issue by dayrachiu** [nodeschool/organizers#332]
Hi, I would like to start a nodeschool chapter for Hermosillo. I'm @Dayrachiu on Twitter and I've worked with several dev communities including @WomenWhoCode. I will be co-organizing this chapter with @jrsalgado, @keogh, and @abrahamhinojo, we work at @nearsoft and Node.js is one of the technologies we use more in the company, we want to learn more and we would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hi @dayrachiu! Awesome that you want to take care of it!
I setup the team and repo for the Hermosillo and invited you and the other team members. Welcome to the team!

**Comment by dayrachiu** [comment]
Thank you @martinheidegger !! Happy to being part of nodeschool team! :)
