### ISSUE TITLE
Chapter for Bangkok

### ISSUE THREAD

**Issue by jjmax75** [nodeschool/organizers#333]
Hi,

I'm interested in getting involved with the Nodeschool Bangkok chapter but it doesn't seem to be being maintained. It looks like it was setup a year ago with no work done on it since then.

Is there a way to be added as a maintainer?

Thanks,
Sean

**Comment by martinheidegger** [comment]
Hello @jjmax75 Awesome that you want to get involved, It shouldn't be a problem at all but I would like to give @RichardLitt (original bangkok chapter maintainer) an option to voice in ^^

**Comment by RichardLitt** [comment]
Whoa, I barely remember trying to set this up when I was there. I wasn't able to find the time, and I haven't been back recently. @jjmax75, take it over!

**Comment by jjmax75** [comment]
Thanks guys

**Comment by martinheidegger** [comment]
You have been added! Cheers and good luck!

**Comment by RichardLitt** [comment]
Good luck! :D
