### ISSUE TITLE
How do I create my page for my created chapter

### ISSUE THREAD

**Issue by raheelkhokhar** [nodeschool/organizers#334]
Hello guys. I have created a Chapter for Islamabad Pakistan, its initial link is:
https://github.com/nodeschool/islamabad

But when I go in chapters section, I do not see Islamabad Chapter here:
http://nodeschool.io/chapters.html

Please help me, how can I make my chapter show on chapters page?
Thanks in advance.

**Comment by a0viedo** [comment]
hey @raheelkhokhar, for your chapter to appear at http://nodeschool.io/chapters.html you need to follow [step 3](https://github.com/nodeschool/organizers#3) of the README.md. Let me know if you get stuck with something.

**Comment by raheelkhokhar** [comment]
Oh thanks @a0viedo, I just followed the steps and created a file up there in repo. I think they'll approve it and I'll have to wait for it. Thanks for your reply. It was helpful.

**Comment by raheelkhokhar** [comment]
Don't know what is left. 

- I have already created json file for the chapter named "Islamabad.json" at https://github.com/nodeschool/nodeschool.github.io/tree/source/chapters

- And also created a pull request.

Am I waiting for my changes to be merged by admin? Please guide.
