### ISSUE TITLE
New Chapter for Panama City, Panama

### ISSUE THREAD

**Issue by ytzvan** [nodeschool/organizers#335]
Hi, I would like to start a nodeschool chapter for Panama city, Panama. I am @ytzvan on twitter and I'm the organizer of PanamaJS meetups . I will be co-organizing this chapter with Gabo Esquivel (Organizer of Nodeschool CR). I have been using Node.js for 3 years and would like to help other developers start their path in Javascript programming using node. I hope you guys guide me with the organization of our first nodeschool in the country.

Thanks.

**Comment by a0viedo** [comment]
hola @ytzvan! It's great that you want to start a new chapter. I've created the repo, the team and invited both of you to join. 
Welcome to Nodeschool! If you want to read on previous events and recommendations there's a long thread on https://github.com/nodeschool/discussions/issues/93. Let me know if I can help you with anything.

**Comment by gaboesquivel** [comment]
yay!  :+1:  :100:

**Comment by martinheidegger** [comment]
@ytzvan Welcome and good luck in Panama. Please close the issue if its not needed anymore.

**Comment by martinheidegger** [comment]
Closing the issue. Please reopen if necessary
