### ISSUE TITLE
Unable to add members to team

### ISSUE THREAD

**Issue by llkats** [nodeschool/organizers#336]
Hi, it seems as if we are unable to use @nodeschoolbot to add members to our team. The `sanfrancisco` team appears to exist, but the bot does not work. See https://github.com/nodeschool/sanfrancisco/issues/111 and https://github.com/nodeschool/sanfrancisco/issues/131. Thanks for the help.

**Comment by a0viedo** [comment]
hey @llkats, found the issue https://github.com/mafintosh/nodeschoolbot/pull/6. @maxogden do you have commit access?

**Comment by martinheidegger** [comment]
https://github.com/mafintosh/nodeschoolbot/pull/6 is merged and deployed. now it should work @llkats
