### ISSUE TITLE
New chapter request for Vellore, Tamil Nadu, India

### ISSUE THREAD

**Issue by Nikhil-Kasukurthi** [nodeschool/organizers#338]
Hi, I would like to start a new Node School chapter here at Vellore. I am a student at the VIT University, Vellore. It is the of the most prominent universities in India. I will be co-organizing events with the help of the local Google Developer Group, GDG - VIT of which I am an organizer. Students here at VIT would love to learn NodeJS. I myself have been using NodeJS for the 3 months and want others to start on this path as well. Hope you guide me with the way for starting the Node School. 

Thanks.

**Comment by martinheidegger** [comment]
Hello @Nikhil-Kasukurthi Awesome! Generally there is no issue. Is it okay to name it "vellore"?

**Comment by Nikhil-Kasukurthi** [comment]
Sure! @martinheidegger

**Comment by martinheidegger** [comment]
@Nikhil-Kasukurthi I setup the team & repo for Vellore and sent you an invitation to the teams. Did you receive them?

**Comment by Nikhil-Kasukurthi** [comment]
Yes @martinheidegger. I accepted the invitation. Thanks!

**Comment by martinheidegger** [comment]
Alright, now that you are an organiser: please keep things clean and close issues :smile: (Oh: and welcome! Let us know if you need something)

**Comment by Nikhil-Kasukurthi** [comment]
Thanks a lot for the help! Looking forward to working with the community.
