### ISSUE TITLE
New Chapter Request for UC San Diego

### ISSUE THREAD

**Issue by joelseq** [nodeschool/organizers#339]
Hi, I'm Joel Sequeira and I would like to start a NodeSchool chapter for my university and surrounding area. I study at University of California San Diego located in La Jolla, San Diego. I am @joelseq96 on twitter and I am also looking for people who are working in the industry or are experienced in Node to help with organizing the events. I have been using Nodejs for around 4 months and I want to promote web development in my university as well as help others learn Nodejs. I would like the chapter to be called UC San Diego.

**Comment by RichardLitt** [comment]
I think this could just be called San Diego? Are you planning to limit it to only UC members?

**Comment by joelseq** [comment]
@RichardLitt in the long term, no. But for the first 2 or 3 going to try making it only UCSD students just to see how it goes and get us time to get sponsors etc. Also since San Diego is pretty huge thought it can help narrow down the geographic location by just saying near UC San Diego

**Comment by martinheidegger** [comment]
@joelseq If the general public "isnt invited" then nodeschool seems like an overhead for you?! :question:

**Comment by joelseq** [comment]
Alright so I think I can set it up as NodeSchool San Diego :)

**Comment by martinheidegger** [comment]
@joelseq Alright, I created a sandiego repo and teman have invited you to the San Diego chapter. Are you okay now? Let us know if you need further help.

**Comment by joelseq** [comment]
@martinheidegger yep it all seems good! :) And I will definitely message on the gitter channel if I need help with anything. Great job with NodeSchool btw!
