### ISSUE TITLE
Free/cheap workshop or training for Node.js beginner?

### ISSUE THREAD

**Issue by JMGodart** [nodeschool/organizers#340]
Hello,
As a university researcher, involved in the development of a mobile application, I am looking for some free (or at least reasonably-priced) intensive training/course about Node.js. I prefer some "live" training/course, rather than an online course. Does some chapter organize such a training/course in the coming months? I can travel to most places in Europe, and possibly outside of Europe, for a training of at least a few days.
Thanks!
Best regards,
    Jean-Marc

**Comment by riyadhalnur** [comment]
Hey Jean-Marc,

You can check out the [Events](http://nodeschool.io/events.html) page here and check for upcoming meetups near you.

Cheers,
Riyadh
