### ISSUE TITLE
Chicago Chapter

### ISSUE THREAD

**Issue by ddaza** [nodeschool/organizers#341]
I'm interested in getting involved with the [Chicago Chapter](https://github.com/nodeschool/chicago). It looks like it was setup but hasn't had any activity for a long time.

Is there a way to be added as a maintainer?

Thanks!

**Comment by martinheidegger** [comment]
Hello @ddaza I think it should be no problem to add you as a maintainer. However I want to make sure that @azizali has the chance to voice in. @azizali : What do you think?

**Comment by azizali** [comment]
Node school is an open concept and I encourage all the help we can get.
@ddaza, I am all for having you involved and organize an event

**Comment by martinheidegger** [comment]
@azizali Thank you for your support. I invited @ddaza to the chicago team and as a chapter maintainer.
@ddaza Let us know if you need some help & please close the issue if you are all set-up.
