### ISSUE TITLE
Permission denied for bangalore chapter updates even after being a co-organizer

### ISSUE THREAD

**Issue by somsharan** [nodeschool/organizers#342]
unable to update the files for the chapter for which i am co-organizer.

**Comment by martinheidegger** [comment]
I can not find you in the [teams](http://team.nodeschool.io) What chapter have been added to? Did you accept the invitation on github?

**Comment by somsharan** [comment]
I am in [bangalore](https://github.com/nodeschool/bangalore) chapter and i am not sure of the invitation on github and bangalore team is not listed in above link.

**Comment by martinheidegger** [comment]
It seems you might have missed that [NodeSchool got deleted and then un-deleted](https://github.com/nodeschool/organizers/issues/248) as a result many people had to be readded as members and [teams were lost in the process](nodeschool). I have recreated the bangalore team and resent an invitation to you. You should  be able to edit the chapter repo again. Can you confirm this and check if you are able to edit the repo?

**Comment by somsharan** [comment]
Martin thanks for helping out, was able to update the repo. And can u please update the owner of the repo also if possible ;)

**Comment by martinheidegger** [comment]
I invited both @somesh123 and @abyv. Can I help you with something else?

**Comment by somsharan** [comment]
Thank you so much for the help :+1:
