### ISSUE TITLE
Private repository for private inquiries

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#343]
Since we have [email](https://github.com/nodeschool/email) I thought it would be mighty awesome if we could connect a `private@nodeschool.io` _(or similar)_ account using ifttt to create github issues that people can answer to. For this to work we would need to upgrade the organization to have private repositories. Do you think that is a good idea? Could someone sponsor the private github-account fee?

**Comment by iancrowther** [comment]
not sure i'm understanding the need? what's broken?

**Comment by martinheidegger** [comment]
Lost interest.
