### ISSUE TITLE
NodeSchool - Malang, ID chapter (UNIRA Malang, Indonesia)

### ISSUE THREAD

**Issue by krahman** [nodeschool/organizers#346]
Another [Malang NodeSchool](http://nodeschool.io/malang/) event will be held on [April 25 - 26, 2016](http://nodeschool.io/events.html).
This event will be hosted and sponsored by [Universitas Raden Rahmat Malang](http://uniradenrahmat.ac.id/), situated at UNIRA campus.
The main goals are to promote NodeJS to local UNIRA students and to spread it across the local community.
For any question and clarification, please open a [New Issue here](https://github.com/nodeschool/malang/issues).

**Comment by martinheidegger** [comment]
Congratulations on your event. I hope its okay to close this issue.

**Comment by krahman** [comment]
sure @martinheidegger, the event was great. Thank you.
