### ISSUE TITLE
Chandigarh, India Chapter

### ISSUE THREAD

**Issue by sachinbhatnagar** [nodeschool/organizers#347]
The Chandigarh, India chapter (http://nodeschool.io/chandigarh) seems to be dormant and doesn't offer anything useful. I would like to take charge of the same. Is there such a provision?

**Comment by iancrowther** [comment]
Indeed there is.

Step 1. Contact the existing Chandigarh team (https://twitter.com/nodeschoolchd) and find out if they are planning to continue, would like help or are happy to pass the baton.

Step 2. Find a fellow organiser, It's MUCH better to operate as a small team.

We need to setup a Chandigarh team regardless, so it would be great if we could get an update here.

Thanks for your interest in the chapter, its looks like it's been well loved.

**Comment by martinheidegger** [comment]
Lets give the current chapter organizer @nsena a chance to voice in. Maybe he is happy to have you join the chapter as organizer?

**Comment by sachinbhatnagar** [comment]
Absolutely. I'll be happy to connect with the organiser. Thanks.
