### ISSUE TITLE
Starting a new Chapter (Delhi-NCR)

### ISSUE THREAD

**Issue by manoj-nama** [nodeschool/organizers#349]
Hi, I would like to start a nodeschool chapter for Delhi-NCR (India). I am [@manoj-nama] on twitter and work at TO THE NEW Digital, Noida as a Fullstack JavaScript developer . I will be co-organizing this chapter with @VibhorKukreja. I have been using Node.js for 3 years and would like to help others learn as well. We already have organized 3 events in the area, but unfortunately the old owner has deleted our  chapter repository.

**Comment by akriti2205** [comment]
Hi manoj, my company Goibibo is interested in hosting a Nodejs event, if you are interested than we can make Nodejs Delhi-NCR chapter, we can provide space for the same. please msg me your email for further details

**Comment by manoj-nama** [comment]
@akriti2205 Surely. We are planning our next event at TO THE NEW Digital, Noida (_4th June 2016_). You are welcome to join us with your folks, and the next one we can plan at your space.

My email address is **manoj.nama@outlook.com**.

**Comment by martinheidegger** [comment]
@kushal-likhi Was the first person to originally create a Delhi chapter [in Oct 2014](https://github.com/kushal-likhi). @vineetdaniel tried to join it in [Nov. 2014](#68) and it is still listed on the NodeSchool homepage. The [chapter.json](https://github.com/kushal-likhi) also references @avin45h @VibhorKukreja @manoj-nama @kashishgupta1990 also as owners. For some reason though [https://github.com/nodeschool/delhi-ncr](https://github.com/nodeschool/delhi-ncr) seems to be gone. A lot of chaos 😅  would be nice if someone would clear that up. If no former owner raises their voice in the next 5 days I think the delhi chapter should be passed on to you.

**Comment by avin45h** [comment]
Clearing this up, Apologies if I offend anyone. The repository was deleted by me and I informed it (along with the reasons ) to the owners of nodeschool as well. The community was growing dead, people not reverting back when pinged and things happening without any timely notifications. People would show up but would never revert back when pinged. Basically we had dud contributors.  As long as @kushal-likhi  was there with us when first event happened, it had the community feel, the ones that followed were merely used for marketings (No offence). I have tried pinging people time to time over phone calls, chats. What my plan is? As I get a bit of break from my current assignment in office, I will join back again, but this time with a better execution strategy and willing contributors. Of course, this does not mean that others cant manage it, just try to keep the community spirit alongwith. 

PS : @manoj-nama You should have at least reverted back to me once, I tried to call you many times.

PPS : @nodeschool, sorry for bringing in these kind of issues here in the forum.

**Comment by avin45h** [comment]
@martinheidegger Just had a word with @kushal-likhi , He is ready to manage things till I am busy with current assignment, Plus he has some nice plans to get the things done in the coming month with nodeschool. If possible, can I get the ownership back again?

**Comment by martinheidegger** [comment]
@nodeschool/core I am a bit overwhelmed here advice would be nice 😅

**Comment by manoj-nama** [comment]
Hey all, i am not at all comfortable with @avin45h being the owner after this incident. Would be great if the owner was @kushal-likhi. We are planning for 4th June so it would be awesome if the repo access is granted ASAP.

**Comment by avin45h** [comment]
@manoj-nama :) thanks. It would have been better if I was contacted at least once. Let's not bring in personal matters over here, the incident was duly informed to @a0viedo and I was in everybody's contact list. A communication would have been nice. Let the community decide in, Just for the info, @kushal-likhi is surely a better option than me, I would love it if he comes in and takes up the ownership. 
As for our private matters, I have no issues in hosting things at TTN, just have the community feel to it. Plus involve the community in it as well, All the blogs and links I saw last time were just purely promotions.

**Comment by manoj-nama** [comment]
@avin45h thanks for the honest reply. You alone are not the community, it is us who have hosted all the nodeschools in the area. You keep talking about the community over and over yet you only pop up when we announce about the upcoming event. You deleting the repo is the most childish act that can be done by a person who is trying to drive a community. And thus i have next to none faith in anyone like that. It would be great if @kushal-likhi was made the owner and we get things in motion as quickly as possible. @martinheideggerr please make @kushal-likhi the owner so we can start spreading the knowledge again. :)

**Comment by avin45h** [comment]
Sigh! Let's not bring it in here. Let's keep it clean.

@nodeschool/core Please help us out on this.

**Comment by martinheidegger** [comment]
Note that: Even before we can sort this out: you can still organize events and add it on the event part of the homepage.

**Comment by Sequoia** [comment]
## Summary
**repos are cheap**. If one's taken, start a different one. If it's not taken & someone requests it, give it to them. If you don't like how someone else is running a group, start your own group! :)

If the `nodeschool/delhi-ncr` repo was **nonexistent** when @manoj-nama, he should have it created for him as a simple procedural matter. I (and I will venture this reflects the views of most of `nodeschool/core`) have no interest in deciding who's "entitled" to a repo-- we're here to create them upon request, not to resolve ownership disputes 👍 

## Longer blathering

My view: A "nodeschool chapter" is...
1. a repo under the nodeschool org*
2. the work put into organizing events

Repos are cheap. If someone wants a repo, give 'em a repo! If someone already owns "Nodeschool San Francisco," then join up with them. If you don't like how they run things- no problem! Just start Nodeschool Bay Area or Nodeschool California, or Nodeschool Golden Gate (or whatever) and do things the way you want. This is very much like OSS: if you don't like governance of the current project/org, that's fine: just fork & do your own thing!

Regarding a deleted/re-created repo: if a repo owner deletes a repo, that's a strong indication that they do not want to be part of that particular group anymore & are yielding control of it. If Xian creates `nodeschool/xanadu`, then deletes it, then Bao wants to take it over, Xian has no claim to it anymore & it goes to Bao. We have a saying in the USA: "Move your meat, lose your seat!" 😸 



\* Or not! There's no "requirements" for nodeschool & you can make whatever site/repo/etc. you want 😺

**Comment by Sequoia** [comment]
paging @nodeschool/core: awaiting LGTM/:+1: from another maintainer to move forward with 👆

**Comment by martinheidegger** [comment]
I agree with @Sequoia 's assessment (thank you, @Sequoia, for chiming in). I would like to amend that it is generally not a good idea to have conversation outside of this issues tracker. If a deletion or problem happens it reduces the confusion and gives more clearance to have the discussion archived here.

**Comment by iancrowther** [comment]
"we're here to create them upon request, not to resolve ownership disputes" - so very true!

**Comment by Sequoia** [comment]
[Team](https://github.com/orgs/nodeschool/teams/delhi-ncr) and [repo](https://github.com/nodeschool/delhi-ncr) created, @manoj-nama feel free to add others to the team! Many hands 👉 light work and all that 😸 

@avin45h: I know you had concerns about @nodeschool/delhi-ncr feeling "dead" in the past but it's alive & kicking again. Everyone has a common goal of putting on nodeschool events in Delhi and it looks like there's plenty of interest now! 🎉 👍 💯 All's well that ends well. 😸

**Comment by Sequoia** [comment]
@manoj-nama please close this ticket when you've confirmed that you have what you need here.

**Comment by manoj-nama** [comment]
@Sequoia @nodeschool/core Thanks Guys, we have what we need here now. Let's get to work.
