### ISSUE TITLE
New chapter for Montreal, Canada

### ISSUE THREAD

**Issue by pcuci** [nodeschool/organizers#350]
Hi noders - I'm down to organizing a series of nodeschool workshops in Montreal.

There are a couple javascript meetups I can coordinate with (I myself co-organize the local Meteor meetup), but there is also js-montreal and a freeCodeCamp which are active in the community; about half their audience is newbies (they'll love the core classes) but another good chunk have played with Node before and I'm sure they'll enjoy the more advanced elective topics.

I've been zooming through workshops/adventures and love the format, reminds me a lot of http://swirlstats.com/ that's how I picked up R.

@David-Ro will help me bootstrap, he's a veteran community organizer and polyglot/-math - so that's a team of two here in Montreal, ready to make things happen!

**Comment by David-Ro** [comment]
Yes we'll use other groups to promote nodeschool.

**Comment by martinheidegger** [comment]
Hi @pcuci and @David-Ro Cool that you start working on the Montreal chapter. @riyadhalnur Kind of uncommon to merge the Chapter without creating it. Anyways - I added the Montreal repository and invited the both of you to the teams. I think you should be ready to go? Do you need something more?

**Comment by riyadhalnur** [comment]
@martinheidegger Sorry about that. @pcuci and @David-Ro had a meeting later that day and I merged in the PR before I went to bed. Timezones!

**Comment by pcuci** [comment]
@martinheidegger - I'm not able to push to the nodeschool/montreal repo, which is empty now

Tried both ssh and https for which I got a 403 permissions denied
```
paul@paul-netbook:~/workspace/toronto$ git remote -v
origin	ssh://git@github.com/nodeschool/montreal.git (fetch)
origin	ssh://git@github.com/nodeschool/montreal.git (push)
paul@paul-netbook:~/workspace/toronto$ git push origin master
ERROR: Permission to nodeschool/montreal.git denied to pcuci.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

![image](https://cloud.githubusercontent.com/assets/2169849/14932267/c04c5a5c-0e41-11e6-9501-a693c1b80edd.png)

Not sure what I'm asked to wait for here...

Thx!

**Comment by pcuci** [comment]
@martinheidegger - it might be easier to directly fork the http://github.com/nodeschool/toronto repo into montreal :smile:, it'll show the fork publicly I think

**Comment by martinheidegger** [comment]
@pcuci Oops, forgot to add the repo. Now added, does it work?

**Comment by pcuci** [comment]
Thanks @martinheidegger - all good now: http://nodeschool.io/montreal/ :smile: :+1:

**Comment by pcuci** [comment]
Thanks @martinheidegger - all good now: http://nodeschool.io/montreal/ :smile: :+1:
