### ISSUE TITLE
Starting Node School Chapter in Kikinda, Serbia

### ISSUE THREAD

**Issue by filipboskov** [nodeschool/organizers#351]
Hello, I would like to start Node School for Kikinda, Serbia. My name is Filip Boskov here's my facebook address https://www.facebook.com/FilipBoskov . I will be organizing this event with Marko Kazic @marxo, Ivan Zivankic and Igor Kovacevic. I don't have any previous Node experience, but I would like to learn it soon.

**Comment by marxo** [comment]
:+1: Hey guys, let us know if we can proceed with the chapter registration. We're looking forward to 21st and International day.

**Comment by Sequoia** [comment]
🎉  Awesome!

## Questions:
1. What name do you want for the repo? Typically it's just a place name (`western-mass`, `nyc`, `berlin`, `argentina` etc.)

That's about it!

**Comment by Sequoia** [comment]
One more question: are there other chapter(s) in your city/region currently?

**Comment by marxo** [comment]
@Sequoia Nope, there's only Belgrade chapter, which is ran by our good friends, but in a different city. The name could be `kikinda` it's the name of the city.

Thanks for the response :tada:

**Comment by Sequoia** [comment]
@marxo @filipboskov YW! Please close this ticket when you've verified that you have what you need. 👍

**Comment by marxo** [comment]
Submitted PR to nodeschool/nodeschool.github.io/pull/500, merged. Will be closing issue today if there's nothing else to do for the init.
