### ISSUE TITLE
NodeSchool Greece / Crete

### ISSUE THREAD

**Issue by kabitakis** [nodeschool/organizers#352]
We, a non-profit community we call Devstaff (https://devstaff.gr), would like to start a NodeSchool in Greece or in Crete (region) more specifically. We've already hosted a Node.js event in the past (https://github.com/devstaff-crete/meetup02-NodeJS). Mentors etc. will be announced soon, but I'd like to set things up in advance. Would be great to have a repo here for that.

Thanks

**Comment by jpwesselink** [comment]
Welcome Nikos. Do know any other organizers to help you with setting up your chapter?

**Comment by jpwesselink** [comment]
ping @kabitakis

**Comment by kabitakis** [comment]
Hi @jpwesselink! No, I don't know anyone else around.

**Comment by finnp** [comment]
@kabitakis This is is already a bit older, but I would love to see a NodeSchool happening in Crete. Are you still interested in setting this up?

**Comment by jpwesselink** [comment]
@markpapadakis

**Comment by riyadhalnur** [comment]
Hi @kabitakis, any luck in finding people to help you out?

**Comment by martinheidegger** [comment]
I assume he didn't have any luck, so I am closing this issue. If this is prematurely feel free to reopen it.
