### ISSUE TITLE
Need to edit the Nodeschool/Delhi-NCR Event

### ISSUE THREAD

**Issue by manoj-nama** [nodeschool/organizers#353]
Hey guys,

I need to edit the event for our Delhi-NCR chapter as we are to postpone the event by a month, and also our repo was renamed, consequently people are landing at a 404 page.

**Comment by martinheidegger** [comment]
@manoj-nama After adding an event you should have been presented with an "edit" link. It is good practice to store that link. In any case: I removed the Delhi event from the events list. Please create it again once you have a new date. Cheers!

**Comment by manoj-nama** [comment]
Thanks @martinheidegger. Yeah I lost the edit link, will store it safely next time around.
