### ISSUE TITLE
New Chapter: Zürich, CH

### ISSUE THREAD

**Issue by philj0st** [nodeschool/organizers#362]
Yo! I'm Phil I've been using JS for about 2 years now and I have experience in teaching beginners to code. I saw this whole nodeschool chapter thing going on while coding in NY @recursecenter. Now as you might have guessed I would like to start a chapter in Switzerland!

Looking for co-organizers. Hit me up if you wanna meet and talk about this.

**Comment by jpwesselink** [comment]
Have you considered visiting the OpenTechSchool meetup in Zürich? Maybe there you can find people who'd like to help you organize your NodeSchool chapter. http://www.meetup.com/opentechschool-zurich

**Comment by philj0st** [comment]
I haven't .. thanks for the good Idea @jpwesselink, I'll do that asap.

**Comment by jpwesselink** [comment]
Good luck! If that doesn't work we'll figure out something else

**Comment by jpwesselink** [comment]
@philj0st Any luck?

**Comment by philj0st** [comment]
I'm out of town right now but i will try asap

**Comment by jpwesselink** [comment]
I'll try to find people from your area as well.

**Comment by riyadhalnur** [comment]
Hi @philj0st, any luck in finding people to help you out?

**Comment by martinheidegger** [comment]
Since there is no response I am assuming that this didn't work out. Closing this issue for now. Please reopen if that was prematurely.
