### ISSUE TITLE
Money, money, money ... aka. Bountysource

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#369]
Hello @nodeschool/core !
I have just maintained the admin rights to https://www.bountysource.com/teams/nodeschool Which is a team at Bountysource that allows crowdfunding for open source. I thought it might be neat to have that option. It is a donation based system for all our efforts. For this I wondered following:

1. Should we promote/use this?
2. Who wants to be admin? (only `core` members please)
3. Do we want to offer advertising on the nodeschool like:

![](https://i.gyazo.com/592f687c25529d95c303e7ecfe4a5d15.png)

4. Should our first goal be 100 USD for a monthly newsletter?
5. What do you think of this?

**Comment by Sequoia** [comment]
What's the money for? Would be great to pay someone ("paid intern") evaluate/update existing nodeschool lessons but that's pretty tedious and skilled work . . .

What's the thing you're interested in spending money on in the project, and who do you see it coming from?

Personally I'd go for the "corporate sponsorship of a lesson"/adopt-a-lesson model-- exchange logo rights for SLA saying that company will respond to questions & fix bugs within 30 days.

**Comment by SomeoneWeird** [comment]
I think this could work, but needs to be done very transparently with clear intentions.

**Comment by llkats** [comment]
My immediate thought was this could perhaps be used to get major issues with workshoppers taken care of, as @Sequoia alluded to, as many workshoppers are showing their age and general neglect.

Anything involving money, though, can be potentially very tricky. I'd be very careful involving the entire org with money matters.

Has there been a need for a monthly newsletter? I must've missed the convo. What would the content of the newsletter entail?

**Comment by timoxley** [comment]
> many workshoppers are showing their age and general neglect.

I'm guilty.

Money isn't really the issue though, the issue is more motivating volunteers to invest time into the workshoppers.

**Comment by martinheidegger** [comment]
> What's the money for?

I can think of various things: i.e.
 - Cutting the International Day video (@iancrowther paid it on his own dime!)
 - Stickers for events
 - Rewards for fixing bugs at the website or workshoppers
 - Travel expenses for mentors to important NodeSchool events (with 100+ attendees)
 - Hosting of NodeSchool-bot and NodeSchool-team server (this one is still not in active use)
 - In case it becomes an issue for [email](https://github.com/nodeschool/email): http://www.mailgun.com
 - _(My vanity strikes here: Maybe T-Shirts for the chapter-organizers?)_

In short: I think it should be used to:

 1. Improve the quality of the available information / curriculum
 2. Improve the quality of NodeSchool events

> done very transparently with clear intentions

The money that moves on BountySource is as transparent as I can imagine things. After a `salt` happened the team, the team receives money. It is able to "pay out" that money or set bounties on github issues. We could make it a habit to never "pay out" the money and rather allocate it on bounties. This way:

- All the received money would be listed by source.
- All the spent money spent on issues, would contain a public record of "for what" and "how much" (example: https://www.bountysource.com/issues/1563162-include-the-vim-breakindent-patch)

> Who do you see it coming from?

Bountysource has a new feature called `Salt` where individuals or companies can crowdsource:
https://salt.bountysource.com/teams/nodeschool
I personally don't mind spending 5$ a month... for a start. Probably there are people likeminded. Aside from that, as mentioned before. Maybe companies like to support this for advertising (NodeSource, whatnot,...). I am not sure if the "receipt" from BountySource can be taken as a deductible bill, might be interesting for corporations.

> Has there been a need for a monthly newsletter?

I do not know how many people signed up for the Newsletter but last I checked the number was in the 1000s. Things I imagine people would love to know:

 - New things about Node (worth to tell people at events)
 - New Workshoppers at NodeSchool
 - Introduction of NodeSchool members
 - Updates to the NodeSchool processes (if there are any)
 - Promotion of the work done by NodeSchool members (i.e. new hexdec logos)
 - Reminders about global events (i.e. NodeSchool international day)

The conversation about newsletters happened [in the newsletter repo](https://github.com/nodeschool/newsletter/issues). 

> Money isn't the real issue

Thats true, it is not. But we **do** have several issue that could maybe be solved with money, so: I wonder: why not? For example:  I would love if some of the translation could be automated for example. Because: while translation has been an awesome boost but Its existence is a speed-limit to improvements. [Gengo](https://gengo.com/) (a paid service) could make it smoother. Another thought is there are some things that organizers fight with, and if they invest their time I think it would be good to have the possibility for a reward. (@timoxley: #370)

>  "corporate sponsorship of a lesson"/adopt-a-lesson

I do not have an issue with that model but I think it should not be part of the organization to offer that: Writing a workshopper is hard work and `npm`, `github` and other companies have paid their staff to work on it (I hope so at least). The mere existence of the workshoppers they create is awesome for node as a community. We could put a button on the homepage thought to offer companies to get contacts if they want "us" to write a workshopper for their product. But the actual deed should, imho, be done without ties to the org. _(If you want to discuss this further, please open a separate issue)_

There have been other issues about money:
 - [Nonprofit/5013c support for Renting Space?](https://github.com/nodeschool/organizers/issues/348)
 - [Global Sponsor Program.](https://github.com/nodeschool/organizers/issues/326)
 - [Setup a NodeSchool Foundation](https://github.com/nodeschool/organizers/issues/126)

**Comment by martinheidegger** [comment]
Due to lack of support I close this issue.

**Comment by johnbrett** [comment]
@martinheidegger just read this https://medium.com/@leichtgewicht/the-missing-hands-at-nodeschool-8999a90d33d1#.41kimln49 I thought it might be worth mentioning open collective: https://opencollective.com/ which could suit for this.. I know I'd happily contribute to a nodeschool open collective, I wonder would others too... :)

I think similar orgs use it for funding this type of organisation: https://opencollective.com/railsgirlsatl. 

I help out with the Dublin chapter when I can, and really enjoy the events. Just wanted to say seriously great work to you and all others who've contributed to nodeschool, it's inspiring 🎉

**Comment by martinheidegger** [comment]
@johnbrett Thank you for letting us know about opencollective. It certainly is an interesting project. However, I think bountysource's salt would works much like opencollective but is seems slightly better connected to the github structure and less dependent on paying out money directly (getting money from either services is charged at 10%). If we were to go down the money road bountysource seems a better bet.

_(Note: Received a donation from @pcuci, not sure what to do with it ...)_

**Comment by pcuci** [comment]
@martinheidegger I thought this was a good idea.

We'll charge $5 at the [next event](https://github.com/nodeschool/montreal/issues/41) for refreshments, the remaining cash can go to bountysource.

**Comment by Sequoia** [comment]
Hey @pcuci, what deliverables would you like to attach to see from this ticket/discussion? This particular ticket was closed a month ago due to lack of interest/support.

**Comment by pcuci** [comment]
Open to suggestions @Sequoia 

I'm planning a mini-fund-raising experiment on our next NodeSchool event, see what the difference from ticket prices is to go towards bountysource support(?)

It may very well be zero, in which case we mark this off as something we tried and learned from, dunno.

**Comment by martinheidegger** [comment]
https://www.dropbox.com/s/52vpygf9op135mz/Screenshot%202016-10-13%2008.15.18.png?dl=0

**Comment by Sequoia** [comment]
> Open to suggestions @Sequoia

My suggestion is that we return this ticket to the "closed" state. 😸  We discussed this a bit ago, it came to naught. Passing the hat at your own event does not require whole-group discussion-- you're free to do so and do what you wish with the money! 💸 

Please specify exactly what you want to see from this ticket if you wish to reopen it. [Gitter](https://gitter.im/nodeschool/organizers) is great for discussion if you just want to kick ideas around.
