### ISSUE TITLE
New chapter in Lima, Peru

### ISSUE THREAD

**Issue by ReinsBrain** [nodeschool/organizers#373]
Hello, my name is Rein Petersen and I have organized a large and growing group dedicated to Node.JS in Lima, Peru. See [http://www.meetup.com/Lima-NodeJS-Meetup](http://www.meetup.com/Lima-NodeJS-Meetup) or [http://nodejslima.org](http://nodejslima.org) . We've held a few successful meetups where we teach good practices with NodeJS. Personally, I have been working professionally with NodeJS for a few years. 

Our group has grown to over 1,000 members and I would like to use the workshopper format to add my workshops about unit-testing with NodeJS and NodeJS with Firebase. I like the fact that there are other good workshops that will allow us to present great workshops more frequently.

I hope we might be welcomed to create a new chapter in Lima, Peru.

Thank You.

**Comment by martinheidegger** [comment]
Hello @ReinsBrain Thank you in your interest. The Workshopper format _(though I recommend to look at [`workshopper-adventure`](https://github.com/workshopper/workshopper-adventure)_ for an implementation) is open-source software an easily accessible to anyone. We accept PR's with new workshoppers at https://github.com/nodeschool/nodeschool.github.io and they will immediately shine up in the list after the accepting of the PR. 

Would you also like to open a chapter for Lima?

**Comment by martinheidegger** [comment]
Ping @ReinsBrain

**Comment by martinheidegger** [comment]
I am assuming that you changed your mind (which is totally okay) and close this issue.
