### ISSUE TITLE
Translation System Contender: Crowdin

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#376]
Okay, I have been testing out Crowdin.com - a translation system for software.
Crowdin has several of the features necessary for more effective translations:
1. A comfortable interface to edit translations
2. A pretty well fleshed out API to integrate into CI tools
3. Support for translation permissions & double checks (something we intend to do already)
4. Support for mixed automatic translations

I can think of creating on NodeSchool project at crowdin and invite all translators to join and upload all translations to it (and build it) might work. It is important that we don't need translators "per workshopper" or "per homepage" so instead of [creating projects](https://crowdin.com/page/api/create-project) It would better if we would treat one workshopper/homepage etc. as [one file](https://crowdin.com/page/api/add-file) for the ci tools of each file it would be good to have an NodeSchool specific API that has one private key per workshopper _(the crowdin api only provides one per project)_ we would probably need to add API on top of it. Right now I am guessing that we would be okay with 5000 strings to be translated (89 USD/month) but atm. I am not quite sure about that. Also there is one feature that might be a bit annoying: There are two points that i see missing at crowdin though:
1. ~~I can not see a good notification system: For the translations to be effective we need to be able for hibernating translators to be notified when something changes~~ _I found the Notification system_
2. There is no API to manage users: With nodeschoolbot/other tools it would be good to have a way to create/invite users without going through the crowdin UI. (preferably it would be great if the invites would automatically be handled by adding people to translator teams @ github)

I was thinking we could ask Crowdin _(based in Ukraine btw.)_ to support the NodeSchool by giving us a free account to use for our work. I could think that in exchange we could offer a "Supported by Crowdin" badge somewhere and we could build a Node.js API. 

What do you guys think? @terrysahaidak @denysdovhan @sudodoki are Ukraine members? Would it make sense to ask in Person? 

Tasks to get crowdin to work
- [ ] Apply for a Open Source Licence [here](https://crowdin.com/page/open-source-project-setup-request)
- [ ] Implement a SSO system for github
- [ ] Create a system that allows workshoppers to submit their files only for a portion of the whole projects translations.

**Comment by martinheidegger** [comment]
https://crowdin.com/page/open-source-project-setup-request

**Comment by pcuci** [comment]
@martinheidegger most cities are bilingual, multilingual. Montreal is too.

Most local Montreal events are a mix of French and English MC'ing, sometimes a sentence starts in French and ends in English, et vice-versa, français et anglais. Most speakers are fluently bilingual.

Some local newsletters too are a mix/remix/mishmash of En+Fr together, in writing. They're fun to read. We want http://nodeschool.io/montreal to read the same.

There are more bilingual people in the world than monolinguals.

You and I are underserved.

cc: @David-Ro @ajmas

**Comment by martinheidegger** [comment]
@pcuci It is indeed funny (and much work) to maintain multiuser systems.

**Comment by pcuci** [comment]
@martinheidegger see this prototype backed by a google spreadsheet: http://pcuci.github.io/nodeschool-theams - perhaps something similar can be used for translations (?)

**Comment by martinheidegger** [comment]
@pcuci Did you try out `crowdin`? It supports teams and invites for translators and gives an API for getting process on projects & files / language. So we could use it to display publically the stats for the translation of the project. Having something like `theams` _(nice project btw.)_ for the missing languages might surely be nice on top of it.

**Comment by jpwesselink** [comment]
@pcuci Is there a locale for that mixed language flavour?

**Comment by martinheidegger** [comment]
General update: I have been working-with and testing crowdin at my day-job for a while. For the biggest part it seems a quite good solution for nodeschool. I requested a few improvements in regards to the github integration that I hope get implemented. They are necessary to properly attribute the people doing the translation.

**Comment by martinheidegger** [comment]
After thorough evaluation Crowdin, while really awesome technology, doesn't support crucial features for the organization of the Translation of NodeSchool. Namely:

- The Commit statements do not contain the authors of the translation
- The Github integration does not have separate branches for each language
- It is not possible to connect multiple repositories to one crowdin project (we would need to connect a lot of people to the same project :( )

So, imho. choose a different tool or write integration for crowdin, but tbh. I'd rather not maintain a custom sync tool...
