### ISSUE TITLE
New Chapter Request: Lima - Perú

### ISSUE THREAD

**Issue by ogsilvaa** [nodeschool/organizers#380]
Hello, I would like to start a chapter ** NodeSchool in Lima - Peru **. I'm @ogsilvaa on twitter / github and work in .Net, PHP and recently some Arduino. I will be co - organizing this chapter with Alan Azabache (@alanazabache [gh]) and Gino Maguiña (@gmvxtm [t / gh]). I've been using Node.js for 6 months and I would like to help others learn as well.

Our team will also participate professionals in the areas of Marketing and Administration to support in the work of organizing and promoting events.

We hope to propose a scheme of differentiated work for professionals and students so they can meet the expectations of both groups. Currently we have the support of a technical school and community nature of a local university interested in the project.

-----------------------------
Hola, me gustaría empezar un capítulo de NodeSchool en ** Lima - Perú **. Soy @ogsilvaa en twitter / github y trabajar en .Net, PHP y recientemente algunos Arduino. Voy a ser co - organización de este capítulo con Alan Azabache(@alanazabache [gh]) y Gino Maguiña (@gmvxtm [t/gh]). He estado usando Node.js durante 6 meses y me gustaría ayudar a otros a aprender también.

En nuestro equipo también participarán profesionales de las áreas de Marketing y Administración para dar soporte en las labores de organización y promoción de los eventos.

Esperamos proponer un esquema de trabajo diferenciado para los profesionales y estudiantes para que puedan cubrir las expectativas de ambos grupos. Actualmente contamos con el apoyo de una escuela técnica de índole comunitario y de una universidad local interesada en el proyecto.

**Comment by thibaudcolas** [comment]
Hi @ogsilvaa! I don't have the right permissions to create this new chapter for you but here are the questions I think you will be asked when the time comes:

- For repository names, NodeSchool tends to only use the name of the city. Would `lima` for you? That would be https://github.com/nodeschool/lima, and http://nodeschool.io/lima/ when you make a site.
- For co-organizers, can you provide the GitHub usernames of Alan and Gino?

Cheers!

**Comment by ogsilvaa** [comment]
OK thanks for the help. I modified the content with your instructions, Greetings

**Comment by martinheidegger** [comment]
@ogsilvaa Thank you for getting involved! I invited you as chapter-organizer and created the Lima chapter and you, @alanazabache and @gmvxtm as team members!

**Comment by ogsilvaa** [comment]
thanks, we will start to check and complete these days, greetings
