### ISSUE TITLE
New Chapter Request: São Paulo, Brazil

### ISSUE THREAD

**Issue by ErickWendel** [nodeschool/organizers#382]
Hello,
I am interested in starting a nodeschool chapter for São Paulo, Brazil. I'm a Community Manager at .NETCoders, the greater community of Brazil (look in meetup.com/netcoders and https://www.facebook.com/groups/netcoders).  I lectured in nodeconf Brazil (http://brazil.nodeconf.com/) and will be a honor organize this event.

**Comment by martinheidegger** [comment]
@ErickWendel Thank you for thinking of opening a chapter,

it is usually better if a chapter is not organized by one person but rather in groups. Do you have someone that can organize this chapter with you?

**Comment by ErickWendel** [comment]
Yes! My group is .NETCoders and the organiser is @Leolosi (https://github.com/Leolosi) and me

**Comment by martinheidegger** [comment]
Oh! Just when I wanted to create sao-paolo for you I found that sao paolo already exists, lets move the discussion there!
