### ISSUE TITLE
File a small change in the event location latitude/logitude

### ISSUE THREAD

**Issue by eunsol715** [nodeschool/organizers#384]
Hi!

I will be hosting a NodeSchool event on Oct. 30th in Seoul, Korea. 
However, on the maps it indicates that it will be held in somewhere else in Korea. ( I might have put down the wrong latitude/logitude data points when I submitted an event form) 

Could you fix that please?

Thank you!

- EunSol Lee

**Comment by martinheidegger** [comment]
Hello Lee!

I just updated the address, please let me know if its correct.

cheers
Martin

**Comment by eunsol715** [comment]
Hi Martin,

This is EunSol Lee. First of all, thank you for your quick response :)
It looks very fine right now but I have another question to ask!

Do we have to name our event as “NodeSchool Seoul” using the actual city we would be in? 
or does it matter if we name our event as “NodeSchool Korea”?

Thank you.

Have a great day,
EunSol Lee

**Comment by martinheidegger** [comment]
NodeSchool events are usually per chapter. I think NodeSchool Seoul sounds right! NodeSchool Korea would be sounding off (Other places name themselves by their city-place as well)

**Comment by martinheidegger** [comment]
I am closing this issue since the lat/long problem seems to be solved. I don't think its a good idea to change from Seoul -> Korea but if you think it is a good idea then open a new issue please.

thanks and cheers
Martin
