### ISSUE TITLE
Open a new chapter for Casablanca

### ISSUE THREAD

**Issue by saadaouad** [nodeschool/organizers#385]
Hi, I would like to start a nodeschool chapter for Casablanca. I am developer web work at OBytes . I have been using Node.js for 6 months and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Thank you @saadaouad,for thinking of opening a chapter,

it is usually better if a chapter is not organized by one person but rather in groups. Do you have someone that can organize this chapter with you?

**Comment by saadaouad** [comment]
Hello @martinheidegger, for now I'm alone.

**Comment by martinheidegger** [comment]
I sent out a tweet looking for co-organisers in Morocco! Lets see if we find help for you.
 https://twitter.com/nodeschool/status/780576785360490496

**Comment by saadaouad** [comment]
Thanks for your help @martinheidegger, let's go...

**Comment by andaluz** [comment]
I know some developers from Casablanca, I'll let them know about NodeSchool.  The potential in Casablanca is huge. It's like the Silicon Valley of NorthWest Africa (the port to Africa).

**Comment by ismnoiet** [comment]
Hi @saadaouad I'm hamza, the maintainer of Nodeschool Algiers if you need any kind of help regarding Javascript just let me know.

**Comment by GO3LIN** [comment]
Hello, I am El Mehdi, a moroccan full-stack web developer, the NodeSchool project is very exciting and I will be very pleased to join the co-organisers team at Casablanca. I am using nodeJs in my daily life, and it's just a very powerful tool. 

Sharing my knowledge is also something I really care about and love doing. So let me know how can I help.

**Comment by martinheidegger** [comment]
Awesome @saadaouad and @GO3LIN , great that this worked out! I created the casablanca repo and invited the both of you to the chapter team. I think this should be enough to get you started. Do you need anything more?

**Comment by martinheidegger** [comment]
I have exchanged mails with @saadaouad privately. @saadaouad Do you think we can close this issue?

**Comment by saadaouad** [comment]
Yes @martinheidegger go for it, thanks for your help :+1:
