### ISSUE TITLE
Job openings

### ISSUE THREAD

**Issue by seklekov** [nodeschool/organizers#386]
Issues to share job openings for Node.js developer

**Comment by seklekov** [comment]
Russian startup [Unicat.biz](http://unicat.biz) are looking for Senior Node.js developer.
Стартап из Санкт-Петербурга разыскивает опытного разработчика Node.js. Обещаем будет интересно!

**Comment by martinheidegger** [comment]
It might be okay to to share job openings but not in this repo: Please use: https://github.com/nodeschool/jobs/issues - The visibility might need fixing though.
