### ISSUE TITLE
Organizers' groups names

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/organizers#391]
Since we're adding Community Groups to our framework we should be able to address their organizers' team as such which is not possible since the current setup is focussed on Chapter Organizers. 

I see the following solutions:

- Put them all on the same team: rename the `chapter-organizers` team to `organizers`
- Create a separate team: `community-group-organizers`

Should we set this up, and if so how? Your input please?

**Comment by martinheidegger** [comment]
I ❤️  _simply_ `organizers`. should contain all the people of `group-organizers` and `chapter-organizers`. Which could or could not be a thing.

**Comment by jpwesselink** [comment]
A quick search for all mentions of @nodeschool/chapter-organizers yields only a handful of results: https://github.com/search?langOverride=&q=team%3Anodeschool%2Fchapter-organizers&repo=&start_value=1&type=Issues 

Which is a good thing, so renaming to `organizers` will not be very intrusive for issues

**Comment by jpwesselink** [comment]
@martinheidegger I like that `organizers` approach very much, should be pretty unintrusive

**Comment by martinheidegger** [comment]
I think you should roll with it

**Comment by riyadhalnur** [comment]
small change but makes a big difference. lets do it!

**Comment by thebergamo** [comment]
I like this approach <3

**Comment by fforres** [comment]
Love it :)

**Comment by martinheidegger** [comment]
It is settled then → https://github.com/nodeschool/nodeschool.github.io/pull/536
