### ISSUE TITLE
Add new contributor to Foyle-Valley chapter

### ISSUE THREAD

**Issue by diarmaidm** [nodeschool/organizers#392]
Hi,
I am on Team Maintainer team for foyle-valley chapter.
How do I add new contributors that can act as co-organizers/repo maintainers?

For reference - Issue for chapter creation https://github.com/nodeschool/organizers/issues/324

Issue to add a new contributor but was unable https://github.com/nodeschool/foyle-valley/issues/2
I tried using `@nodeschoolbot` but get:

> Sorry @diarmaidm. You are not allowed to do that if you are not a member of the chapter-organizers team

Can you assist?
Thanks,
Diarmaid.

**Comment by riyadhalnur** [comment]
Hi @diarmaidm,

I have added you and @PMcDevitt to the foyle-valley team and also to the chapter-organisers team. Let me know if everything's working for you guys.

Cheers,
Riyadh
