### ISSUE TITLE
Can't access regina-sk repo

### ISSUE THREAD

**Issue by normrider2001** [nodeschool/organizers#394]
Hi 

I'm a member of the organizers team, but I don't have admin access to the regina-sk repo.  I have admin access to a bunch of other repos.

Craig

**Comment by martinheidegger** [comment]
Hello @normrider2001 !

It seems like the @nodeschool/regina-sk team was not added as admin to the repo. I fixed that, now you should be able to access it.

Please let me know if it worked.

**Comment by normrider2001** [comment]
It worked now thanks @martinheidegger
