### ISSUE TITLE
Date & URL change for NodeSchool Regina

### ISSUE THREAD

**Issue by lawson2k** [nodeschool/organizers#401]
Hi there,

I'm one of the organizers of the upcoming NodeSchool Regina. We've changed dates from November 5th (which is what currently shows on the main NodeSchool site) to **November 19th**.

The URL has also changed to https://nodeschool.io/regina-sk/ (note that we are making updates that will go live EOD). 

Finally, we're calling it "NodeSchool YQR" rather than NodeSchool Regina, if you could change that too.

Could you please update this on the Upcoming Workshops listings?

Thanks!

Karen Lawson
klawson@gasbuddy.com

**Comment by jpwesselink** [comment]
Hi @lawson2k, I'd be happy to adjust this, however, I noticed that you're not an organizer: I can't find you! Before I move on I'd like to notify @nodeschool/regina-sk to add you to their team, or have them confirm you are organizing as well : )

**Comment by lawson2k** [comment]
Hey JP,

Sorry about that, I should be added as an organizer now!

Best,

Karen Lawson
Corporate Events Coordinator
klawson@gasbuddy.com<mailto:klawson@gasbuddy.com> | 306-347-8159
Check us out<https://www.gasbuddy.com/about> | Get the app<http://gasbuddy.com/app>
[cid:6CD656BF-7F11-4208-B698-D9BC0F6951AE]<https://www.facebook.com/gasbuddy/>[cid:A9DD3049-E8E7-402F-87A8-50D3A4DD15B8]<https://twitter.com/GasBuddy>[cid:3E552C42-704A-4E57-A47B-0BC615B0BE57]<https://www.instagram.com/gasbuddy/>[cid:375CAC6D-BF41-4D61-8AD0-F2E3464699A3]<https://www.linkedin.com/company/gasbuddy>

**Comment by normrider2001** [comment]
I can confirm she is an organizer. I will add her to the team.

**Comment by dhruv-m-patel** [comment]
@normrider2001 @jpwesselink I have added @lawson2k as a collaborator on @nodeschool/regina-sk

**Comment by jpwesselink** [comment]
Alrighty, should be changed : )

**Comment by jpwesselink** [comment]
Can you validate the changes and close this ticket if all is well?

**Comment by jpwesselink** [comment]
Can you share how that meetup went? Would be nice to hear your experiences!

**Comment by lawson2k** [comment]
@jpwesselink, @normrider2001 just submitted a recap to nodeschool/write-ups if you're interested in reading. Thanks!
