### ISSUE TITLE
Education group at Node Interactive North America: will we see you there?

### ISSUE THREAD

**Issue by hackygolucky** [nodeschool/organizers#403]
NodeSchool is so central to folks learning Node.js. It would be awesome to see who will be in attendance at Node Interactive North America from the NodeSchool organizers. We'll be having time set aside during [Collaboration Summit](https://github.com/nodejs/education/issues/17) to discuss education in Node.js moving forward, and I can't think of what that looks like without input from the awesome work y'all do.

Anyone going to be there? Please contact me with questions!(or just comment here because yay)

**Comment by martinheidegger** [comment]
Date has passed, right?
