### ISSUE TITLE
New Chapter: Rock Hill, SC

### ISSUE THREAD

**Issue by bardicwarrior** [nodeschool/organizers#408]
Hi, I'm new to the Node.is world and am hoping to connect with locals to expand our education and use of Node.is. The chapter name would be Rock Hill, SC, or Charlotte, NC if that is preferred, and while I a complete noob with Node.is I'd be happy to help get something going and find fellow organizers. I am @bardicwarrior on Twitter and will be sharing my projects on GitHub under 'bardicwarrior'.

Cheers!

**Comment by jpwesselink** [comment]
Aloha @bardicwarrior. Good to hear you want to create a chapter! ⚡ Are you going to organize it by yourself or do you get help from others helping you?

**Comment by riyadhalnur** [comment]
@bardicwarrior Any updates?
