### ISSUE TITLE
Being added to the NodeSchool Organisation?

### ISSUE THREAD

**Issue by skipzero** [nodeschool/organizers#409]
I volunteer at nodeSchool, San Francisco and was wondering how one gets added to the organisation? Seems like it's the founding members out here not sure if that's the general rule of thumb or not. 
Sorry if this has come up before, I looked around before posting and didn't see anything on this topic.

**Comment by riyadhalnur** [comment]
Hey @skipzero, it's perfectly to ask this question and I'm glad you asked. At the moment, all chapter organisers are automatically added to the NodeSchool organisation. If any chapter decides to invite someone outside the organisation to be a collaborator, they can do that as well. I hope that answers your question. Ping if you need more information.

**Comment by skipzero** [comment]
That covered my question! Thanks @riyadhalnur for the quick reply! 😸

**Comment by riyadhalnur** [comment]
Anytime 😃 . Closing this issue. Please feel to reopen if premature.
