### ISSUE TITLE
Change the event title

### ISSUE THREAD

**Issue by rsoares** [nodeschool/organizers#412]
Hi! Sorry, but we filled in the event title with the wrong name. How can we change to "NodeSchool Faro"?
Thanks!

**Comment by riyadhalnur** [comment]
Which event?

**Comment by rsoares** [comment]
Sorry, it's the one on [Feb, 4th 2017](https://nodeschool.io/events.html#2017-Feb): "Nodeschool - Learn You Node.js"

**Comment by riyadhalnur** [comment]
Ping @jpwesselink. I think you have permissions to update the Google doc?

**Comment by jpwesselink** [comment]
I have, let me fix that :D

**Comment by jpwesselink** [comment]
@rsoares Should be ok, can you check?

**Comment by rsoares** [comment]
Yup! It's OK now. Thanks, @riyadhalnur and @jpwesselink! 👍

**Comment by riyadhalnur** [comment]
Cheers! Thanks to @jpwesselink actually for updating the event name. Closing this issue now then.
