### ISSUE TITLE
New Event, Nodeshool Elazig, Turkey

### ISSUE THREAD

**Issue by icalik** [nodeschool/organizers#421]
Hi. There have been created a new chapter called "Nodeschool Elazig". In this new chapter, we organised a new workshop named 'Git and Github 101' as our first workshop. Register link of the event is https://ti.to/nodeschool-elazig/git-101-workshop . Necessary announcements have been made for students and people who had interest in Javascript. We would like this chapter's name to be seen on nodeshool.io page and event page as with workshop name 'Git and Github 101'.  Thank you. W/ @cumen @unalkalkan @firatyenidunya

**Comment by riyadhalnur** [comment]
Hi @icalik, that's great! You can show the event on the nodeschool.io website by filling out this form - [Events form](https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform?usp=form_confirm).

Best of luck with your event. 😃

**Comment by riyadhalnur** [comment]
Closing this. Please feel free to re-open if premature.
