### ISSUE TITLE
New Chapter: Porto Alegre

### ISSUE THREAD

**Issue by andreymoser** [nodeschool/organizers#425]
Hi!

I would like to start the [Porto Alegre](http://github.com/nodeschool/porto-alegre) nodeschool chapter. I am [@andreymoser](http://twitter.com/andreymoser) and currently I'm an organizer of [Node.js meetups in Porto Alegre](https://github.com/node-poa/Meetups). Some university students in Porto Alegre asked me to help them on Node.js and I'm interested to create this chapter in order to engage them. :)

**Comment by riyadhalnur** [comment]
Hi @andreymoser, there's already a chapter for Porto Alegre as you've linked in your comment. Maybe @lucaslago can add you as a team member in the chapter?

**Comment by andreymoser** [comment]
Hi @riyadhalnur, I'll talk with him and I'll let you know. Thanks!
