### ISSUE TITLE
New Chapter: Taft Avenue Manila, PH

### ISSUE THREAD

**Issue by seanagustin** [nodeschool/organizers#431]
Hi, I would like to start a nodeschool chapter for Taft, Avenue, Manila PH I am @merwinsean on twitter and work at/on De La Salle College of Saint Benilde . I have been using Node.js for 2 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @seanagustin, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
