### ISSUE TITLE
New Chapter: De La Salle University, Manila

### ISSUE THREAD

**Issue by Yapapalicious** [nodeschool/organizers#432]
Hi, I would like to start a nodeschool chapter for DLSU. I am @Yapapalicious on twitter and work at/on . I have been using Node.js for 6 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @Yapapalicious, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
