### ISSUE TITLE
Starting a new node school chapter

### ISSUE THREAD

**Issue by ardisantos** [nodeschool/organizers#433]
Hi, I would like to start a nodeschool chapter for De La Salle - College of Saint Benilde. I am santos.ardi on facebook and work at/on . I have been learning Node.js for a month now and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @ardisantos, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
