### ISSUE TITLE
New Chapter: Makati City, Philippines

### ISSUE THREAD

**Issue by mitchpedro** [nodeschool/organizers#434]
Hi, I would like to start a nodeschool chapter for Makati City, Philippines. I am @mitchpedro on twitter and a student of De La Salle - College of Saint Benilde . I will be co-organizing this chapter with some of my friends. I started using Node.js this trimester and would like to help others learn as well. Also, it is where I live so if ever I start a chapter, I could easily recruit people into joining and I could easily help them.

**Comment by riyadhalnur** [comment]
Hi @mitchpedro, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
