### ISSUE TITLE
New Chapter: Sta Maria

### ISSUE THREAD

**Issue by josefezekiel** [nodeschool/organizers#436]
Hi, I would like to start a nodeschool chapter for Sta Maria Bulacan, Philippines. I am @josefezekiel on twitter and a student of DLS-CSB . I will be co-organizing this chapter with some of my classmates. I have been using Node.js for 4 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @josefezekiel, that's awesome. There's already a chapter for London though [https://github.com/nodeschool/london](https://github.com/nodeschool/london). Maybe you could start there?

**Comment by riyadhalnur** [comment]
Hi @josefezekiel, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
