### ISSUE TITLE
New Chapter: Cavite City, Philippines

### ISSUE THREAD

**Issue by JohnAdres** [nodeschool/organizers#437]
Hi, I would like to start a nodeschool chapter at Cavite City, Manila PH I am @johnadres1 on twitter and work at/on De La Salle College of Saint Benilde . I have been using Node.js for 3 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @JohnAdres, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
