### ISSUE TITLE
New Chapter: Koronadal City, Philippines

### ISSUE THREAD

**Issue by ernestpascual** [nodeschool/organizers#438]
Hi, I would like to start a nodeschool chapter for Koronadal City, Philippines . I am @izedbeats on twitter and I'am a student of De La Salle - College of St. Benilde .I have been using Node.js for a few months from our IS-EBIZ subject and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @ernestpascual, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
