### ISSUE TITLE
New Chapter: Pandi, Bulacan, Philippines

### ISSUE THREAD

**Issue by ChesterCanites** [nodeschool/organizers#439]
Hi, I would like to start a nodeschool chapter for Pandi, Bulacan. I am @ChesCanites on twitter and a student from De La Salle - College of St. Benilde . I have been using Node.js for 1 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @ChesterCanites, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
