### ISSUE TITLE
New Chapter: Paranaque City, Manila, PH

### ISSUE THREAD

**Issue by klaudinealejar** [nodeschool/organizers#440]
Hi, I would like to start a nodeschool chapter for BF Homes, Paranaque City. I am @_khlorajela on twitter and I am a student from De La Salle College of Saint Benilde, Manila. I have been using Node.js for 1 month and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @klaudinealejar, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
