### ISSUE TITLE
New Chapter:Muntinlupa City, Philippines

### ISSUE THREAD

**Issue by micoylagan** [nodeschool/organizers#442]
Hi, I would like to start a nodeschool chapter for Muntinlupa City. I am @micoylagan on twitter and a student at De La Salle - College of Saint Benilde . I have been using Node.js for 6 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @micoylagan, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
