### ISSUE TITLE
NEW CHAPTER: ZAMBOANGA CITY,PH

### ISSUE THREAD

**Issue by seansaimon** [nodeschool/organizers#443]
Hi, I would like to start a nodeschool chapter for Zamboanga City, Philippines
 I am @seansaimon on twitter and work at/on .
I have been using Node.js for 4 months and would like to help others learn as well. *

The chapter name should preferably be the name of the city, where the workshops will be held. 
Alternatively the area should be small, but yet meaningful

**Comment by riyadhalnur** [comment]
Hi @seansaimon, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
