### ISSUE TITLE
NEW CHAPTER: ANGELES CITY,PH

### ISSUE THREAD

**Issue by Gabmntmyr** [nodeschool/organizers#444]
Hi, I would like to start a nodeschool chapter at ANGELES CITY PAMPANGA. I am @gab_montemayor on twitter . I have been using Node.js for 3 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @Gabmntmyr, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
