### ISSUE TITLE
NEW CHAPTER: SAN PEDRO CITY, LAGUNA

### ISSUE THREAD

**Issue by marvinpaculan** [nodeschool/organizers#445]
Hi, I would like to start a nodeschool chapter at SAN PEDRO CITY, LAGUNA. I am Marvin Paculan on Facebook.  I have been using Node.js for 3 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @marvinpaculan, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
