### ISSUE TITLE
New Chapter: Caloocan City, Philippines

### ISSUE THREAD

**Issue by happiestman12** [nodeschool/organizers#446]
Hello, I would like to start a node school here in my hometown. the youth will enjoy this. I a student in De Lasalle College of Saint Benilde. I encounter this in my subject IS-EBIZ and it helped me a lot as a student and I hope that every one who dreams to be a IT/IS/CA can learn about this.

**Comment by riyadhalnur** [comment]
Hi @happiestman12, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
