### ISSUE TITLE
New Chapter: Valenzuela City, Philipppines

### ISSUE THREAD

**Issue by biancapatrizavalmeo** [nodeschool/organizers#447]
Hi nodeschool, my professor in school introduced us in your community, and the term is ending, but I would still like to continue my journey in learning node.js with your community. so i would like to request to a new chapter in my hometown to reach more people and start learning with them. Thank you!

**Comment by riyadhalnur** [comment]
Hi @biancapatrizavalmeo, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
