### ISSUE TITLE
New Chapter: Baguio City, Benguet

### ISSUE THREAD

**Issue by johvinmagtoto** [nodeschool/organizers#448]
Hi, I would like to start a nodeschool chapter for Baguio City, Benguet, Philippines. I am [@johvinmagtoto] on twitter and instagram. I will be organizing this chapter. I have been using Node.js for 3 months and would like to help others learn.

Thanks & Regards
Johvin Magtoto

**Comment by riyadhalnur** [comment]
Hi @johvinmagtoto, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
