### ISSUE TITLE
NEW CHAPTER: MANDALUYONG CITY, PHILIPPINES

### ISSUE THREAD

**Issue by kier723** [nodeschool/organizers#449]
Hi, I would like to start a nodeschool chapter for mandaluyong city. I am Kyrie Eleison Fajardo . I will be organizing this chapter. I have been using Node.js for 4 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @kier723, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by llkats** [comment]
@riyadhalnur I think that all of these chapter requests that were created on April 21st are bot-created. The text is all too similar and the accounts have barely any activity on most of them. I'm considering opening a ticket with GitHub support, though we haven't seen any more spam lately. Thoughts on just deleting these issues?

**Comment by riyadhalnur** [comment]
@llkats Yeah I put off responding to these few issues for a few weeks but then some of the issues have humans in their profile pictures and they seem to have some activity if not a lot. I think we can keep these open and start closing them once you hear back from GitHub support.
