### ISSUE TITLE
New Chapter: Pasig City, Philippines

### ISSUE THREAD

**Issue by joshualaxamana** [nodeschool/organizers#450]
Hello, I would like to start a NodeSchool chapter for Pasig City here in the Philippines. I am Joshua Laxamana . I will be organizing this chapter. I have been using Node.js for 3 months and I would like to help others learn as well. Thank you very much!

**Comment by riyadhalnur** [comment]
Hi @joshualaxamana, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.
