### ISSUE TITLE
New Chapter: Brooklyn, NY

### ISSUE THREAD

**Issue by TatisLois** [nodeschool/organizers#451]
Hi, I would like to start a nodeschool chapter for Brooklyn, NY. I am @supremeWZRD on twitter and work at LearnVest as a FED. I will be organising this chapter by myself but have support from others in the community and am open to other co-organisers. I have been using Node.js/Javascript for over a year and would like to help others learn as well, while I continue to learn myself.

**Comment by riyadhalnur** [comment]
Hi @TatisLois, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by TatisLois** [comment]
@riyadhalnur Thanks for responding, I was able to secure a few other co-organisers and will link to there githubs below. Between the lot of us, I am confident that we can offer a premium experience for the engineers in Brooklyn! 

https://github.com/ericduran
https://github.com/conortm
https://github.com/nimadera

**Comment by TatisLois** [comment]
@riyadhalnur anything else we can provide to help take this across the finish line?

**Comment by riyadhalnur** [comment]
Hi @TatisLois  I created the brooklyn team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/brooklyn. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.
