### ISSUE TITLE
Please add me to nodeschool/chicago 

### ISSUE THREAD

**Issue by thatadamedwards** [nodeschool/organizers#452]
Hello, my name is Adam Edwards and I am looking to be a co-organizer for NodeSchool Chicago with @MarcusHogue. Please add me to the nodeschool group and the nodeschool/chicago group if possible please

**Comment by thatadamedwards** [comment]
Hello - I'm not sure who to assign this to, but I have had this request open for 14 days now. Did I miss a step in applying to be an organizer?

**Comment by riyadhalnur** [comment]
Hi, @thatadamedwards, waiting on one of the guys from the Chicago team to confirm. They can add you to the team themselves afterwards or I can do it also.

cc @MarcusHogue @azizali

**Comment by MarcusHogue** [comment]
@riyadhalnur confirmed!

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user @thatadamedwards

**Comment by riyadhalnur** [comment]
Sent out the invites @thatadamedwards. Let me know if everything's ok. Cheers. Apologies again for the delay.

**Comment by thatadamedwards** [comment]
Sorry I hadn't responded sooner - but yes the invite went through and everything looks good now!

**Comment by riyadhalnur** [comment]
Awesome. Closing this issue then.
