### ISSUE TITLE
New Chapter: Novosibirsk, Russia

### ISSUE THREAD

**Issue by ekaragodin** [nodeschool/organizers#454]
Hi, I would like to start a nodeschool chapter for Novosibirsk, Russia. I am @ekaragodin on twitter and work at Openprovider. I have been using Javascript for 5 years and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @ekaragodin , that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by ekaragodin** [comment]
Hi @riyadhalnur! Also @alexeysinko wants to become a co-organizer. He has a lot of experience with javascript. And I'm looking for others.

**Comment by scherebedov** [comment]
Hi, I want to be a co-organizer. I can be a mentor.

**Comment by ekaragodin** [comment]
Hi @riyadhalnur, need more people?

**Comment by riyadhalnur** [comment]
Hi @ekaragodin, sorry for getting back to you so late. I will create the chapter tonight.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user @ekaragodin

**Comment by riyadhalnur** [comment]
Hi @ekaragodin, I created the Novosibirsk team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/novosibirsk. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by ekaragodin** [comment]
Thanks, everything is good.
