### ISSUE TITLE
New chapter: Okinawa, Japan

### ISSUE THREAD

**Issue by pcambra** [nodeschool/organizers#456]
Hi, I'd like to start a new chapter here in Okinawa, I am @pcambra on Twitter and I work at OIST (Okinawa Institute for Science and Technology) where we're starting to use Node for some of the stuff we build.
I'll be looking for help hosting, mentoring and making it a very participatory meetup :)

**Comment by riyadhalnur** [comment]
Hi @pcambra, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by pakmanlh** [comment]
Hey there, I'm a front-end developer who lives in Okinawa too, I'd be glad to helping somehow in the creation of the Okinawan chapter.

**Comment by birosjh** [comment]
I'd be happy to help out!  I'm a backend developer working in Okinawa.

**Comment by riyadhalnur** [comment]
Hi @pcambra, I created the okinawa team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/okinawa. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by yosuke-furukawa** [comment]
Sounds so fun!! I would like to share knowledge with nodeschool tokyo, osaka, fukui and okinawa!

**Comment by abouthiroppy** [comment]
🎉

**Comment by pcambra** [comment]
Thanks @riyadhalnur 💃 

@yosuke-furukawa get in touch and let's arrange that, shall we? :)

**Comment by riyadhalnur** [comment]
Closing this issue. Please feel free to reopen if premature. Welcome again to the family!
