### ISSUE TITLE
New chapter: CDMX, Mexico

### ISSUE THREAD

**Issue by DeipMartin** [nodeschool/organizers#464]
Hi, I'd like to start a new chapter here in Mexico, I'm study at UPIICSA - IPN  (Instituto Politecnico Nacional) where We are starting to use and teach node and we would like to organize a nodeschool.
I'll be looking for help mentoring and making it a very participatory meetup :)   . 
I am looking forward to your response.
Thanks

**Comment by riyadhalnur** [comment]
Hi @DeipMartin, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by DeipMartin** [comment]
hi @riyadhalnur , 
Yep ,at the moment we are 5 that we are planning the organization of the workshops :D

**Comment by evillasr** [comment]
I can colaborate with him 👍

**Comment by riyadhalnur** [comment]
Hi @DeipMartin, I created the cdmx team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/cdmx. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by DeipMartin** [comment]
Thanks !!!!! :D
We will give the best of us,  I promise


2017-06-20 3:16 GMT-05:00 Riyadh Al Nur <notifications@github.com>:

**Comment by riyadhalnur** [comment]
You are welcome. Closing this issue then. Welcome again to the family!
