### ISSUE TITLE
New Chapter: Belgium

### ISSUE THREAD

**Issue by Milenkoo** [nodeschool/organizers#465]
Hi, I'd like to start a new chapter here in Belgium. I am an open source engineer intern working at Hackages.io.

I already have a coorganizer and i'll reach out to local node communities to find mentors. I also have experience in mentoring in those kind of events thanks to Hackages.

Thanks!

**Comment by Milenkoo** [comment]
@riyadhalnur 
Any updates? I really want to start this soon

**Comment by riyadhalnur** [comment]
Hi @Milenkoo, sorry for the delayed response. Are you planning to start a city-wide chapter or country-wide?

**Comment by Milenkoo** [comment]
Hi, I'm planning to start a country wide chapter. Belgium is a very small country I don't want to split the community into small groups.

Thank you for your answer

**Comment by riyadhalnur** [comment]
Hi @Milenkoo, I created the belgium team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/belgium. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by Milenkoo** [comment]
Thank you very much! I'll take a look at the wiki this evening

**Comment by riyadhalnur** [comment]
Great! Closing this issue then. Please feel free to re-open if premature.
