### ISSUE TITLE
New Chapter: Luanda, Angola

### ISSUE THREAD

**Issue by quindai** [nodeschool/organizers#466]
Hi, I would like to start a nodeschool chapter called "luanda",  the country is Angola(Africa). I am @rquindai on twitter and work at LaCCAN - Laboratorio de Computação Científica e Análise Numérica, UFAL . I will be co-organizing this chapter with Flowck and Joel Epalanga. I have been using Node.js for 18 months and would like to help others learn as well.

**Comment by quindai** [comment]
Hi @riyadhalnur, I would like to know when will you add me as a chapter organizer?

**Comment by quindai** [comment]
@nodeschoolbot create-repo luanda

**Comment by riyadhalnur** [comment]
Hi @quindai, sorry for the delay. I'm a bit busy. I will get around to creating the chapter for you this week. Hang in there! Sorry again.

**Comment by quindai** [comment]
I'll be waiting, @riyadhalnur thank you for your time.

**Comment by riyadhalnur** [comment]
Hi @quindai, I created the Luanda team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/luanda. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by quindai** [comment]
Thank you @riyadhalnur, everything is working just fine 💯

**Comment by riyadhalnur** [comment]
Great! Closing this issue then.
