### ISSUE TITLE
Edit Chapter permission rights

### ISSUE THREAD

**Issue by ldbraun** [nodeschool/organizers#467]
Hello Organizers,
my name is Braun Okoi Boniface @ldbraun, the lead organizer of the Nodeschool Chapter Abuja.
I have been trying to edit my chapter but it seems I dont have permisssions/privilege rights to edit or modify the chapter.

please, what do I need to do?

best regards

**Comment by ldbraun** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Hi @ldbraun, you already have write permissions to the Abuja repo. Please check if there any errors when pushing to git.

**Comment by ldbraun** [comment]
Ok. thanks @riyadhalnur . will check and get back to you with any error thereof.

**Comment by riyadhalnur** [comment]
@ldbraun Still receiving errors?

**Comment by riyadhalnur** [comment]
Assuming there are no problems anymore.
