### ISSUE TITLE
Add members to wisconsin chapter

### ISSUE THREAD

**Issue by zo0o0ot** [nodeschool/organizers#470]
@nodeschoolbot add-team-user wisconsin @yetialmighty

**Comment by zo0o0ot** [comment]
The bot may be down.  Would anyone be willing to help me add @YetiAlmighty as a team member in the wisconsin nodeschool team, as well as giving them access to https://github.com/nodeschool/wisconsin ?

Thanks!

**Comment by riyadhalnur** [comment]
Hi @zo0o0ot, I sent out an invite to @YetiAlmighty to join the wisconsin team.  The nodeschoolbot is down. I opened an issue for it here #469.
