### ISSUE TITLE
locked out of the Faro Chapter Repo

### ISSUE THREAD

**Issue by mcoquet** [nodeschool/organizers#471]
Hi , I'm the admin of the Faro chapter and yesterday I was trying to add someone to the repo and I mistakenly locked myself out 😭 . 

Can someone give me a hand? I can add members to my Team ( Faro ) but I need admin permissions to the repo itself. I can no longer resolve issues or merge PRs :(

Thank you in advance for your time and patience 👍

**Comment by mcoquet** [comment]
@riyadhalnur Apologies for pulling you directly , but noticed you were active in other issues. Looking for help on this one :( 

Thank you for your time and patience :)

**Comment by riyadhalnur** [comment]
@mcoquet No problem at all. Tag me anytime. Sorry for the delayed response. Just got back from my holiday today. Fixed the permissions. Should be all good now.

**Comment by mcoquet** [comment]
purrrfect! 

Thank you so much 👍 😄
