### ISSUE TITLE
Actually starting NodeSchool Utrecht, Netherlands chapter

### ISSUE THREAD

**Issue by GeorgeSapkin** [nodeschool/organizers#473]
We are trying to start a local chapter of NodeSchool in Utrecht, Netherlands. However the [repo](https://github.com/nodeschool/utrecht) has already been claimed (#211) by @fritzvd 2 years ago and [Meetup page](https://www.meetup.com/meetup-group-qqfnPcvK/) by @rickheere this year.

There has not been any progress or a single meetup organized in 2 years since then. Is there anything that can be done to resolve this? Like a rule that inactive chapters are let go and new organizers can step up.

Posting this here for visibility since it looks like it's not going to be resolved by private conversations.

CC @ramongebben @jpwesselink @fritzvd @rickheere

**Comment by fritzvd** [comment]
Hi George,

Thanks for the heads-up! How can we transfer ownership? I started very enthusiastically and then a kid happened. So I would be glad if someone would step up in the driver-seat. I'd happily help out in Utrecht!

Let me see if I can transfer ownership to you and @jpwesselink now..

Fritz

**Comment by fritzvd** [comment]
Also, who is we?

**Comment by rvanlaar** [comment]
@fritzvd Some friends of mine @GeorgeSapkin @GeorgeSapkin. See also Coffee Code and Chat, a bunch of programmers that code on Saturday morning. 

https://www.meetup.com/Coffee-Code-and-Chat/

**Comment by RamonGebben** [comment]
@rvanlaar and @fritzvd, @GeorgeSapkin and myself would take on the heavy load untill the chapter grows and @fritzvd if you'd add me as a collaborator on the repo we could get started on the website and other related things while we wait for the Meetup page to become free.

**Comment by jlengrand** [comment]
@RamonGebben I'm up for giving a hand too, if you guys need anything.

**Comment by fritzvd** [comment]
ok. I don't think I have the access to add new users to the group. 

Pinging @a0viedo or @brianloveswords to help out: *ping*

**Comment by jpwesselink** [comment]
I'll sort this later on today

**Comment by jpwesselink** [comment]
First off, creating an issue explaining that you want to revive a dormant chapter would have sufficed. NodeSchool is about dialogue, understanding, tolerance and helping each other, not about accusations, those will get us nowhere. 

Secondly, @RamonGebben, @rvanlaar and @GeorgeSapkin are added and/or invited to the Utrecht repo. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/utrecht. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by jpwesselink** [comment]
Regarding the meetup.com group, I see two possibilities here: Ask @rickheere nicely if you can become co-organisers (where Rick will still be accountable for billing), the other option would be asking Rick if he can transfer the community to one of you (where you will pay meetup out of your own pocket).

**Comment by RamonGebben** [comment]
@jpwesselink Thanks for the quick work.
It was never our intention to make potential harmful accusations. For that reason the issue has being updated to express our intent in a better light.

I'm very happy thing could be resolved in the manner and want to thank everybody involved in resolving some of the conflicts that emerged from this.

Let's make the Utrecht chapter just as much fun as the previous work done by @jpwesselink  @stefanmirck @rickheere and many more.

**Comment by RamonGebben** [comment]
@jpwesselink Either way is fine.
Let's leave it as is and indeed kindly request to become co-organisers and I will reimburse @rickheere for the costs made for hosting the Meetup page. That way everybody is still involved and responsibility is shared.

**Comment by jpwesselink** [comment]
You got this, closing this for now. If you have any questions don't hesitate to create another issue. Good luck, make it worthwhile!
