### ISSUE TITLE
Add new memeber to lviv chapter team 

### ISSUE THREAD

**Issue by lavriv92** [nodeschool/organizers#474]
I want to add @itspoma to Lviv chapter organizers team. He is self-motivated and responsible engineer, and ask me to help with organizing next NodeShool event in Lviv.

**Comment by itspoma** [comment]
hi @lavriv92 ! Thanks for this pull-request.
I hope to organize the workshop hopefully on the first days on August. I've already found the mentors and conference hall for the event. The marketing part is left, so I'm waiting for response :)

**Comment by riyadhalnur** [comment]
@lavriv92  I've sent an invite to @itspoma to join the lviv team. I've also made you the maintainer of the lviv team. Cheers :)

**Comment by itspoma** [comment]
@riyadhalnur accepted invitation, ty!
