### ISSUE TITLE
Add new member to SPB chapter

### ISSUE THREAD

**Issue by marinintim** [nodeschool/organizers#475]
We need to add @zeckson to @nodeschool/spb. Apparently, @nodeschoolbot is still down, and apparently I lack permission to invite to the organization.

@riyadhalnur, maybe you could help with that?

**Comment by riyadhalnur** [comment]
@marinintim I've sent out an invite to @zeckson to join the spb team. Cheers :)

**Comment by zeckson** [comment]
@riyadhalnur got the invite. Thank you! This issue may be closed.

**Comment by marinintim** [comment]
@riyadhalnur: thank you again! :+1:
