### ISSUE TITLE
New chapter: Guatemala City, Guatemala

### ISSUE THREAD

**Issue by delaguilaluis** [nodeschool/organizers#476]
Hi, I would like to start a nodeschool chapter for Guatemala City. I am @delaguilaluis on twitter and work at Xoom, a PayPal service. I will be co-organizing this chapter with @osukaa and @milsosa. I have been using Node.js for 2 years and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @delaguilaluis, I created the Guatemala team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/guatemala. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by delaguilaluis** [comment]
Thanks @riyadhalnur! I already accepted the invitation and I can see the repo. 😄
