### ISSUE TITLE
Adding a new organizer for San Francisco

### ISSUE THREAD

**Issue by jedireza** [nodeschool/organizers#477]

**Comment by jedireza** [comment]
@nodeschoolbot add @tlhunter @nodeschoool/sanfrancisco

**Comment by jedireza** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
@jedireza The bot is down. You will need to add a new organiser manually.

**Comment by jedireza** [comment]
@riyadhalnur I can add someone to our team, but if they're not a member of the @nodeschool org, I cannot. How can I add someone to the org manually?

<img width="474" alt="screen shot 2017-08-09 at 8 52 34 am" src="https://user-images.githubusercontent.com/979929/29130979-368cae2a-7ce0-11e7-929c-b6803665e8db.png">

**Comment by riyadhalnur** [comment]
I have sent @tlhunter an invite to join the San Fran team

**Comment by jedireza** [comment]
🙏 Thanks. So I take it only some people can do this manually? Can you get me those permissions?

**Comment by riyadhalnur** [comment]
You should have the permissions now. Check and let me know. Cheers.

**Comment by jedireza** [comment]
I'm unable to invite people to join the @nodeschool org. Same disabled screen for adding to the team if they're not in the org yet.

<img width="476" alt="screen shot 2017-08-09 at 9 12 29 am" src="https://user-images.githubusercontent.com/979929/29131870-161eac30-7ce3-11e7-8805-6b8b9d895df6.png">

**Comment by riyadhalnur** [comment]
Ah I think then you would have to be an owner of the nodeschool org to be able to do that.

**Comment by jedireza** [comment]
Okie dokie.
