### ISSUE TITLE
new organizer and chapter in Tabriz,Iran

### ISSUE THREAD

**Issue by mrfarhadir** [nodeschool/organizers#478]
Hi , I'm Farhad Mehryari Full stack developer and web technologies teacher 
I would like to start a nodeschool chapter for Tabriz city to introduce it to our programmers and also university IT students 
here is my own website http://mrfarhad.ir
and here is my another website for teaching nodejs in persian language 
http://learnodejs.ir

**Comment by mrfarhadir** [comment]
why there is no answer for this issue ?

**Comment by riyadhalnur** [comment]
Hi @mrfarhadir, that's awesome. I will create the chapter for you tonight.

**Comment by mrfarhadir** [comment]
Thanks U @riyadhalnur

**Comment by mrfarhadir** [comment]
how I could be added to `chapter-organizers` Team ?

**Comment by riyadhalnur** [comment]
Once I create the chapter, you'll be added to the group.

**Comment by riyadhalnur** [comment]
Hi @mrfarhadir, the Tabriz chapter already exists so I have created the team and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/tabriz. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by mrfarhadir** [comment]
Thanks for your invitation @riyadhalnur . now am I able to add new chapter ? 
or I just could modify Tabriz chapter?

**Comment by riyadhalnur** [comment]
You can now modify the Tabriz chapter.

**Comment by mrfarhadir** [comment]
And one thing more , I saw Iran's chapter that both of contributes was not Iranian could I have access for that chapter too ?

**Comment by riyadhalnur** [comment]
If the members of those chapters are active, best if you contact them directly.

**Comment by mrfarhadir** [comment]
their last commit was 7 month ago ! ok I try to get in touch with them I hope I success 
Thanks U again @riyadhalnur

**Comment by riyadhalnur** [comment]
Welcome 😃 . Closing this now. Feel free to reopen should you have other questions.
