### ISSUE TITLE
Creating Chapter for TLV (Israel)

### ISSUE THREAD

**Issue by EladKeyshawn** [nodeschool/organizers#479]
Hi, I'd like to start a nodeschool chapter for Tel Aviv!
I am @EladKeyshawn,I have been using Node.js for quite some time now at work (@giftwizard), contributing to OSS like @kiwix and for personal projects as well. And so I would really like to help others learn as well as creating good community together.
I'm currently looking for co-organizers but I think that'll be easy to find. 
All the best 😄

**Comment by EladKeyshawn** [comment]
@riyadhalnur ?

**Comment by riyadhalnur** [comment]
Hi @EladKeyshawn, that's awesome. I will create the chapter for you tonight.

**Comment by EladKeyshawn** [comment]
@riyadhalnur great thanks!

**Comment by EladKeyshawn** [comment]
@riyadhalnur Any progress?

**Comment by riyadhalnur** [comment]
Hi @EladKeyshawn, I created the Tel Aviv team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/telaviv. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.
