### ISSUE TITLE
Add nodeschool/montreal to Netlify for CD system

### ISSUE THREAD

**Issue by matchai** [nodeschool/organizers#490]
Howdy Nodeschol! 🤠

Over at [nodeschool/montreal](https://github.com/nodeschool/montreal) we're [implementing i18n](https://github.com/nodeschool/montreal/pull/43) to give equal opportunity to our English and French students. Because our jekyll stack will need some fancier plugins to get the job done, we found the easiest solution would be to hook the app up to Netlify to build and host our jekyll site.

Unfortunately, I don't have the rights to add Netlify as a GitHub integration to nodeschool/montreal. If someone can get the necessary wiring done on the Netlify side of things, or grant me the appropriate rights, that would be much appreciated! 😄

**Comment by riyadhalnur** [comment]
Hi there @matchai, you have admin access to the Montreal repo already. AFAIK, enabling netlify access would grant them access to all repos in the Nodeschool org. If possible, you can maybe add the webhook and deploy key manually to the Montreal repo itself or I can ad it for you.

**Comment by matchai** [comment]
It looks like their docs suggest enabling the "Restrict third-party application access", if adding Netlify to an org's repo:
https://www.netlify.com/docs/github-permissions/#restrict-access-for-organizations

Unfortunately I don't have access to any webhooks or deploy keys before completing the repo-selection flow.

**Comment by riyadhalnur** [comment]
Ah ok. Maybe you can add me to the team in Netlify and I can set up the pipeline. Would that work?

**Comment by matchai** [comment]
Unfortunately I can't create a team on the free tier.
I believe that in open-source projects, you can add unlimited contributors to a site, but you can't create a team for them.

Would you be able to create the site on Netlify?

**Comment by ajmas** [comment]
Travis and Circle CI have worked for me. For hosting we could use GitHub, by having the generated results put into a specific branch of the GitHub repo?

We use Travis to deploy to Heroku, for the https://github.com/maison-notman-house/notman-api-server project, though Travis can do anything you want. Circle CI was used for another project, since thy allowed free builds for closed source, with certain restrictions.

**Comment by RichardLitt** [comment]
We could always ask Netlify to help us out here, too. @matchai Have you tried contacting them, mentioning that you're trying to get this working for NodeSchool?

**Comment by matchai** [comment]
Looks like we've gotten our CI wired up on Jenkins instead of Netlify with this ticket: 
https://github.com/nodeschool/montreal/issues/66

Cheers 👍
