### ISSUE TITLE
New chapter: nodeschool passau

### ISSUE THREAD

**Issue by huberv** [nodeschool/organizers#491]
Hi, 
I'd like to start a new chapter located in Passau (that's in south-west Germany).

My twitter handle is [@FollowValentin](https://twitter.com/FollowValentin).

I work for msg systems (www.msg.group), am part of the technical guidance team and like to push node by giving interested people (like students from the university nearby) the chance to come together and get hands-on experience with JavaScript and node.

Co-founders of the nodeschool passau will be [@lechnerc77](https://twitter.com/lechnerc77), [@otmarjatsch](https://twitter.com/otmarjatsch) and [@kandlinf](https://twitter.com/kandlinf).

Kind regards,
Valentin

**Comment by huberv** [comment]
Hi all, any news regarding the chapter setup? Is there anything you need from my side?

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user huberv

**Comment by riyadhalnur** [comment]
Hi @huberv, sorry about the delay. Nodeshool bot is down it seems. Will get back to you once I get it fixed and get it back up and running again.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user huberv

**Comment by riyadhalnur** [comment]
Sorry @undefined. You are not allowed to do that if you are not a member of the `chapter-organizers` team

**Comment by riyadhalnur** [comment]
Sorry @undefined. You are not allowed to do that if you are not a member of the `chapter-organizers` team

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user huberv

**Comment by riyadhalnur** [comment]
I have added @huberv to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team passau

**Comment by riyadhalnur** [comment]
I have created @nodeschool/passauteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo passau

**Comment by riyadhalnur** [comment]
I have created a new repo called [passau](https://github.com/nodeschool/passau)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user passau huberv

**Comment by riyadhalnur** [comment]
I have invited @huberv to the `passau` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user passau lechnerc77

**Comment by riyadhalnur** [comment]
I have invited @lechnerc77 to the `passau` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user passau otmarjatsch

**Comment by riyadhalnur** [comment]
I have invited @otmarjatsch to the `passau` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user passau kandlinf

**Comment by riyadhalnur** [comment]
Hi @huberv, I created the Passau team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/passau. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by huberv** [comment]
add-user hafnerv

**Comment by huberv** [comment]
@nodeschoolbot add-team-user passau hafnerv

**Comment by riyadhalnur** [comment]
I have invited @hafnerv to the `passau` team.

**Comment by riyadhalnur** [comment]
Closing this issue. Please feel free to reopen if premature.
