### ISSUE TITLE
New chapter organizer

### ISSUE THREAD

**Issue by ELyounes** [nodeschool/organizers#494]
Hello, I would like to start a nodeschool chapter for nodeschool morocco. I am Younes EL kasri @younes_el_kasri on twitter and work at systemantic.net on developing software and solutions to businesses in the country. I will be co-organizing this chapter with Mohamed Lazhari Alaoui. I have been using Node.js for 3 years and would like to help people around the country to discover and learn node.js and to get better skills on it, this going to help them improve their situation.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user ELyounes

**Comment by riyadhalnur** [comment]
I have added @ELyounes to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
Hi @ELyounes, it's awesome you want to open a chapter but we recommend you open a chapter for a particular city in your country. Let me know what city you want to open a chapter for and I can continue creating it for you.

**Comment by ELyounes** [comment]
Hi @riyadhalnur Thanks for your quick answer so , I would like to create a chapter in the city of Marrakesh and if possible in Rabat too, since we are active in both cities. Many thanks

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team marrakesh

**Comment by riyadhalnur** [comment]
I have created @nodeschool/marrakeshteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo marrakesh

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user marrakesh ELyounes

**Comment by riyadhalnur** [comment]
I have invited @ELyounes to the `marrakesh` team.

**Comment by riyadhalnur** [comment]
Hi @ELyounes, I created the Marrakesh team and repo and invited you. Please accept the invite and let me know if everything is good on your side. Additionally, please provide the usernames of your other co-organisers or you can add them also using the NodeSchool Bot. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/marrakesh. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
