### ISSUE TITLE
New chapter request. Node School for Karachi, Pakistan

### ISSUE THREAD

**Issue by AhsanAyaz** [nodeschool/organizers#496]
Hi, I would like to start a nodeschool chapter for Karachi, Pakistan. I am @ahsan_ayz on twitter and I work as a Sr. Full Stack Engineer at [Modus Create](moduscreate.com) . I will be co-organizing this chapter with Mohammad Kamran Qadri. I have been using Node.js for around 4.5 years & would like to help others learn as well. 
You can look into my [github account](https://github.com/ahsanayaz) for some examples of my past work & open source contributions.
I already have written some blogs revolving around NodeJS & Angular. I also started a [youtube series](https://www.youtube.com/channel/UCc8Q1SMwcB_j7g731hAbLow) on MEAN stack in URDU/Hindi language so people who understand these languages (also my mother tongue) can learn NodeJS easily. 
Looking forward to a response :) Thanks

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user AhsanAyaz

**Comment by riyadhalnur** [comment]
I have added @AhsanAyaz to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team karachi

**Comment by riyadhalnur** [comment]
I have created @nodeschool/karachiteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo karachi

**Comment by riyadhalnur** [comment]
I have created a new repo called [karachi](https://github.com/nodeschool/karachi)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user karachi AhsanAyaz

**Comment by riyadhalnur** [comment]
I have invited @AhsanAyaz to the `karachi` team.

**Comment by riyadhalnur** [comment]
Hi @AhsanAyaz, I created the Karachi team and repo and invited you. Please accept the invite and invite your co-organisers and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/karachi. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
