### ISSUE TITLE
Gomel chapter

### ISSUE THREAD

**Issue by boccob** [nodeschool/organizers#498]
Hi, I would like to start a nodeschool chapter for Gomel. I am @_boccob on twitter. I will be co-organizing this chapter with @mikhail-hatsilau, @DioDread and @ShuhratBek. I have been using Node.js for 4 years and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user boccob

**Comment by riyadhalnur** [comment]
I have added @boccob to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team gomel

**Comment by riyadhalnur** [comment]
I have created @nodeschool/gomelteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo gomel

**Comment by riyadhalnur** [comment]
I have created a new repo called [gomel](https://github.com/nodeschool/gomel)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user gomel boccob

**Comment by riyadhalnur** [comment]
I have invited @boccob to the `gomel` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user gomel mikhail-hatsilau

**Comment by riyadhalnur** [comment]
I have invited @mikhail-hatsilau to the `gomel` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user gomel DioDread

**Comment by riyadhalnur** [comment]
I have invited @DioDread to the `gomel` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user gomel ShuhratBek

**Comment by riyadhalnur** [comment]
I have invited @ShuhratBek to the `gomel` team.

**Comment by riyadhalnur** [comment]
Hi @boccob, I created the Gomel team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/gomel. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
