### ISSUE TITLE
chapter request

### ISSUE THREAD

**Issue by codeekage** [nodeschool/organizers#499]
Hi, I would like to start a nodeschool chapter for Port Harcourt, River State, Nigeria. I am @codeekage on twitter and currently a free-bird-dev. I will be co-organizing this chapter with Gabriel Eze. I have been using Node.js for 4 months and would like to help others learn as well.
The chapter name should preferably be portharcourtcity, where the workshops will be held, the repo name should be portharcourtcity.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user codeekage

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user codeekage

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user codeekage

**Comment by riyadhalnur** [comment]
I have added @codeekage to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo portharcourtcity

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team portharcourtcity

**Comment by riyadhalnur** [comment]
I have created @nodeschool/portharcourtcityteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user portharcourtcity codeekage

**Comment by riyadhalnur** [comment]
I cannot find the team `portharcourtcity`

**Comment by riyadhalnur** [comment]
I have invited @codeekage to the `portharcourtcity` team.

**Comment by codeekage** [comment]
Good day there!

We here at portharcourtcity NodeSchool we'll love to host our first meet up
in February. So we can get devs and soon to be devs involved in the
community.

We will also like to know what support we can get from NodeSchool towards
organizing the first official meet up in Nigeria, Rivers , Port Harcourt.

We will also love to get started with NodeBots Nigeria as not many are so
familiar with JavaScript being  a language for NextGeneration robotics.

Thanks for your anticipated support.

Regards
Agiri Abraham Junior @codeekage.

On Jan 17, 2018 10:47 AM, "Riyadh Al Nur" <notifications@github.com> wrote:

Here is what I can do for you:

   - help - shows this help
   - create-repo {name} - creates a nodeschool repo
   - add-user {username} - adds a user to the chapter-organizers team and
   the org
   - create-team {team} - creates a new team
   - add-team-user {team} {username} - add a user to a specific team

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nodeschool/organizers/issues/499#issuecomment-358251533>,
or mute the thread

**Comment by codeekage** [comment]
Please walk me through getting portharcourtcity chapter listed out on nodeschool.io.

**Comment by codeekage** [comment]
-help

**Comment by riyadhalnur** [comment]
You have to create a PR in the `nodeschool.github.io` repo to list the chapter on the site. An example PR can be found here [https://github.com/nodeschool/nodeschool.github.io/pull/597/files](https://github.com/nodeschool/nodeschool.github.io/pull/597/files)

**Comment by riyadhalnur** [comment]
Closing this. Feel free to reopen if premature.
