### ISSUE TITLE
Chapter request for Tallinn, Estonia

### ISSUE THREAD

**Issue by yasinaydin** [nodeschool/organizers#500]
Hello all
I am Yasin. I was one of the organizers and mentors of NodeSchool Istanbul.
I also created node.ist and a member of Node.js/Linux foundations.
Now I am living in Estonia and already co-organized a Node.js event here.

I want to create NodeSchool Tallinn, Estonia chapter and do meetings here.
Could someone help me on how to proceed?

Thanks!

**Comment by riyadhalnur** [comment]
Hi @yasinaydin, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by yasinaydin** [comment]
I have one ultimate and 2 potential co-organizers to start, and few potential sponsors for events.

**Comment by riyadhalnur** [comment]
Could you tag them here? I can then move ahead and create the chapter for you or would you like to add them yourself afterwards?

**Comment by yasinaydin** [comment]
I can add them afterwars too, if that's alright!

**Comment by riyadhalnur** [comment]
Sure thing. I'll create the chapter and team for you asap. 😃

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user yasinaydin

**Comment by riyadhalnur** [comment]
I have added @yasinaydin to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team tallinn

**Comment by riyadhalnur** [comment]
I have encountered an error doing this :(

```
Error: Bad status: 422
    at Request._callback (/home/nowuser/src/bin.js:266:50)
    at Request.self.callback (/home/nowuser/src/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team tallinn

**Comment by riyadhalnur** [comment]
@yasinaydin A chapter with the same name already seems to exist. Please get in touch with the co-organisers of the current team in order for them to grant you access.

**Comment by yasinaydin** [comment]
@riyadhalnur will do, thanks!

**Comment by riyadhalnur** [comment]
Sorry, I closed it by mistake. Feel free to close when it's resolved.

**Comment by riyadhalnur** [comment]
Thank you @martinraag. That's awesome! 😃 . Closing this issue.
