### ISSUE TITLE
chapter request for coimbatore,INDIA

### ISSUE THREAD

**Issue by madhusona** [nodeschool/organizers#501]
Hi, nodeschool resources are good. I deployed Autobots on facebook and telegram using nodejs. Now I am interested to teach nodejs to my students so I would like to start a nodeschool chapter for Coimbatore, Tamilnadu, India. I will be co-organizing this chapter with Balakrishnan [ @balasv ].

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user madhusona

**Comment by riyadhalnur** [comment]
I have added @madhusona to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team coimbatore

**Comment by riyadhalnur** [comment]
I have created @nodeschool/coimbatoreteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo coimbatore

**Comment by riyadhalnur** [comment]
I have created a new repo called [coimbatore](https://github.com/nodeschool/coimbatore)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user coimbatore madhusona

**Comment by riyadhalnur** [comment]
I have invited @madhusona to the `coimbatore` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user coimbatore balasv

**Comment by riyadhalnur** [comment]
I have invited @balasv to the `coimbatore` team.

**Comment by riyadhalnur** [comment]
Hi @madhusona, I created the Coimbatore  team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/coimbatore. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
