### ISSUE TITLE
Miami Chapter

### ISSUE THREAD

**Issue by ciolt** [nodeschool/organizers#503]
Hi, I would like to contribute to the NodeSchool chapter for Miami. I am [@Bryan_Agredo](https://twitter.com/Bryan_Agredo) on Twitter and work on a project called [AmpTweet](https://github.com/amptweet/amptweet-web). I want to help contribute to this chapter since Miami's chapter seems to be very inactive. I have been using Node.js for about 6 months and been a front-end web developer for 3 years and I would like to help others learn as well. 

Why do I want to help co-organize the Miami chapter? I want to be a leader in my community and truly make a difference for those entering the growing Miami tech scene. What better way to do it than by doing something I love -- JavaScript and the satisfaction of teaching others.

**Comment by ciolt** [comment]
Is anyone able to add me as an organizer to the NodeSchool Miami GitHub repo?

**Comment by ciolt** [comment]
Any help? @nizaroni

**Comment by riyadhalnur** [comment]
I think it's better to open this issue to open in the @nodeschool/miami  chapter issues itself.

**Comment by ciolt** [comment]
The group organizer hasn't been active on GitHub in years, and I can't contact him. Putting an issue on the DEAD Miami chapter would be like talking to a wall.
