### ISSUE TITLE
Start new chapter, Uzhhorod Ukraine

### ISSUE THREAD

**Issue by YuraDerevenko** [nodeschool/organizers#506]
Hi, I would like to start a nodeschool chapter for Uzhhorod, Ukraine. I am @YuriiDerevenko on twitter and work at SharpMinds (http://www.sharpminds.com).
 I will be co-organizing this chapter with [
https://github.com/darkvas,
@ivan_lyakh
].
 I have been using Node.js for 3 years and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user YuraDerevenko

**Comment by riyadhalnur** [comment]
I have added @YuraDerevenko to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team uzhhorod

**Comment by riyadhalnur** [comment]
I have created @nodeschool/uzhhorodteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo uzhhorodteam

**Comment by riyadhalnur** [comment]
I have created a new repo called [uzhhorodteam](https://github.com/nodeschool/uzhhorodteam)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user uzhhorod YuraDerevenko

**Comment by riyadhalnur** [comment]
I cannot find the team `uzhhorod`

**Comment by riyadhalnur** [comment]
I have invited @YuraDerevenko to the `uzhhorod` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user uzhhorod darkvas

**Comment by riyadhalnur** [comment]
I cannot find the team `uzhhorod`

**Comment by riyadhalnur** [comment]
I have invited @darkvas to the `uzhhorod` team.

**Comment by riyadhalnur** [comment]
Hi @YuraDerevenko, I created the Uzhhorod team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/uzhhorod. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
