### ISSUE TITLE
Start A New Chapter in Abuja Nigeria

### ISSUE THREAD

**Issue by inidaname** [nodeschool/organizers#507]
Hello
I am an Abuja based Node Developer and I will like to start the Abuja Nodeschool.

I will like to be able to connect the Node Developers in my community

**Comment by codeekage** [comment]
Awesome!

**Comment by inidaname** [comment]
@codeekage @nodeschoolbot I will like you to guide me so far what you have done for Port Harcut and possible collaboration on making Nigeria NodeJs community

**Comment by riyadhalnur** [comment]
Sorry @inidaname. You are not allowed to do that if you are not a member of the `chapter-organizers` team

**Comment by inidaname** [comment]
@riyadhalnur may I request for a link on how to be a member if it possible thank you

**Comment by inidaname** [comment]
@riyadhalnur I will formally open another issue requesting for `chapter-organizers` membership

**Comment by codeekage** [comment]
Hola! I'm NodeSchool Orgainzer portharcourtcity looking forward to woking with you! 

Cheers!
