### ISSUE TITLE
Start new chapter, Cascais, Portugal

### ISSUE THREAD

**Issue by telmocontreiras** [nodeschool/organizers#509]
Hi, I would like to start a nodeschool chapter for [linha-de-cascais], in Portugal. I am @TelmoContreiras on twitter and work at SyndicateRoom Ltd. I have been using Node.js for 6 months and would like to help others learn as well, including members of my team at SyndicateRoom.

Thanks,
Telmo

**Comment by riyadhalnur** [comment]
Hi @telmocontreiras, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by telmocontreiras** [comment]
Hi @riyadhalnur, my colleagues @fcferreira1985, @carloslpmp, @FelipeGN85, @ademircps, @DidFavas, and @diogomrpt will be co-organizing :)

**Comment by telmocontreiras** [comment]
@riyadhalnur Updated with github handles. Cheers

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user telmocontreiras

**Comment by riyadhalnur** [comment]
I have added @telmocontreiras to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team cascais

**Comment by riyadhalnur** [comment]
I have created @nodeschool/cascaisteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo cascais

**Comment by riyadhalnur** [comment]
I have created a new repo called [cascais](https://github.com/nodeschool/cascais)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais telmocontreiras

**Comment by riyadhalnur** [comment]
I have invited @telmocontreiras to the `cascais` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais fcferreira29

**Comment by riyadhalnur** [comment]
I have invited @fcferreira29 to the `cascais` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais CarlosLeandroPT

**Comment by riyadhalnur** [comment]
I have invited @CarlosLeandroPT to the `cascais` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais Felipe-GN

**Comment by riyadhalnur** [comment]
I have invited @Felipe-GN to the `cascais` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais ademircps

**Comment by riyadhalnur** [comment]
I have invited @ademircps to the `cascais` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais pedrodgbaptista

**Comment by riyadhalnur** [comment]
I have invited @pedrodgbaptista to the `cascais` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais DavidMonteiroPereira

**Comment by riyadhalnur** [comment]
I have invited @DavidMonteiroPereira to the `cascais` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais diogomrodrigues

**Comment by riyadhalnur** [comment]
I have invited @diogomrodrigues to the `cascais` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user cascais zemworld

**Comment by riyadhalnur** [comment]
I have encountered an error doing this :(

```
Error: Bad status: 404
    at Request._callback (/home/nowuser/src/server.js:344:17)
    at Request.self.callback (/home/nowuser/src/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by riyadhalnur** [comment]
Hi @telmocontreiras, I created the Cascais team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. I apologise for the delay in creating the chapter. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/cascais. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by telmocontreiras** [comment]
Thanks Riyhadh, will do.


Best regards,

*--*

*Telmo Contreiras*

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by telmocontreiras** [comment]
add-team-user cascais  CarlosLeandroPT
