### ISSUE TITLE
Notice of Duplicate nodeschool Abuja

### ISSUE THREAD

**Issue by inidaname** [nodeschool/organizers#511]
I noticed we have 2 Nodeschool Abuja, can I request we merge the membership to one team so we don't get confused on which one is.
Abuja, Ng and Abuja are all the same we only have one Abuja in Nigeria I don't know if it will be okay with both the organizers to merge the team and plan things together so we can have a genuine community in the City

cc @ldbraun @savicsly @riyadhalnur

**Comment by ldbraun** [comment]
It's alright. Let's go ahead and merge em.

Regards.

Braun Boniface
CTO - Chief Technology Officer.
Okoi Studios
From: Hassan Sani
Sent: Sunday, 18 February 2018 23:16
To: nodeschool/organizers
Reply To: nodeschool/organizers
Cc: Braun Okoi Boniface; Mention
Subject: [nodeschool/organizers] Notice of Duplicate nodeschool Abuja (#511)



I noticed we have 2 Nodeschool Abuja, can I request we merge the membership to one team so we don't get confused on which one is.
Abuja, Ng and Abuja are all the same we only have one Abuja in Nigeria I don't know if it will be okay with both the organizers to merge the team and plan things together so we can have a genuine community in the City

cc @ldbraun<https://github.com/ldbraun> @savicsly<https://github.com/savicsly> @riyadhalnur<https://github.com/riyadhalnur>

**Comment by inidaname** [comment]
I have contacted @savicsly via email we need to have his attention on this

**Comment by inidaname** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by riyadhalnur** [comment]
Closing this issue. Feel free to re-open if premature.
