### ISSUE TITLE
Start new chapter, Ilorin Nigeria

### ISSUE THREAD

**Issue by jalasem** [nodeschool/organizers#512]
Hi, I kickstarted my node career 2 years ago with nodeschool resources and I found them awesome and great. I am currently the developer of steemgigs and CEO at Nerd Garage. I'm interested in teaching nodejs to my students and creating nodeschool workshops in my city, Ilorin Nigeria. I am @jalasem on facebook, @ajalaabdulsamii on twitter and I will be co-organizing this chapter with 
`[{name: 'Jatto AbdulQahar', github: 'jattoabdul', works_at: 'Andela, Nigeria'}, {name: 'Yusuf Kamaldeen', github: 'kenkarmah', works_at: 'Malhub, Ilorin'}]`

**Comment by inidaname** [comment]
@jalasem Happy to see this coming up 2 cities already Nigeria is growing, now seriously excited about the future of Node Devs in Nigeria cc @riyadhalnur

**Comment by MylesBorins** [comment]
🎉

**Comment by codeekage** [comment]
@jalasem when you get approved open an issue on https://github.com/NodeJSAfrica/nodeschool-organizers to be added to committee planning Node in Africa Conf. 

Cheers

**Comment by jalasem** [comment]
@codeekage, @inidaname, @MylesBorins, @riyadhalnur thank you so much. 
It will be a great pleasure putting my city on the map with our contributions and active participation

**Comment by inidaname** [comment]
We look forward to this please click the link @codeekage added and let's bring Africa on the Map

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user jalasem

**Comment by riyadhalnur** [comment]
I have added @jalasem to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team ilorin

**Comment by riyadhalnur** [comment]
I have created @nodeschool/ilorinteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo ilorin

**Comment by riyadhalnur** [comment]
I have created a new repo called [ilorin](https://github.com/nodeschool/ilorin)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user ilorin jalasem

**Comment by riyadhalnur** [comment]
I have invited @jalasem to the `ilorin` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user ilorin jattoabdul

**Comment by riyadhalnur** [comment]
I have invited @jattoabdul to the `ilorin` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user ilorin kenkarmah

**Comment by riyadhalnur** [comment]
I have invited @kenkarmah to the `ilorin` team.

**Comment by riyadhalnur** [comment]
Hi @jalasem, I created the Ilorin team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/ilorin. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
