### ISSUE TITLE
Start New Chapter, Kano Nigeria

### ISSUE THREAD

**Issue by Timtech4u** [nodeschool/organizers#514]
Hi, I would like to start a nodeschool chapter for Kano. I am @timtech4u on twitter and work at FlexiSAF Edusoft Ltd. I have been using Node.js for over a year and would like to help others learn as well.

**Comment by inidaname** [comment]
@Timtech4u Happy to see this coming up and really excited about the future of Node Devs in Nigeria cc @riyadhalnur

**Comment by codeekage** [comment]
when you get approved open an issue on https://github.com/NodeJSAfrica/nodeschool-organizers to be added to the committee planning Node in Africa Conf.

Cheers

**Comment by riyadhalnur** [comment]
Hi @Timtech4u, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by Timtech4u** [comment]
Hi @riyadhalnur , Sure we do have ahmedin01@gmail.com and 25ambat25@gmail.com, they are awesome contributors to the tech ecosystem here in Kano and are readily available.

**Comment by riyadhalnur** [comment]
@Timtech4u could you specify their GitHub handles?

**Comment by inidaname** [comment]
@Timtech4u please let us know when your first event is happening will like
to attend.

Very happy to see this coming up

**Comment by Timtech4u** [comment]
Hi @riyadhalnur , their github handles are @amazingneotech and @ambat25
Thanks.

@inidaname  Sure, you'll be informed. ;-)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user Timtech4u

**Comment by riyadhalnur** [comment]
I have added @Timtech4u to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team kano

**Comment by riyadhalnur** [comment]
I have created @nodeschool/kanoteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo kano

**Comment by riyadhalnur** [comment]
I have created a new repo called [kano](https://github.com/nodeschool/kano)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user kano Timtech4u

**Comment by riyadhalnur** [comment]
I have invited @Timtech4u to the `kano` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user kano Amazingneotech

**Comment by riyadhalnur** [comment]
I have invited @Amazingneotech to the `kano` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user kano ambat25

**Comment by riyadhalnur** [comment]
I have invited @ambat25 to the `kano` team.

**Comment by riyadhalnur** [comment]
Hi @Timtech4u, I created the Kano team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/kano. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
