### ISSUE TITLE
Add @waleedashraf to organizers

### ISSUE THREAD

**Issue by WaleedAshraf** [nodeschool/organizers#516]
Hi,
I have been working on Nodejs for more than 2 years and now trying my best to give back to the community. I have joined NodeSchool Lahore, PK chapter to organize different events and to also help existing organizer @usmantahirr. We are working on to launch website ASAP and organize multiple events/workshops.

I request to add me as co-organizer in NodeSchool Org and NodeSchool Lahore repo. I'm @waleedashraf01 on twitter.

**Comment by usmantahirr** [comment]
Thanks @WaleedAshraf 
The chapter was idle for one complete year and I really wanted someone to help me renew it.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user WaleedAshraf

**Comment by riyadhalnur** [comment]
I have added @WaleedAshraf to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user lahore WaleedAshraf

**Comment by riyadhalnur** [comment]
I cannot find the team `lahore`

**Comment by riyadhalnur** [comment]
I have invited @WaleedAshraf to the `lahore` team.

**Comment by riyadhalnur** [comment]
@WaleedAshraf, I invited to the 2 teams. Cheers! 😃
