### ISSUE TITLE
Starting a new chapter: Milton Keynes, UK

### ISSUE THREAD

**Issue by edieblu** [nodeschool/organizers#517]
Hi,

I run regular bimonthly meetups for beginners in our [city](https://www.meetup.com/Girls-Code-Learn-to-Code-with-Other-Girls-and-Women/) as well as [Django Girls](https://djangogirls.org/miltonkeynes/) events. 

I'm looking to host NodeSchool workshops as well in the future.

We already have the venue, and there's a meetup co-organizer.

Please let me know if you need any other information.

Kind regards, 
Eva

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user edieblu

**Comment by riyadhalnur** [comment]
I have added @edieblu to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team miltonkeynes

**Comment by riyadhalnur** [comment]
I have created @nodeschool/miltonkeynesteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo miltonkeynes

**Comment by riyadhalnur** [comment]
I have created a new repo called [miltonkeynes](https://github.com/nodeschool/miltonkeynes)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user miltonkeynes edieblu

**Comment by riyadhalnur** [comment]
I have invited @edieblu to the `miltonkeynes` team.

**Comment by riyadhalnur** [comment]
Hi @edieblu, I created the Milton Keynes team and repo and invited you. Please accept the invite, invite your co-organiser and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/miltonkeynes. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by edieblu** [comment]
Excellent, thanks @riyadhalnur!
