### ISSUE TITLE
Noticed a global event for March 24th

### ISSUE THREAD

**Issue by inidaname** [nodeschool/organizers#518]
I just noticed a majority of events scheduled for **March 24th** I feel it will be a good idea if the organizers use the chance to do a twitter takeover with a uniform tweet hashtag 

I have a few suggestions below

- #nodejs
- #Nodeschool
- #NodeEvent

More suggestions are welcome

**Comment by riyadhalnur** [comment]
Closing this issue. Feel free to re-open if premature.
