### ISSUE TITLE
Start a New Chapter for Mumbai, India

### ISSUE THREAD

**Issue by rajmayank** [nodeschool/organizers#519]
Hey, I'm Mayank Raj, a web consultant from Mumbai India. Not very active on twitter, you can find my on FB - mayank9856. I've been using node for well over two years now. I'm a public speaker and speak on topics related to JS (recent one - nerdsummit, UMass Amherst)
I've been active in the local community here in Mumbai and we lack the official nodeschool group here. I'd like to take the initiative and start one so that we call can come together and learn together.

**Comment by riyadhalnur** [comment]
Hi, a chapter for [Mumbai](https://github.com/nodeschool/mumbai) already exists. I would suggest getting in touch with the current organisers of the chapter to take over/join the organising team.

**Comment by rajmayank** [comment]
The group you've linked to is virtually nonexistent. Also I've been trying to teach the currently organizer for a few month's now and have not heard back. Do let me known of the plan of action in this cases.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team mumbai

**Comment by riyadhalnur** [comment]
I have created @nodeschool/mumbaiteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user mumbai rajmayank

**Comment by riyadhalnur** [comment]
I have invited @rajmayank to the `mumbai` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user rajmayank

**Comment by riyadhalnur** [comment]
I have added @rajmayank to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
Hi @rajmayank, I've added you to the Mumbai repo and to the `chapter-organisers` team. Do inform the current organisers should they get back to you about this.

**Comment by PatrickHeneise** [comment]
@rajmayank @Ramakant701 is also interested setting up the Mumbai chapter: https://github.com/nodeschool/organizers/issues/546

I'll land in Mumbai on 23.11. and can help bootstrap the event from scratch, as long as you have a venue. Would be great if we could organise this for 24. or 25.11. What do you think?
