### ISSUE TITLE
.js does not exist

### ISSUE THREAD

**Issue by Hrc-33** [nodeschool/organizers#521]

**Comment by yasinaydin** [comment]
Is this spam? @riyadhalnur

**Comment by Hrc-33** [comment]
It says in my Command prompt when I want to verify task from nodeschool "javascripting" that it is erorr and that for-loop.js doesn't exist.. can You PLEASE help me?

**Comment by yasinaydin** [comment]
This might be wrong place for your problem. Have you tried this website?
https://stackoverflow.com/search?q=.js+does+not+exist

**Comment by finnp** [comment]
@Hrc-33 Could you copy/paste the entire output o the `javascripting` command? And what are you trying to run `javascripting verify for-loop.js`?

**Comment by Hrc-33** [comment]
![image](https://user-images.githubusercontent.com/20649538/38639987-35914256-3dd3-11e8-9d97-68f9bb6596e8.png)
![image](https://user-images.githubusercontent.com/20649538/38640034-56d5d670-3dd3-11e8-875a-ff4a0b8950fa.png)

**Comment by yasinaydin** [comment]
I still am not sure if nodeschool/organizers repo is the right place...

**Comment by finnp** [comment]
@yasinaydin Good point, didn't notice.

@Hrc-33 See #2288 for a reply :)
