### ISSUE TITLE
Chapter in Lima, Perú

### ISSUE THREAD

**Issue by lupomontero** [nodeschool/organizers#522]
Hi there,

I can see that there have been a couple of attempts at starting a Chapter in Lima, Perú, but I'm not sure if things got going in the end. I can see the chapter [is listed on the website](https://nodeschool.io/chapters.html) but when I follow the link to the Lima Chpater [the page it leads to appears to be some kind of template with dummy info](https://nodeschool.io/lima/).

I found two issues wrt the Lima Chapter:

* https://github.com/nodeschool/organizers/issues/373 by @ReinsBrain in Aug 27, 2016
* https://github.com/nodeschool/organizers/issues/380 by @ogsilvaa in Sep 19, 2016

Digging through the @nodeschool org on GitHub I found the [nodeschool/lima](https://github.com/nodeschool/lima) repo and posted a new issue there (https://github.com/nodeschool/lima/issues/8) but have not had a reply yet.

***

For context, I'm director of technology at @Laboratoria as well as being actively involved with @lima-js. Along with fellow local JavaScripters (@lizzie136, @wixo, @JoshDev1205, ...) we have been toying with the idea of organising a series of @nodeschool inspired events/workshops in Lima, so we'd like to offer help in re-activating the Lima chapter 💪 🚀

The [LimaJS](https://limajs.org/) group has been actively organising JavaScript meetups since early 2012, and on the other hand at [Laboratoria](http://www.laboratoria.la/) we regularly organise workshops and hackathons (for our students, alumni, instructors, ... and the general public).

Any feedback would be greatly appreciated.

Best,

L

**Comment by riyadhalnur** [comment]
There seems to be a reply on the issue you tagged from the Lima repo. I think the best course of action is to discuss with current organisers about how to go about handing it over if that is the case. Either way, we can pick this up once you guys have discussed the issue.

**Comment by lupomontero** [comment]
Ho @riyadhalnur, thanks for your reply 😃

The only reply I got so far in the [Lima repo](https://github.com/nodeschool/lima/issues/8) is from someone not involved as an organiser.

Based on previous issues and the [commit logs](https://github.com/nodeschool/lima/commits/master) on the Lima repo I believe the person in charge is @ogsilvaa, but haven't received any replies from him (yet).

**Comment by ogsilvaa** [comment]
I'm so excited to be able to expand the chapter of Lima. Currently we are 4 members here in Lima and we have made some presentations in centers. I hope we'll make with Laboratoria

**Comment by lupomontero** [comment]
Thanks for your reply @ogsilvaa. Now that the issue on the Lima repo has got going, we can continue the conversation over there: https://github.com/nodeschool/lima/issues/8

Closing this issue...
