### ISSUE TITLE
chapter proposal for nodeschool in San miguel , El Salvador

### ISSUE THREAD

**Issue by D3Portillo** [nodeschool/organizers#528]
Hi I am studying Systems Engineering at Universidad de El Salvador , I've been using nodejs since last year, I started talking to some friends about it then we started meeting up at pals house. But now we found this community and it will be really, but really nice if you let us get in, I don't have twitter just FB => @d3portillo

**Comment by riyadhalnur** [comment]
Hi @D3Portillo, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by DavidAlvarado0** [comment]
Hi, I'm studying systems engineering at the same university as him and I'll help him as co-organisers.

**Comment by riyadhalnur** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user D3Portillo

**Comment by riyadhalnur** [comment]
I have added @D3Portillo to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team sanmiguel

**Comment by riyadhalnur** [comment]
I have created @nodeschool/sanmiguelteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo sanmiguel

**Comment by riyadhalnur** [comment]
I have created a new repo called [sanmiguel](https://github.com/nodeschool/sanmiguel)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user sanmiguel D3Portillo

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @D3Portillo to the `sanmiguel` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user sanmiguel DavidAlvarado0

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @DavidAlvarado0 to the `sanmiguel` team.

**Comment by riyadhalnur** [comment]
Hi @D3Portillo, I created the San Miguel team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/sanmiguel. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by D3Portillo** [comment]
terrific, boom shakalaka boom, thank you for adding us, yay!

**Comment by Art3Aga** [comment]
I'll help them too

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel Art3Aga

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @Art3Aga to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel arnoldou

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @arnoldou to the `sanmiguel` team.
