### ISSUE TITLE
Starting new chapter in Delhi-NCR, India

### ISSUE THREAD

**Issue by sambhav2612** [nodeschool/organizers#529]
Hi, I would like to start a nodeschool chapter for Delhi-NCR, India. I am sambhavvjain on Twitter and work on OSS projects. I will be co-organizing this chapter with @coderwassananmol. I have been using Node.js for 5 months and would like to help others learn as well. I also organize the regional Jenkins CI club.

**Comment by sambhav2612** [comment]
Also, I've been known to the fact that the chapter already exists but it is somewhat inactive hence this step should mean more of a starting point of the chapter with new organizers.

**Comment by riyadhalnur** [comment]
Hi @sambhav2612, since the chapter already exists, it's better to get in touch with the current organisers and discuss handing over responsibility to you or adding you to their team.

**Comment by sambhav2612** [comment]
The issue is with that only,  I tried establishing contact with the
existing organisers but no email/phone/address was found to accomplish the
same. Last time I checked, the website was down.

On Jun 4, 2018 2:21 PM, "Riyadh Al Nur" <notifications@github.com> wrote:

Closed #529 <https://github.com/nodeschool/organizers/issues/529>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nodeschool/organizers/issues/529#event-1660734869>, or mute
the thread

**Comment by riyadhalnur** [comment]
Sorry to hear that. Could you try opening an issue on the chapter repo. Maybe that'll help. If after some time, they don't respond, we can think of something to do.

**Comment by sambhav2612** [comment]
Sure. Will do.

On Jun 4, 2018 2:26 PM, "Riyadh Al Nur" <notifications@github.com> wrote:

Sorry to hear that. Could you try opening an issue on the chapter repo.
Maybe that'll help. If after some time, they don't respond, we can think of
something to do.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nodeschool/organizers/issues/529#issuecomment-394282780>,
or mute the thread

**Comment by sambhav2612** [comment]
So, I made an issue as soon as it was suggested and haven't heard from them
since. Therefore, I think we can move ahead with this one now.

**Comment by sambhav2612** [comment]
cc @riyadhalnur
