### ISSUE TITLE
New Chapter in Kaduna

### ISSUE THREAD

**Issue by savicsly** [nodeschool/organizers#530]
Hi, I would like to start a nodeschool chapter for Kaduna. I am @savics on twitter and work at Bingham University.  I have been using Node.js for over a year now and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Hi @savicsly, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by savicsly** [comment]
Hello @riyadhalnur not at the moment, but will make arrangement for that very soon.

**Comment by D3Portillo** [comment]
will be closed, please answer

**Comment by savicsly** [comment]
At the moment I don't but I have spoken to someone who is interested but
has not given the answer yet. But should be able to get him and another as
soon as we start.

Best regards

**Comment by D3Portillo** [comment]
Can a single co-organizer answer? , please, so we can proceed

**Comment by savicsly** [comment]
there is no co-organizer for now. i am the only one.

**Comment by inidaname** [comment]
Awesome @savicsly and @MicahBala, Looking forward to seeing the node community grow in Kaduna, your neighbor Abuja community is ready to work with you

**Comment by savicsly** [comment]
thank you @inidaname

**Comment by savicsly** [comment]
@riyadhalnur @D3Portillo I am still awaiting your response.

**Comment by riyadhalnur** [comment]
Is this still valid? Sorry for the late response

**Comment by savicsly** [comment]
Yes, it is, I've been waiting for your response all along. I've supplied the required co-organizer but didn't get any reply.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user savicsly

**Comment by riyadhalnur** [comment]
I have added @savicsly to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team kaduna

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo kaduna

**Comment by riyadhalnur** [comment]
I have encountered an error doing this :(

```
Error: Bad status: 422
    at Request._callback (/var/task/index.js:363:17)
    at Request.self.callback (/var/task/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/var/task/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user kaduna savicsly

**Comment by riyadhalnur** [comment]
I have invited @savicsly to the `kaduna` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user kaduna MicahBala

**Comment by riyadhalnur** [comment]
I have invited @MicahBala to the `kaduna` team.

**Comment by riyadhalnur** [comment]
Hi @savicsly, I created the Kaduna team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/kaduna. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
* `create-chapter {name}` - creates a new chapter

**Comment by savicsly** [comment]
Thank you @riyadhalnur I will do all that shortly and reach out if I need any help.
