### ISSUE TITLE
New Chapter Request New Orleans, LA USA

### ISSUE THREAD

**Issue by dtdimart** [nodeschool/organizers#532]
Hi, I would like to start a nodeschool chapter for New Orleans, LA. I am @dtdimart on twitter and founded Dunwich Technologies. I will be organizing this chapter on my own, but will regularly collaborate with education groups in my area and am able to host at my Coworking space. I have been using Node.js for about 1 year, strongly in conjunction with ReactJS

Chapter Name: "nola"

**Comment by riyadhalnur** [comment]
Hi @dtdimart, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by dtdimart** [comment]
Yes

**Comment by riyadhalnur** [comment]
Could you mention them here? I will create the chapter for you later in the day then

**Comment by dtdimart** [comment]
@TechTalentSouth

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user dtdimart

**Comment by riyadhalnur** [comment]
I have added @dtdimart to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team nola

**Comment by riyadhalnur** [comment]
I have created @nodeschool/nolateam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo nola

**Comment by riyadhalnur** [comment]
I have created a new repo called [nola](https://github.com/nodeschool/nola)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user nola dtdimart

**Comment by riyadhalnur** [comment]
I cannot find the team `nola`

**Comment by riyadhalnur** [comment]
I have invited @dtdimart to the `nola` team.

**Comment by riyadhalnur** [comment]
Hi @dtdimart , I created the New Orleans team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/nola. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
