### ISSUE TITLE
New Chapter in Mossoró

### ISSUE THREAD

**Issue by aretw0** [nodeschool/organizers#534]
Hi, I would like to start a nodeschool chapter for Mossoró. I am @aretw0 on twitter and study at the Semi-arid Federal Rural University in Mossoró, Brazil. I will be co-organizing this chapter with @igorfs042 and @allefrodrigo. I have been using Node.js for over a year and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Is this still valid? Sorry for the late response.

**Comment by aretw0** [comment]
Not right now, sorry. I was graduating back there and now working full time and in quarantine.
