### ISSUE TITLE
New Chapter Request Gran Canaria, Spain

### ISSUE THREAD

**Issue by sejas** [nodeschool/organizers#535]
Hi, I would like to start a nodeschool chapter for Gran Canaria. I am [@antoniosejas](https://twitter.com/antoniosejas) on twitter and work at Udacity.  I will be co-organizing this chapter with @sofiasz and other people who are responsable of my coworking but doesn't have a github account. I have been using Node.js for 5 years and now I want to help others learn as well.
IMO the best repo name would be : grancanaria or gran-canaria

Thank you !

**Comment by D3Portillo** [comment]
hi, who will be helping you ? , you need to have some co pals , maybe 1 or 2 more, thus we can proceed to create your team, can @sofiasz answer , please?

**Comment by sofiasz** [comment]
@D3Portillo We are currently two organizers. It's enough ?

**Comment by D3Portillo** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by D3Portillo** [comment]
@nodeschoobot add-user @sofiasz

**Comment by D3Portillo** [comment]
@nodeschoobot add-user sofiasz

**Comment by D3Portillo** [comment]
@nodeschoobot add-user sejas

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user sofiasz

**Comment by riyadhalnur** [comment]
I have added @sofiasz to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoobot add-user sejas

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user sejas

**Comment by riyadhalnur** [comment]
I have added @sejas to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot create-team gran-canaria

**Comment by riyadhalnur** [comment]
I have created @nodeschool/gran-canariateam

**Comment by D3Portillo** [comment]
@nodeschoolbot create-repo gran-canaria

**Comment by riyadhalnur** [comment]
I have created a new repo called [gran-canaria](https://github.com/nodeschool/gran-canaria)

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user gran-canaria sejas

**Comment by riyadhalnur** [comment]
I have invited @sejas to the `gran-canaria` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user gran-canaria sofiasz

**Comment by riyadhalnur** [comment]
I have invited @sofiasz to the `gran-canaria` team.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by D3Portillo** [comment]
@a0viedo need your help

**Comment by D3Portillo** [comment]
@riyadhalnur

**Comment by riyadhalnur** [comment]
Done. Sorry for the late response.
