### ISSUE TITLE
Add dallas organizers

### ISSUE THREAD

**Issue by gangstead** [nodeschool/organizers#536]
I'm just creating this issue so I can get nodeschool bot to add @samiconductor @michaeledavis to the dallas chapter organizers

**Comment by gangstead** [comment]
@nodeschoolbot add-team-user dallas_organizers michaeledavis

**Comment by riyadhalnur** [comment]
I have invited @michaeledavis to the `dallas_organizers` team.

**Comment by gangstead** [comment]
@riyadhalnur you are the real nodeschoolbot.  Do they need to be in the org before nodeschoolbot can add to the team?

**Comment by ldbraun** [comment]
Hello @gangstead, what are you trying to accomplish? lets see if I can be of help
