### ISSUE TITLE
Add Tabasco organizers

### ISSUE THREAD

**Issue by gartox** [nodeschool/organizers#537]

**Comment by gartox** [comment]
@nodeschoolbot add-team-user tabasco giortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `tabasco`

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `tabasco` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user tabasco_organizers gioortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `tabasco_organizers`

**Comment by riyadhalnur** [comment]
I have invited @gioortiz to the `tabasco_organizers` team.

**Comment by riyadhalnur** [comment]
I cannot find the team `tabasco_organizers`

**Comment by riyadhalnur** [comment]
I have invited @gioortiz to the `tabasco_organizers` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user chapter-organizers giortiz

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `chapter-organizers` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user tabasco giortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `tabasco`

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `tabasco` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user tabasco giortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `tabasco`

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `tabasco` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user @nodeschool/tabasco giortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `nodeschool/tabasco`

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `nodeschool/tabasco` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user Tabasco giortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `Tabasco`

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `Tabasco` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user tabasco giortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `tabasco`

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `tabasco` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user tabasco_organizers giortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `tabasco_organizers`

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `tabasco_organizers` team.

**Comment by gartox** [comment]
@nodeschoolbot add-team-user tabasco giortiz

**Comment by riyadhalnur** [comment]
I cannot find the team `tabasco`

**Comment by riyadhalnur** [comment]
I have invited @giortiz to the `tabasco` team.

**Comment by gartox** [comment]
some idea why the bot can found the team?

**Comment by D3Portillo** [comment]
share this link https://github.com/orgs/nodeschool/teams/{your-team-name-here} to the ones you wanna join you, they must request to join that team , idk why but in my case I can't use the bot to make those stuff

**Comment by gartox** [comment]
thanks @D3Portillo

**Comment by D3Portillo** [comment]
hi

**Comment by D3Portillo** [comment]
bro, first you need to add a pal to chapters-organizers team, by doing @  nodeschoolbot add-user username   , then send then the past link I sent you

**Comment by D3Portillo** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
