### ISSUE TITLE
chapter request ||Nodeschool Bijlmer

### ISSUE THREAD

**Issue by Samuel-S-Ampofo** [nodeschool/organizers#541]
# _chapter request_

Hi, I would like to start a nodeschool chapter in bijlmer. The bijlmer is the balck community in amsterdam. I left this comunity eight years ago to persue higher education in other part of the netherlands. Mainly in white communities. I am @shmuelampofo on twitter and work at Neos Innovations in Utrecht . I will be co-organizing this chapter with Joshua Sampene and John Angoh. I have been using Node.js for 1 year six months and would like to help others learn as well. 

The chapter name will be bijlmer

**Comment by riyadhalnur** [comment]
A chapter for Amsterdam already exists. I don't know if opening a more localised chapter serving to a particular community is the way to go but do correct me if I'm wrong.
