### ISSUE TITLE
Copenhagen NodeSchool

### ISSUE THREAD

**Issue by watson** [nodeschool/organizers#548]
Hi, we would like to start a NodeSchool chapter for Copenhagen, Denmark 🇩🇰 (nodeschool repo name: `copenhagen`)

Organizers:

- Thomas Watson, @watson
- Emil Bay, @emilbayes
- Mathias Buus, @mafintosh 
- Andreas Madsen, @andreasmadsen

We already run the [Copenhagen Node.js Meetup](https://www.meetup.com/cph-node/) group and will periodically be dedicating some of the meet-ups to NodeSchool.

**Comment by watson** [comment]
I'm a member my self already, so I could just create this, but I'm not sure what the policy is around that. If y'all are ok with me just creating the repo, I'll go ahead and do that.

**Comment by watson** [comment]
@nodeschoolbot add-user emilbayes

**Comment by riyadhalnur** [comment]
I have added @emilbayes to the `chapter-organizers` team.

**Comment by watson** [comment]
@nodeschoolbot create-team copenhagen

**Comment by riyadhalnur** [comment]
I have created @nodeschool/copenhagenteam

**Comment by watson** [comment]
@nodeschoolbot create-repo copenhagen

**Comment by riyadhalnur** [comment]
I have created a new repo called [copenhagen](https://github.com/nodeschool/copenhagen)

**Comment by watson** [comment]
@nodeschoolbot add-user AndreasMadsen

**Comment by riyadhalnur** [comment]
I have added @AndreasMadsen to the `chapter-organizers` team.

**Comment by watson** [comment]
@nodeschoolbot add-team-user copenhagen watson emilbayes mafintosh AndreasMadsen

**Comment by riyadhalnur** [comment]
I have invited @watson, @emilbayes, @mafintosh, @AndreasMadsen to the `copenhagen` team.
