### ISSUE TITLE
Add myself to organizers

### ISSUE THREAD

**Issue by enBonnet** [nodeschool/organizers#549]
Hello

**Comment by enBonnet** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Sorry @enBonnet. You are not allowed to do that if you are not a member of the `chapter-organizers` team

**Comment by enBonnet** [comment]
Hey @Xabadu can you add me? 😿

**Comment by Xabadu** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by Xabadu** [comment]
@nodeschoolbot add-team-user santiago @enBonnet

**Comment by riyadhalnur** [comment]
I cannot find the team `santiago`

**Comment by riyadhalnur** [comment]
I have invited @enBonnet to the `santiago` team.

**Comment by Xabadu** [comment]
@nodeschoolbot add-team-user santiago @cristofer-dev

**Comment by riyadhalnur** [comment]
I cannot find the team `santiago`

**Comment by riyadhalnur** [comment]
I have invited @cristofer-dev to the `santiago` team.

**Comment by Xabadu** [comment]
@nodeschoolbot add-user @enBonnet

**Comment by riyadhalnur** [comment]
I have added @enBonnet to the `chapter-organizers` team.

**Comment by Xabadu** [comment]
@nodeschoolbot add-user @cristofer-dev

**Comment by riyadhalnur** [comment]
I have added @cristofer-dev to the `chapter-organizers` team.

**Comment by Xabadu** [comment]
@nodeschoolbot add-user @satanas

**Comment by riyadhalnur** [comment]
I have added @satanas to the `chapter-organizers` team.
