### ISSUE TITLE
NodeSchool NYC Co-organizers

### ISSUE THREAD

**Issue by bnb** [nodeschool/organizers#551]
I've discussed NodeSchool NYC with @gautamarora (a current organizer) and would like to be added as a co-organizer to reboot the meetup. Additionally, I'd like to request that @joesepi be added as an organizer, as he was the one that suggested we reboot NodeSchool NYC and is just as interested as I am in kicking it off again.

My twitter handle is [@bitandbang](https://twitter.com/bitandbang), and Joe's account is [@joe_sepi](https://twitter.com/joe_sepi).

I've been contributing to Node.js since just after io.js, in the Website WG. I spun out the Evangelism WG from the Website WG. More recently, I've been participating in the Community Committee for the last ~2 years, spending 1 year of that time as chairperson of the Node.js Community Committee. I currently work at NodeSource as a Developer Advocate, and have [published 137 blog posts](https://nodesource.com/blog/author/bitandbang) to the NodeSource blog focusing on Node.js in production and best practices.

Joe is also a Node.js CommComm member, and has been for well over a year now. He's a Developer Advocate at IBM focusing on Node.js, and has worked on / contributed to Node.js in his last several roles.

**Comment by a0viedo** [comment]
Awesome! I'm sure you both @bnb and @joesepi will contribute greatly to the NodeSchool community.

I've sent the invitations, let me know if you need anything else.

**Comment by bnb** [comment]
I've accepted! Thank you for the invite ❤️

**Comment by a0viedo** [comment]
And went ahead and gave maintainers roles to you both. Each chapter usually manages their teams how they think it's best so feel free to add any collaborators.

**Comment by bnb** [comment]
@a0viedo awesome! How could myself and @joesepi be added as maintainers of [nodeschool/nyc](https://github.com/nodeschool/nyc)? It's unfortunately not currently attached to the [nyc-mentors](https://github.com/orgs/nodeschool/teams/nyc-mentors) team.

**Comment by bnb** [comment]
Ah, being added to [chapter-organizers](https://github.com/orgs/nodeschool/teams/chapter-organizers) team resolved that! 💥
