### ISSUE TITLE
Nodeschool Landshut

### ISSUE THREAD

**Issue by DanielHilpoltsteiner** [nodeschool/organizers#555]
Hi, I would like to start a nodeschool chapter for Landshut (Bavaria).
Currently i'm working for the local University of Applied Sciences in Landshut. 
There is no fixed Co-Organizer at the moment, but it is planned. I already talked to people who are involved in Nodeschool Munich and Augsburg. 
I started using node roughly 3 years ago and would like to create an environment in Landshut where everybody can learn it as well.

You can find me on Twitter: @HilpoltsteinerD

**Comment by DanielHilpoltsteiner** [comment]
- P U S H - 
&  add Co-organizer: 
@WanielDeiss (https://github.com/WanielDeiss)
& add Mentor: 
@Narigo (https://github.com/Narigo)
@meaku (hope thats ok for you ;-) - if we have some questions)

**Comment by victorperin** [comment]
Hello @DanielHilpoltsteiner I think I can help, by using the nodeschool bot.

**Comment by victorperin** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by victorperin** [comment]
@nodeschoolbot create-team landshut

@nodeschoolbot add-team-user landshut DanielHilpoltsteiner

**Comment by riyadhalnur** [comment]
I cannot find the team `landshut`

**Comment by riyadhalnur** [comment]
I have created @nodeschool/landshutteamI have invited @DanielHilpoltsteiner to the `landshut` team.

**Comment by victorperin** [comment]
@nodeschoolbot add-team-user landshut WanielDeiss

**Comment by riyadhalnur** [comment]
I have invited @WanielDeiss to the `landshut` team.

**Comment by victorperin** [comment]
@nodeschoolbot create-repo landshut

**Comment by riyadhalnur** [comment]
I have created a new repo called [landshut](https://github.com/nodeschool/landshut)

**Comment by victorperin** [comment]
@DanielHilpoltsteiner now it's time to you and @WanielDeiss accept the invite.

**Comment by DanielHilpoltsteiner** [comment]
Thanks @victorperin  for helping on this! i appreciate it!
I did not get any invitation (e-mail / notification) till now.
does this take a while? (i also checked spam mails)

if i try to access the repo with following link: https://github.com/nodeschool/landshut/invitations 
> i get this message: Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

has anybody some idea on this?

**Comment by WanielDeiss** [comment]
thanks for your help @victorperin !
got my invitation and accept it

@DanielHilpoltsteiner my invitation was in the spam folder (gmail) 

but don't get rights on the landshut repo, i try to do it again :D

@nodeschoolbot add-team-user landshut WanielDeiss

**Comment by riyadhalnur** [comment]
Sorry @WanielDeiss. You are not allowed to do that if you are not a member of the `chapter-organizers` team

**Comment by victorperin** [comment]
@nodeschoolbot add-team-user landshut WanielDeiss

**Comment by riyadhalnur** [comment]
I have invited @WanielDeiss to the `landshut` team.

**Comment by victorperin** [comment]
Can you try again @WanielDeiss?

**Comment by WanielDeiss** [comment]
works! thanks :)

**Comment by victorperin** [comment]
I'll close this issue, then. :)
