### ISSUE TITLE
[Chapter Request] NodeSchool Mangaluru

### ISSUE THREAD

**Issue by haxzie-xx** [nodeschool/organizers#557]
Hello there 👋 
I'm a CS undergrad from [Sahyadri Collge of Engineering](https://sahyadri.edu.in) Mangaluru and a Community lead of an [Open Source Community](https://sosc.org.in) here which helps young engineers to learn and contribute to open source projects and host free workshops on the latest tech. I'd like to start a new chapter of NodeSchool in our city, [Mangaluru](https://www.google.com/maps/place/Mangaluru,+Karnataka/data=!4m2!3m1!1s0x3ba35a4c37bf488f:0x827bbc7a74fcfe64?sa=X&ved=2ahUKEwjNlsi7ob3hAhUMfysKHb8kDnYQ8gEwAHoECAoQAQ) and to help the community in general, to learn more about JavaScript and Node.js. We are excited to introduce the resources provided by NodeSchool in our upcoming workshops. 

I have been working with Node.js for more than a year now with a number of open source projects. I've put together a strong team of devs from our community to help me co-organize the NodeSchool workshops in our city. The following are the GitHub handles of the organizers: @haxzie @rumaan  @coderhawk999 @charmy11 @Dhanush-Bangera @akashdeepb

**Comment by haxzie** [comment]
@a0viedo Sorry for the ping 😄 , we have a Node.js workshop scheduled for the next week. It'd be great if we could get our chapter approved before that. Can you please look into this?

**Comment by haxzie** [comment]
@D3Portillo any update on this, please? :smile:

**Comment by riyadhalnur** [comment]
Is this still valid? Sorry for the late response.

**Comment by dhanushp** [comment]
@riyadhalnur Hello there, some of the mentioned people have already graduated, but we are still looking forward for starting new chapter in [Mangaluru](https://www.google.com/maps/place/Mangaluru,+Karnataka/data=!4m2!3m1!1s0x3ba35a4c37bf488f:0x827bbc7a74fcfe64?sa=X&ved=2ahUKEwjNlsi7ob3hAhUMfysKHb8kDnYQ8gEwAHoECAoQAQ) with the help of our community dev's. The following are the GitHub handles of the organizers: @coderhawk999 @charmy11 @akashdeepb

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user dhanushp

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team mangaluru

**Comment by riyadhalnur** [comment]
I have created @nodeschool/mangaluruteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo mangaluru

**Comment by riyadhalnur** [comment]
I have created a new repo called [mangaluru](https://github.com/nodeschool/mangaluru)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user mangaluru dhanushp

**Comment by riyadhalnur** [comment]
I have invited @dhanushp to the `mangaluru` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user mangaluru haxzie

**Comment by riyadhalnur** [comment]
I have invited @haxzie to the `mangaluru` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user mangaluru rumaan

**Comment by riyadhalnur** [comment]
I have invited @rumaan to the `mangaluru` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user mangaluru coderhawk999

**Comment by riyadhalnur** [comment]
I have invited @coderhawk999 to the `mangaluru` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user mangaluru charmy11

**Comment by riyadhalnur** [comment]
I have invited @charmy11 to the `mangaluru` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user mangaluru akashdeepb

**Comment by riyadhalnur** [comment]
I have invited @akashdeepb to the `mangaluru` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user mangaluru Dhanush-Bangera

**Comment by riyadhalnur** [comment]
I have encountered an error doing this :(

```
Error: Bad status: 404
    at Request._callback (/home/nowuser/src/server.js:344:17)
    at Request.self.callback (/home/nowuser/src/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by riyadhalnur** [comment]
Hi @dhanushp, I created the Mangaluru team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/mangaluru. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by dhanushp** [comment]
@nodeschoolbot add-team-user mangaluru coderhawk999

**Comment by riyadhalnur** [comment]
I have invited @coderhawk999 to the `mangaluru` team.

**Comment by dhanushp** [comment]
@nodeschoolbot add-team-user mangaluru dhanushp

**Comment by riyadhalnur** [comment]
I have invited @dhanushp to the `mangaluru` team.

**Comment by dhanushp** [comment]
@nodeschoolbot add-user coderhawk999

**Comment by riyadhalnur** [comment]
I have added @coderhawk999 to the `chapter-organizers` team.
