### ISSUE TITLE
Nodeschool Nantes

### ISSUE THREAD

**Issue by cbossard** [nodeschool/organizers#558]
Hi, we would like to start a nodeschool chapter for Nantes, France. I am @ceciliaBossard on twitter and work at Code Lutin . I will be co-organizing this chapter with the local Women In Tech group in Nantes (@nanteswit). We will be around 6 or 7 organizers.
We are planning this event to take place in november.

**Comment by riyadhalnur** [comment]
Is this still valid? Sorry for the late response.

**Comment by cbossard** [comment]
Hi,
Yes, we are still motivated :-)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user cbossard

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team nantes

**Comment by riyadhalnur** [comment]
I have created @nodeschool/nantesteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo nantes

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user nantes cbossard

**Comment by riyadhalnur** [comment]
I cannot find the team `nantes`

**Comment by riyadhalnur** [comment]
I have invited @cbossard to the `nantes` team.

**Comment by riyadhalnur** [comment]
I have created a new repo called [nantes](https://github.com/nodeschool/nantes)

**Comment by riyadhalnur** [comment]
Hi @cbossard, I created the Nantes team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/nantes. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by cbossard** [comment]
Everything looks great !
Thanks a lot !
