### ISSUE TITLE
New chapter for Southeastern Ohio

### ISSUE THREAD

**Issue by TashaPenwellHC** [nodeschool/organizers#559]
Hi, I would like to start a nodeschool chapter for Southeastern Ohio.  I live in Gallia County and work in Athens County so ideally there would be some overlap to bring the two locations to one school. I am @PenwellTasha on twitter and work at Hocking College . I will be co-organizing this chapter with others in the community (TBD). I have been using Node.js for 10 months and would like to help others learn as well.

**Comment by riyadhalnur** [comment]
Please mention you co-organisers and I'll get you started on the chapter.
