### ISSUE TITLE
Add admin to NodeSchool/Lima

### ISSUE THREAD

**Issue by ogsilvaa** [nodeschool/organizers#561]
Please, add a new admin in Chapter Lima user: @darpi

 regards

**Comment by ccarruitero** [comment]
I want to nominate @lupomontero like admin in chapter Lima. He has been organizing latest nodeschool events that we did with @lima-js

ref: https://github.com/nodeschool/lima/issues/13
cc/ @ogsilvaa @lizzie136 @wixo @lupomontero @a0viedo @riyadhalnur

**Comment by a0viedo** [comment]
hey @ogsilvaa and @ccarruitero, thanks for your suggestions. I've sent the invites to @darpi and @lupomontero and will make them maintainers

**Comment by lupomontero** [comment]
Many thanks @a0viedo, @ogsilvaa and @ccarruitero  :star: 

I've already accepted the invite :yellow_heart:

**Comment by a0viedo** [comment]
please feel free to add as many team members or maintainers as you like

**Comment by ccarruitero** [comment]
Thanks @a0viedo , this will help us a lot

**Comment by a0viedo** [comment]
closing now, if you need anything reach out :wave:
