### ISSUE TITLE
Email forwarding seems to be down

### ISSUE THREAD

**Issue by keywordnew** [nodeschool/organizers#562]
Hey rad NodeSchool folks! We found that email forwarding for vancouver@nodeschool.io isn't working.

Any others having the same experience?

**Comment by riyadhalnur** [comment]
Has this issue been resolved?

**Comment by keywordnew** [comment]
We switched to using a groups.io alias, to allow for more fine-grained control. I'm ok to close this, but feel free to reopen at any time! 💯
