### ISSUE TITLE
New Chapter Request: Indore, India

### ISSUE THREAD

**Issue by mishuvs** [nodeschool/organizers#563]
Hi, I would like to start a nodeschool chapter for Indore, India. I am [@iamvaibhav_sh] on twitter. I was a  [Google Summer of Code](https://summerofcode.withgoogle.com) 2018 student under FOSSASIA. I have completed a Bachelors of Engineering degree in Information Technology this year.
I started learning Node.js from a Coursera course by HKUST's Prof. Jogesh Mupalla. Since then, I have been using Node.js for my personal projects.

I along with my co-organizer @harshmandalgi would like to start a NodeSchool Chapter for our city, Indore. Kindly guide us with the requirements. Thank you.

**Comment by darcyclarke** [comment]
@nodeschoolbot add-user mishuvs

**Comment by riyadhalnur** [comment]
I have added @mishuvs to the `chapter-organizers` team.

**Comment by darcyclarke** [comment]
@nodeschoolbot create-team indore

**Comment by riyadhalnur** [comment]
I have created @nodeschool/indoreteam

**Comment by darcyclarke** [comment]
@nodeschoolbot create-repo indore

**Comment by riyadhalnur** [comment]
I have created a new repo called [indore](https://github.com/nodeschool/indore)

**Comment by darcyclarke** [comment]
@nodeschoolbot add-team-user indoreteam mishuvs

**Comment by riyadhalnur** [comment]
I cannot find the team `indoreteam`

**Comment by riyadhalnur** [comment]
I have invited @mishuvs to the `indoreteam` team.

**Comment by mishuvs** [comment]
Thanks a lot @darcyclarke @riyadhalnur ! :tada: :smile:

**Comment by darcyclarke** [comment]
@nodeschoolbot add-team-user indoreteam harshmandalgi

**Comment by riyadhalnur** [comment]
I cannot find the team `indoreteam`

**Comment by riyadhalnur** [comment]
I have invited @harshmandalgi to the `indoreteam` team.

**Comment by mishuvs** [comment]
@riyadhalnur I haven't received any invitations to join the `indore` team. Also it's: `indore`, couldn't find `indoreteam`.

**Comment by darcyclarke** [comment]
@nodeschoolbot add-team-user indore mishuvs

**Comment by riyadhalnur** [comment]
I have invited @mishuvs to the `indore` team.

**Comment by darcyclarke** [comment]
@nodeschoolbot add-team-user indore harshmandalgi

**Comment by riyadhalnur** [comment]
I have invited @harshmandalgi to the `indore` team.

**Comment by mishuvs** [comment]
Oh, now I am in the `indore` team!

**Comment by darcyclarke** [comment]
@riyadhalnur are repos that are created with @nodeschoolbot configured properly for the corresponding team to have access? Looks like it just generated a repo that is "Read" only from what I see....

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by darcyclarke** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by darcyclarke** [comment]
Looks like we're going to need some help to get this **bot** to create repos with the repo permissions/configuration... otherwise, someone is always going to have manually set it up. 

Can we get help from someone to give the **indore** team push access/permissions to the **nodeschool/indore** repo? /cc @riyadhalnur @maxogden @SomeoneWeird @brianloveswords @mikeal or anyone that is an "owner" [here](https://github.com/orgs/nodeschool/people?utf8=%E2%9C%93&query=+role%3Aowner)

**Comment by mishuvs** [comment]
Yes, I don't have push access 
> Can we get help from someone to give the Indore team push access/permissions to the nodeschool/indore repo?

/cc @nodeschool/admin-maintainer

**Comment by SomeoneWeird** [comment]
Done, not sure why the bot is busted.

**Comment by mishuvs** [comment]
Thanks, Adam!!

**Comment by darcyclarke** [comment]
@mishuvs I think you're all set up now, so I'm going to close this issue. Definitely let me know if you need any more help or guidance as you begin to ramp up. I know that NodeSchool Montreal previously forked the Toronto Chapter's website (check out our [gh-pages](https://github.com/nodeschool/toronto/tree/gh-pages) branch) and you're more then welcome to do the same (although it'll require some work to update the styles/content)

**Comment by mishuvs** [comment]
Sure @darcyclarke :+1: The Toronto Chapter's website is really cool :heart:! I'll see if we can fork it with attribution, and modify as per ours needs. :smile:
