### ISSUE TITLE
Request for New chapter ASIET Nodeschool

### ISSUE THREAD

**Issue by arjunangepat** [nodeschool/organizers#564]
Hi, I would like to start a nodeschool chapter for ASIET, Cochin, India. I am @arjunangepat on twitter and completed my BTech in Computer Science and Engineering from ASIET . I will be co-organizing this chapter with Prof. Ajay Basil Vaghese, Chief Coordinator Innovation and Entrepreneurship Development Cell ASIET. We have been experimenting a lot of projects on IoT and AI with NodeJS and many other frameworks. If we were to form a new collective community, it will be great for effective utilization of the functionalities of NodeJS.

**Comment by arjunangepat** [comment]
May I know how much time it will take for the submission?

**Comment by riyadhalnur** [comment]
Could you mention your co-organiser's Github handle?
