### ISSUE TITLE
nodeschool Prague

### ISSUE THREAD

**Issue by quibusus** [nodeschool/organizers#565]
Hi, I would like to start a Nodeschool chapter for Prague.

I am @karoldanko on twitter and work at [OAK'S LAB.](https://github.com/oakslab).

I will be co-organizing this chapter with engineers from OAK'S LAB and Rupert Vans Agnew (@rupertva on GitHub).

We're using Node.js in production for a few years and we'd like to share with the community.

**Comment by quibusus** [comment]
Logo:

![logo](https://user-images.githubusercontent.com/965671/64864829-39569900-d638-11e9-9e6c-7674bb2c356c.png)

**Comment by ldbraun** [comment]
nodeschoolbot create-repo prague

**Comment by ldbraun** [comment]
@nodeschoolbot create-repo prague

**Comment by riyadhalnur** [comment]
I have created a new repo called [prague](https://github.com/nodeschool/prague)

**Comment by ldbraun** [comment]
Oh, Ok @riyadhalnur

**Comment by ldbraun** [comment]
@nodeschoolbot add-user  quibusus

**Comment by riyadhalnur** [comment]
I have added @quibusus to the `chapter-organizers` team.

**Comment by ldbraun** [comment]
@nodeschoolbot add-team-user prague  quibusus

**Comment by riyadhalnur** [comment]
I cannot find the team `prague`

**Comment by riyadhalnur** [comment]
I have invited @quibusus to the `prague` team.

**Comment by ldbraun** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by ldbraun** [comment]
@nodeschoolbot create-team prague

**Comment by riyadhalnur** [comment]
I have created @nodeschool/pragueteam

**Comment by ldbraun** [comment]
@nodeschoolbot add-team-user prague  quibusus

**Comment by riyadhalnur** [comment]
I cannot find the team `prague`

**Comment by riyadhalnur** [comment]
I have invited @quibusus to the `prague` team.

**Comment by ldbraun** [comment]
@nodeschoolbot add-team-user pragueteam  quibusus

**Comment by riyadhalnur** [comment]
I cannot find the team `pragueteam`

**Comment by riyadhalnur** [comment]
I have invited @quibusus to the `pragueteam` team.
