### ISSUE TITLE
Beginning a nodeschool in jalandhar, punjab

### ISSUE THREAD

**Issue by genialkartik** [nodeschool/organizers#566]
Hi, I would like to start nodeschool at Jalandhar, India. I am @genialkartik on twitter and I love to contribute in Open Source projects and workshops. I'm a web developer and Mozillian from India. If there is any provision for meetup/event in Jalandhar, India then kindly drop me a mail. I'm a UG student by profession hence I'm not in sort of co-organisers.

**Comment by ldbraun** [comment]
Hello @genialkartik, thank you for your interest to start and extend Nodeschool, Do you have co-organizer(s)? As we usually recommend starting a chapter with atleast 2-3 co-organizers.
