### ISSUE TITLE
New chapter: East Bay (San Francisco)

### ISSUE THREAD

**Issue by klequis** [nodeschool/organizers#567]
Hi,

I would like to start a Nodeschool chapter for what in the San Francisco area is known as the 'East Bay'. This describes mostly the suburbs on the east side of the San Francisco bay. While it is a large area it is somewhat quiet in terms of event attendance and a smaller geographic description would likely have low attendance.

My name is [Carl Becker](https://www.linkedin.com/in/carlbecker/). I'm an independent software developer and have been using node for 4 years. On Twitter I'm @at_klequis, although I'm not active there.

I have been the organizer of of [TriValley Coders (TVC)](https://www.meetup.com/trivalleycoders/) for the past 3 years and would like to re-brand as Nodeschool. TVC has been quiet for a while but I want to restart it.

I'm also a regular participant & sometimes mentor in the San Francisco and Oakland Nodeschools.

Cheers,
Carl

**Comment by Xabadu** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by Xabadu** [comment]
@nodeschoolbot add-user klequis

**Comment by riyadhalnur** [comment]
I have added @klequis to the `chapter-organizers` team.

**Comment by Xabadu** [comment]
@nodeschoolbot create-team eastbay

**Comment by riyadhalnur** [comment]
I have created @nodeschool/eastbayteam

**Comment by Xabadu** [comment]
@nodeschoolbot add-team-user eastbay klequis

**Comment by riyadhalnur** [comment]
I have invited @klequis to the `eastbay` team.

**Comment by Xabadu** [comment]
@nodeschoolbot create-repo eastbay

**Comment by riyadhalnur** [comment]
I have created a new repo called [eastbay](https://github.com/nodeschool/eastbay)

**Comment by klequis** [comment]
Thank you both for your help! I don't have exact plans yet but hoping to hold the first event in January.

**Comment by mikeal** [comment]
Typically NodeSchool’s are named after cities rather than regions. This is a little confusing since there is at least one other NodeSchool in the East Bay already (NodeSchool Oakland).

Where do you plan on actually holding the workshops? Is there a reason you don’t want to name it after the town/city?
