### ISSUE TITLE
Add members to NodeSchool Campinas

### ISSUE THREAD

**Issue by victorperin** [nodeschool/organizers#569]
@nodeschoolbot add-team-user campinas pethersonmoreno

**Comment by fmoliveira** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by fmoliveira** [comment]
@nodeschoolbot add-team-user campinas pethersonmoreno

**Comment by riyadhalnur** [comment]
I have invited @pethersonmoreno to the `campinas` team.

**Comment by victorperin** [comment]
@nodeschoolbot add-team-user campinas geovanipfranca

**Comment by riyadhalnur** [comment]
I have invited @geovanipfranca to the `campinas` team.

**Comment by victorperin** [comment]
Thanks ;)
