### ISSUE TITLE
New Chapter for NodeSchool Calabar, Cross River State, Nigeria

### ISSUE THREAD

**Issue by okoibraun** [nodeschool/organizers#570]
Hello,

I will like to start a Nodeschool Chapter in Calabar, Cross River, Nigeria. I spoke/had a chat with @ldbraun, and He is willing to spare-head and co-organize with me as He was the one that introduce and told me about this.

**Comment by ldbraun** [comment]
@nodeschoolbot create-repo calabar

**Comment by riyadhalnur** [comment]
I have created a new repo called [calabar](https://github.com/nodeschool/calabar)

**Comment by ldbraun** [comment]
@nodeschoolbot add-user okoibraun

**Comment by riyadhalnur** [comment]
I have added @okoibraun to the `chapter-organizers` team.

**Comment by ldbraun** [comment]
@nodeschoolbot add-team-user calabar okoibraun

**Comment by riyadhalnur** [comment]
I cannot find the team `calabar`

**Comment by riyadhalnur** [comment]
I have invited @okoibraun to the `calabar` team.

**Comment by ldbraun** [comment]
@nodeschoolbot add-team-user ldbraun

**Comment by riyadhalnur** [comment]
I cannot find the team `ldbraun`

**Comment by riyadhalnur** [comment]
I have invited  to the `ldbraun` team.

**Comment by ldbraun** [comment]
@nodeschoolbot add-team-user calabar ldbraun

**Comment by riyadhalnur** [comment]
I cannot find the team `calabar`

**Comment by riyadhalnur** [comment]
I have invited @ldbraun to the `calabar` team.

**Comment by terrywirewire780** [comment]
![Screenshot_20241129-035341](https://github.com/user-attachments/assets/c65d3214-c451-4fd8-ab84-38a0c60b7c7e)
![Screenshot_20241129-035150](https://github.com/user-attachments/assets/f170d611-d97b-4aa6-bb6f-120fe38ff95b)
![Screenshot_20241129-040622](https://github.com/user-attachments/assets/8329f270-79d5-4b5c-a0d7-ecdb12f4ef4c)

**Comment by terrywirewire780** [comment]
> I cannot find the team `ldbraun`

Phone iTunes gift card 

> ****

**Comment by terrywirewire780** [comment]
xwmps8aj
