### ISSUE TITLE
[Github Pages] Website for nodeschool landshut not building

### ISSUE THREAD

**Issue by DanielHilpoltsteiner** [nodeschool/organizers#572]
Hey altogether, 

we are still having some problems creating a website for nodeschool landshut. 
We have tried several different versions at out gh-pages branch at https://github.com/nodeschool/landshut/tree/gh-pages
But no site was generated. 
1) We tried to access https://nodeschool.github.io/landshut but it is resulting in a 404 Page.
2) We double checked the build artefact in another repository with github pages enabled and it worked. So it is not the Code. 
3) We also forked the nodeschool/augsburg repository (which is working) and tried the same code on the landshut repo. Also not working
3) At the moment we think it is settings issue in the repository. As we can not access settings for the nodeschool landshut repository, we are not able to verify.

Did anyone ran into similar problems or knows how to solve this?
@WanielDeiss and me would really appreciate any thoughts!

But not to forget! We wish you a happy and great new year!

**Comment by riyadhalnur** [comment]
@DanielHilpoltsteiner  I got the site running at [https://nodeschool.io/landshut/](https://nodeschool.io/landshut/) by triggering a publish from the repo settings. You might need to update the site to use the proper design etc. by pushing a new commit. Let me know if there's any more problems.
