### ISSUE TITLE
I see that this chapter is not active, I'll like to take over the repo 

### ISSUE THREAD

**Issue by laurelsilva** [nodeschool/organizers#573]
I'll like to start a nodeschool chapter for Portland, Oregon. I'll like to take over this repo (https://github.com/nodeschool/pdx) that's no longer active or start a new one. I am [@laurosilvacom](http://twitter.com/laurosilvacom) on twitter and work as an independent developer. I have been using Node.js for over a year and would like to help others learn as well.

**Comment by victorperin** [comment]
@nodeschoolbot add-team-user pdx laurosilvacom

**Comment by laurosilvacom** [comment]
@nodeschoolbot I was not added to the team

**Comment by riyadhalnur** [comment]
Sorry @laurosilvacom. You are not allowed to do that if you are not a member of the `chapter-organizers` team

**Comment by laurelsilva** [comment]
Thanks @ricardoerl. Can I be added as a chapter organizer?

The last commit was 5 years ago: https://github.com/nodeschool/pdx/tree/gh-pages
Here's the GitHub pages: https://nodeschool.io/pdx

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user pdx laurosilvacom

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user laurosilvacom

**Comment by riyadhalnur** [comment]
I have added @laurosilvacom to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team pdx

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team pdx

**Comment by riyadhalnur** [comment]
I have created @nodeschool/pdxteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user pdxteam laurosilvacom

**Comment by riyadhalnur** [comment]
I cannot find the team `pdxteam`

**Comment by riyadhalnur** [comment]
I have invited @laurosilvacom to the `pdxteam` team.

**Comment by riyadhalnur** [comment]
Closing this now. Feel free to reopen if premature
