### ISSUE TITLE
New Chapter:  Delhi

### ISSUE THREAD

**Issue by prateikjaiswal** [nodeschool/organizers#575]
Hi, I would like to start a nodeschool chapter for Delhi. I am [Pratik Jaiswal](https://www.linkedin.com/in/pratik-jaiswal/) on LinkedIn. I will be organizing this chapter. I have been using Node.js, Express.js, Nest.js, Angular, and Ionic for four years, nowadays I`m participating in NodeJS worldwide group at slack.
I will be utilizing this to help people with Node.js and organize events.

**Comment by riyadhalnur** [comment]
A chapter for Delhi (https://github.com/nodeschool/delhi-ncr) already exists. Please get in touch with the organisers of the chapter for future collaboration.
