### ISSUE TITLE
New chapter: Chennai

### ISSUE THREAD

**Issue by yohix** [nodeschool/organizers#577]
I'm Yohix, **iOS and Web Developer from Chennai**

The NodeSchool resources are really awesome. I develop **NPM Modules**, **React Apps** and **React Native Mobile apps**. I'm interested to inculcate Node.js to my friends, colleagues, and students from various parts of Tamil Nadu. I'm interested in starting the NodeSchool chapter for Chennai, Tamil Nadu, India.

I will be co-organizing this chapter with **Kavya Manoharan** @manokavya.

If anyone here in Chennai interested to help me with this, please +1 :)

cc: @riyadhalnur, @victorperin

:pray: Thanks!

**Comment by manokavya** [comment]
Dear yohix,

I'm glad to hear from you.  But I couldn't figure what it is exactly.  Can
you communicate about this in your free time?


Regards,
Kavya Manoharan

**Comment by riyadhalnur** [comment]
A chapter for Chennai (https://github.com/nodeschool/chennai) already exists. Please get in touch with the organisers of the chapter for future collaboration.

**Comment by yohix** [comment]
Thanks, @riyadhalnur seems like the repo is no longer active!

**Comment by yohix** [comment]
Gitter channel is also no longer active https://gitter.im/nodeschool/chennai!

**Comment by yohix** [comment]
cc: @vikene

**Comment by riyadhalnur** [comment]
You can try opening an issue on the repo or getting in touch directly with the organiser. Should they not respond within a given period of time, we can move ahead and give you permissions to maintain the chapter.

**Comment by yohix** [comment]
I requested over here https://github.com/nodeschool/chennai/issues/3

Let us wait for a month! WDYT @riyadhalnur

**Comment by yohix** [comment]
@riyadhalnur It seems there is no response till now!

WDYT?

**Comment by riyadhalnur** [comment]
Hi @yohix, I went ahead and added you to the repo and team. Please accept the invite to get started.

**Comment by yohix** [comment]
@riyadhalnur Thank you so much! We will try to make Nodeschool great!

**Comment by riyadhalnur** [comment]
Closing this issue then. Welcome to the family!
