### ISSUE TITLE
New Chapter: Richmond, VA USA

### ISSUE THREAD

**Issue by JohnHillegass** [nodeschool/organizers#578]
Hi, I would like to start a nodeschool chapter for Richmond, VA. I am @johnphillegass on twitter and am a software engineering manager at Capital One . I have been using Node.js for 3 years and would like to help others learn as well.

**Comment by JohnHillegass** [comment]
closing until I can find some co-organizers.. seems like there is a requirement to have more than one :(

**Comment by JohnHillegass** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Sorry @JohnHillegass. You are not allowed to do that if you are not a member of the `chapter-organizers` team
