### ISSUE TITLE
New chapter: Jaipur

### ISSUE THREAD

**Issue by hiteshsubnani0128** [nodeschool/organizers#579]

**Comment by hiteshsubnani0128** [comment]
Hello World!

I am Hitesh Subnani, and I want to open Node.JS chapter in Jaipur India

**Comment by riyadhalnur** [comment]
Hi @hiteshsubnani0128, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by hiteshsubnani0128** [comment]
Hi @riyadhalnur, yes, I am having few active communists @kroy96, and @rexyagami will be our co-organizer also I will look for more helping hands for organizing the meetup and learning camps.

**Comment by kroy96** [comment]
Yes, we will be aiding @hiteshsubnani0128 by the side.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user hiteshsubnani0128

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team jaipur

**Comment by riyadhalnur** [comment]
I have created @nodeschool/jaipurteam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo jaipur

**Comment by riyadhalnur** [comment]
I have created a new repo called [jaipur](https://github.com/nodeschool/jaipur)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user jaipur hiteshsubnani0128

**Comment by riyadhalnur** [comment]
I have invited @hiteshsubnani0128 to the `jaipur` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user jaipur kroy96

**Comment by riyadhalnur** [comment]
I have invited @kroy96 to the `jaipur` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user jaipur rexyagami

**Comment by riyadhalnur** [comment]
I have invited @rexyagami to the `jaipur` team.

**Comment by riyadhalnur** [comment]
Hi @hiteshsubnani0128, I created the Jaipur team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/jaipur. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
