### ISSUE TITLE
start a new nodeschool chapter

### ISSUE THREAD

**Issue by paullaster** [nodeschool/organizers#580]
Hi all, I would like to start a nodeschool chapter for Nairobi KE. I am @PaullasterOkoth] on twitter and work at Meta Ajax Technology Agency Inc . I Paullaster Okoth will be the organizer of this chapter. I have been using Node.js for 9 months and would like to help others learn as well. Thank you!

**Comment by riyadhalnur** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
* `create-chapter {name}` - creates a new chapter

**Comment by riyadhalnur** [comment]
Hi @paullaster, there's already a chapter for [Nairobi](https://github.com/nodeschool/nairobi). Please get in touch with the maintainers for the respective chapter to join as co-organiser.

**Comment by antosan** [comment]
Hi @paullaster, please get in touch with us, we are looking for mentors for NodeSchool Nairobi https://nodeschool.io/nairobi/. Thanks.

**Comment by paullaster** [comment]
Cool.

**Comment by paullaster** [comment]
Hi @antosan  Kindly tell me about joining the https://nodeschool.io/nairobi/ as a co-organizer
Looking forward for a timely reply.
