### ISSUE TITLE
NodeSchool at Valencia (Spain)

### ISSUE THREAD

**Issue by itspoma** [nodeschool/organizers#609]
Hello! I would like to run NodeSchool at **Valencia (Spain)**.

I've organized NodeSchool at Lviv (Ukraine) before (Aug 2017), and that time we gathered 100+ members who want to learn and improve Node.js. https://nodeschool.io/lviv/ & https://github.com/nodeschool/lviv.

I have more 10 years of software development on various positions (including C-level), and worked with various clients (US/EU) and different domains.

Recently I've moved to Spain, Valencia - and found that NodeSchool is missed here (but present on other cities like Madrid, Barcelona, Malaga).

![image](https://github.com/nodeschool/organizers/assets/601915/ab9fd377-e9e2-4c29-9eac-d93189cb1d26)

Kind regards,
Roman

**Comment by itspoma** [comment]
@alexfernandez @carlosazaustre @javiervelezreyes @patrickheneise (I'm sorry to tagging you) Can you assist? (since you're owners of Madrid & Barcelona initiatives). Thanks in advance!

**Comment by PatrickHeneise** [comment]
It's been a while since the last NodeSchool Barcelona and I'm not living there any more. I'd suggest to reach out to the current BarcelonaJS organizers and see if they can help (@dmitry-zaets, @onedesert).

**Comment by dmitry-zaets** [comment]
Yep, @PatrickHeneise is right - we haven't conducted NodeSchool events for many years. But we are happy to assist you! Let us know how we can help.

**Comment by itspoma** [comment]
Thanks Patrick!, and hello Dmitry! What help am I looking for - based on [Issues](https://github.com/nodeschool/organizers/issues) no new cities been added during past many months, so I assume support might not be actively monitoring these issues. I would appreciate if you can introduce me with somebody from NodeSchool who can approve "new chapter" Valencia, and create a branch, so I can proceed with website and event. Thanks in advance!

**Comment by carlosazaustre** [comment]
Hi @itspoma!
Sure, I can add Valencia chapter to the repo.
Please, create a PR adding a file `valencia.json` in `chapters` folder, filled with info similar to this one: https://github.com/nodeschool/nodeschool.github.io/blob/source/chapters/madrid.json
You can put me as reviewer and I will add it. :)

**Comment by itspoma** [comment]
@carlosazaustre Hello Carlos, pleasure meeting you! I've added PR with committed json with Valencia's chapter - https://github.com/nodeschool/nodeschool.github.io/pull/664.

According to process defined [here](https://github.com/nodeschool/organizers?tab=readme-ov-file#how-to-start-a-new-nodeschool-chapter), could you also pls add me to `chapter-organizers` group so I can create & push gh-page? Thanks in advance!

**Comment by carlosazaustre** [comment]
Hi @itspoma , I have already accept the PR, altought I couldn't added you to `chapter-organizers` team. Maybe needs an admin to added you.

**Comment by riyadhalnur** [comment]
Hey @itspoma welcome to the org. I've created the repo here https://github.com/nodeschool/valencia along with the relevant teams. Sent you an invite to the organisers team.

**Comment by itspoma** [comment]
Hello again @riyadhalnur ! Sorry for bothering you again – it seems I don't have enough permissions on https://github.com/nodeschool/valencia/ (can't set up github-pages, doesn't have permissions to edit settings on repo).

I've tried to create both `master` and `main` branches (since I'm not sure to which branch gh-pages are looking), but either not working – https://nodeschool.io/valencia is 404.

You can compare my permissions on another repo, where I'm organizer – https://github.com/nodeschool/lviv/, since I have right permissions there, and website is working – https://nodeschool.io/lviv/.

I'm in active preparation of the event, so would very much appreciate it if you can check it. Thank you in advance!

**Comment by riyadhalnur** [comment]
Hey @itspoma should be updated now
