### ISSUE TITLE
Way to treat inactive discussion threads.

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#90]
Most of the issues in the discussions issue tracker are answered. Most of those have been answered quite clearly in my opinion. And also most of the issues have a positive feedback or are missing feedback for weeks.

- Is it okay to close threads that seem to be answered positively with positive feedback from the initial reporter? (label: "successfully-resolved"?)
- Is it okay to close threads that have a solid answer but no response from the person asking the question? (label: "seems-resolved"?)
- Is it okay to close threads that are open with a moderator question and missing feedback? (label: "broken-feedback-loop")

**Comment by martinheidegger** [comment]
@jasonrhodes I thought about it a little more and I think that the "resolved" label will not solve my problem. My problem being: I sift through the list of issues and can't figure out treat them. Most i would close with "Seems resolved" and that is where the label's would come in place. My imagined workflow would be like:

In case I read through an entry and the person has answered to it like "I figured it out!" but didn't close it:

1. Add `seems-resolved` label
2. Close issue

In case I read an entry and the content is quite trivial and there was no follow up like "How do I install node.js":

1. Add `probably-self-resolved` label
2. Close issue

In case the issue is a little bit trickier and a mentor asked a question without answer:

1. Add `waiting-for-feedback` label
2. Wait for 3 weeks
3. Close issue

And (additionally to what I wrote when I started the issue) in case the issue is non-trivial and there has not been an answer by the community;

1. Add `needs-attention` label
2. Wait for 1 day
3. Post on twitter

This way it would be possible for me to clean up the issue list (giving people more confidence that their issues will be taken care of ...)

**Comment by martinheidegger** [comment]
I decided to add the labels. Please use them as described above.

**Comment by Sequoia** [comment]
Can users reopen tickets? If so, & the issue is straightforward like "how install node" I think link & close & prompting them to "reopen if issue persists!" works.  Quick & easy & allows user to get thread back up if they are still having trouble.

TBH I think all install issues should be punted to a nodejs faq & closed.

**Comment by martinheidegger** [comment]
Yes, users can reopen tickets. When you say "link" I think of a github document because it tracks references in the original document ([example](https://github.com/nodeschool/organizers/issues/28#issuecomment-67791092))

**Comment by martinheidegger** [comment]
So: users can not reopen tickets but they still can comment on them and we get notified, so we can reopen and remove labels.

**Comment by Sequoia** [comment]
What should we do to resolve this question/what specific question exists here/is it resolved?

I think more people looking over the tickets w/o comments or labeled as needing attention, comment & close in 2 weeks (or 1 if it's a really old ticket) could make this issue go away.  I propose a guideline like "reply & give the asker a week or so to respond then close" & leave the rest to peoples' discretion.

For my part, I have my start pages in chrome set to:
* [needs some love](https://github.com/nodeschool/discussions/issues?q=is%3Aopen+label%3Aneeds-some-love+sort%3Acreated-asc) and
* [no comments yet](https://github.com/nodeschool/discussions/issues?q=is%3Aissue+is%3Aopen+comments%3A0+sort%3Acreated-asc)

If a few people do this and spend a few minutes a day addressing tickets, I think the issue can be considered resolved :+1:

**Comment by martinheidegger** [comment]
The question here is resolved in the sense that I am already working on it (reopened so others feel like chiming in) but my follow up steps would be

- [ ] PR for a markdown file that explains labels
- [ ] PR for a markdown file that gives guidance for people trying to help

Afaik @a0viedo is working on this.

**Comment by jasonrhodes** [comment]
Just for the record, I don't think it's reasonable to assume that everyone who can pitch in to help with issue grooming is going to end up following a system like this. I don't think there's anything wrong with having the labels to help with various visibility, but I don't think I'd have anything written that guarantees this kind of process. I've worked on some big open source projects where we just closed things, reopened them if necessary, and it all shakes out while also being easy for other owners to jump in and use their best judgement on closing issues, answering them, etc.

My $0.02.

**Comment by martinheidegger** [comment]
@jasonrhodes Totally agree. This is not meant to be enforced but as guidance in case someone feels uneasy about interacting with the list (as I did when I started this).

**Comment by Sequoia** [comment]
I agree with @jasonrhodes that we're veering towards "overthinking/overengineering" these systems. No documentation can be bad but `readme`s scattered hither and yon present their own problem.  TBH I'd say that if our labeling system require's a `readme`, that's a sure sign that our labeling system is overcomplicated.  There are a handful of people here addressing a handful of tickets.

I propose that "having an active community" would render all the issues around labeling moot. To quote Shakespeare: "Don't overthink it."  :palm_tree:

**Comment by martinheidegger** [comment]
Thanks for pulling me out of my rabbit hole ... (I tend to overthink a lot of things) ... But still: I think the initial problem is valid so I would say to reduce this to:

- [ ] Add a section somewhere that says: *"organisers: feel free to comment on dicussion issues when you have time, use labels to as you see fit and close issues"*

**Comment by Sequoia** [comment]
looks gr8 :+1: :smile_cat:

**Comment by Sequoia** [comment]
I might `s/organizers/everyone/`. i.e. "if you want to help or know an answer, don't be afraid to jump right in!"

**Comment by martinheidegger** [comment]
:+1:

**Comment by martinheidegger** [comment]
Oh, but only owners can actually apply labels and close issues ....

**Comment by martinheidegger** [comment]
Documentation done. Many issues closed.
