### ISSUE TITLE
Interest in helping setup a San Francisco NodeSchool Chapter

### ISSUE THREAD

**Issue by duquet** [nodeschool/organizers#92]
Hi, I would like to start a nodeschool chapter for San Francisco. I am @aduquet on twitter and work at NerdWallet as a contract Recruiter. I will be co-organizing this chapter with nerdwallet. I have been using Node.js for 1 month and would like to help others learn as well.

**Comment by llkats** [comment]
+1 for the daytime. How long do events usually last? Could we do something like 12 - 5?

**Comment by linclark** [comment]
For the one at Double Union, I scheduled it for 4 hours, which I think is about the right length. So maybe 1pm-5pm? If we start it at 1pm, then I think we can get away with having lighter snacks.

**Comment by jedireza** [comment]
Feb 7th 1pm - 5pm works for me too.

**Comment by jasonrhodes** [comment]
FWIW, in Baltimore this is exactly the format we use, 1-5pm, light snacks and drinks (if alcohol, we only serve for the last hour or two, but recently we dropped alcohol altogether). We usually do about 30 minutes of intro up front and jump into exercises after that, although I've heard people having a lot of success going through the first lesson or two together as a group.

Also, we ask people in advance to self-rate their JS skill level with 1-3 ratings, then we put their names on color-coded name tags and tell them to pair up with someone with the same color name tag. That's worked *really* well if you are interested in having people pair, which we've found to be really really successful. 

Good luck! :)

**Comment by RichardLitt** [comment]
Works for me!

**Comment by cantremember** [comment]
1-5pm sounds like a good plan -- but i'll have to bolt right @ 5

**Comment by llkats** [comment]
Thanks for the tips, @jasonrhodes!! Keep 'em coming if you think of any more! :)

**Comment by llkats** [comment]
Something that occurred to me: should we have signups or RSVPs?

**Comment by linclark** [comment]
For the one at Double Union, we did $5 tickets through Tito to ensure that people showed up.

**Comment by llkats** [comment]
Okay, cool, that sounds like a plan. I can set that up, just need confirmation from @groundwater on the date/times and I'm ready to start getting the word out!

**Comment by RichardLitt** [comment]
It'll also be useful to know tutors to students ratio, right?

**Comment by jedireza** [comment]
Referring to: https://github.com/nodeschool/organizers/blob/master/README.md#how-to-start-a-new-nodeschool-chapter

We need a chapter owner (if we don't already have one). I'm happy to throw my name in that hat. Once that's done we can continue with the steps outlined.

:sparkles: woot :sparkles:

**Comment by llkats** [comment]
Yes, tutor to student ratio would be great to know. How do we solicit and track volunteers? Would this Github issue be fine to do that?

Seems to me like @duquet would be first in line to be the chapter owner, since he opened this thread!

**Comment by duquet** [comment]
Thanks, I would like that unless anyone objects.

On Wed, Jan 7, 2015 at 11:22 AM, Lydia Katsamberis <notifications@github.com
> wrote:

> Yes, tutor to student ratio would be great to know. How do we solicit and
> track volunteers? Would this Github issue be fine to do that?
>
> Seems to me like @duquet <https://github.com/duquet> would be first in
> line to be the chapter owner, since he opened this thread!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/organizers/issues/92#issuecomment-69075823>
> .
>



-- 
Andrew Duquet
Owner/Recruiter
Searchlight Systems
t:510.525.3200
andrew.duquet@gmail.com

**Comment by jedireza** [comment]
Sweet. @maxogden how do we get @duquet setup as an owner?

**Comment by jasonrhodes** [comment]
I can set you all up. There are chapters with multiple owners, FYI.

**Comment by jasonrhodes** [comment]
OK @duquet I added you as an owner. FYI there are chapters with multiple owners so let me know if you would like to add more. You can follow the steps in the README that you linked to above and get your chapter repo set up, then you can continue this conversation over there!

**Comment by groundwater** [comment]
I will confirm the time with our events planner tomorrow

**Comment by cantremember** [comment]
conversation moved to https://github.com/nodeschool/sanfrancisco/issues/1
