### ISSUE TITLE
Invitation to Comment: advice on being a 'good Mentor'

### ISSUE THREAD

**Issue by cantremember** [nodeschool/organizers#97]
is there some resource on being a 'good Mentor' in the NodeSchool Community sense?  i don't see a NodeSchool.io site page that covers this, nor a Wiki Page here, nor an open or closed Issue that really touches on this point.  i could have easily missed something ...

i scanned through [tips and tricks](https://github.com/nodeschool/nodeschool.github.io/issues/15) and [Want to run an event?](https://github.com/nodeschool/discussions/issues/93) for some advice.  these were relevant snippets

- https://github.com/nodeschool/nodeschool.github.io/issues/15#issue-22385252

  > mentors basically hover around the room during the event and try to find people who are stuck and then they help them get un-stuck.

  "hovering" sounds good

  ![](http://media.giphy.com/media/1DxowAuY90ady/giphy.gif)

- https://github.com/nodeschool/discussions/issues/93#issuecomment-36045066

  (in general)

- https://github.com/nodeschool/discussions/issues/93#issuecomment-36449229

  > The mentors were asked to familiarize themselves with the workshops being offered in order to be the most help on-site.

  i also see mentions of "Functional JavaScript mentors," which suggests that there is some sort of idea of what Organizers are looking for

- https://github.com/nodeschool/discussions/issues/93#issuecomment-37015159

  > ... it's just worth giving mentors the heads up on the common pitfalls.

i'm just wanting to make sure that i'm putting my best face forward for the Community :)

**Comment by cantremember** [comment]
thank you, @linclark . i'll be happy to author a Nodeschool Wiki page on the subject ... once i have enough material to based one on. i'll use this Issue to solicit feedback comments. it'll simply be a matter of capturing people's attention :smile: 

your opinion -- is *this* repo the proper forum for an open Issue like this, or would [nodeschool/discussions](https://github.com/nodeschool/discussions/issues) be more appropriate? 'organizers' seems more long-view-oriented IMHO

**Comment by jasonrhodes** [comment]
`discussions` is _probably_ a better fit but there are no rules, do whatever you think makes the most sense. The only advantage I can see to moving it to discussions is you *might* get more eyeballs on it naturally, but I'm not sure if that's true. 

Also: don't wait on starting this page! Get it up with whatever you have, people can add to it rather than adding to this thread and making you do all the work! :)

**Comment by cantremember** [comment]
point taken.  i plan to start the authoring process after i actually *do* my first Mentoring role later this month.  until then, pile 'em on ...

**Comment by cantremember** [comment]
*aaaaand* ... it's already been done -- by **you**, @jasonrhodes 

https://github.com/node-forward/mentors

 :+1:

**Comment by linclark** [comment]
I think the Node Forward mentoring program is kind of different than the mentoring for Node School, but I might be wrong.

**Comment by cantremember** [comment]
you make a good point, @linclark .  in fact, that repo doesn't yet contain the content i'd like to author

but it's an excellent starting resource, can be forked, and would be a suitable place to address similar themes about mentoring across our groups.  i see no reason there wouldn't be crossover -- with @jasonrhodes permission of course

**Comment by jasonrhodes** [comment]
Oh you definitely don't need my permission, that repo isn't mine! I just work on it with some others (and I've been MIA there for a while, need to fix that).

However, @linclark is right, the node-forward mentoring program is about long-term mentoring relationships, 1:1, learning node and potentially expanding out from there. The content talked about in this thread, I thought, was more specific to how to be a good mentor at a NodeSchool event, which would be different enough in my opinion that I'm not sure even a fork makes sense there.

Does that make sense?

**Comment by cantremember** [comment]
yah.  i can see that

*darn it.*  i have to re-open the ticket

> /me kicks ground

**Comment by cantremember** [comment]
- @llkats has opened https://github.com/nodeschool/sanfrancisco/issues/68
- @maxogden & @trosetty have made progress on [Event Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices)
- i will be contributing to [Mentorship Guidelines and Advice](https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice)

at some point, they will all be aggregated into gloriousness
